Fix taxonomy page styles
ymcatwincities/openy pull request #102
Opened 2017-02-02 11:15 UTC by hamrant

Jira - https://propeople-us.atlassian.net/browse/OYPD-183

Steps for review:
login as admin
go to /blog/start-training-now-y-run
click on Category: "Community Outreach" link -  (/taxonomy/term/17)
check that that blog teasers looks fine (not beautiful but fine)
profit

2017-02-02 11:18 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build331

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/331/

2017-02-02 11:20 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build331/profiles/openy/build/reports/behat

2017-02-02 13:33 UTC, Sanchiz commented
@hamrat I think it would be better to do following things:
- Override taxonomy page template for this vocabulary and add markup for grid(layout should be as on one column page)
- Remove "Subscribe to Community Outreach"
- Would be nice to add pathauto pattern to generate good URL aliases for this vocabulary

2017-02-02 15:20 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build335

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/335/

2017-02-02 15:22 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build335/profiles/openy/build/reports/behat

2017-02-02 15:45 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build336

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/336/

2017-02-02 15:47 UTC, alexschedrov requested changes

2017-02-02 15:47 UTC, Sanchiz commented on config/install/system.site.yml
> +name: Site-Install
Let's change to "Open Y Distribution"

2017-02-02 15:47 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build336/profiles/openy/build/reports/behat

2017-02-02 15:47 UTC, alexschedrov requested changes

2017-02-02 15:47 UTC, Sanchiz commented on modules/openy_features/openy_taxonomy/config/install/views.view.taxonomy_term.yml
> +_core:
Please get rid of hash.

2017-02-02 16:00 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build337

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/337/

2017-02-02 16:02 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build337/profiles/openy/build/reports/behat

2017-02-02 16:07 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build338

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/338/

2017-02-02 16:08 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build338/profiles/openy/build/reports/behat

2017-02-02 16:18 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build339

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/339/

2017-02-02 16:20 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build339/profiles/openy/build/reports/behat

2017-02-03 09:18 UTC, Sanchiz commented
retest this please

2017-02-03 09:21 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/347/

**Build Log**
*last 25 lines*

 ```
[...truncated 203 lines...]
stdout: You are about to create a /var/www/build347/sites/default/settings.php file and CREATE the 'drupal347' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-03 09:25 UTC, Sanchiz commented
retest this please

2017-02-03 09:28 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build348

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/348/

2017-02-03 09:29 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build348/profiles/openy/build/reports/behat

2017-02-03 09:30 UTC, alexschedrov approved these changes
Approved.

2017-02-03 09:30 UTC, merged