OS-26 Location list page modifications
ymcatwincities/openy pull request #1022
Opened 2018-05-02 13:27 UTC by rotator

**Steps for review**
After installation or update OpenY profile you can check modified settings form in OpenY Map module /admin/config/services/openy_map with all settings for Location list page and explanations how to add new location content type to Locations search.

@podarok Please, review

2018-05-02 13:29 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-05-03 13:38 UTC, podarok commented
ok to test

2018-05-03 14:05 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build308 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build308 |
| Installation process | http://install.openy-dev.ffwua.com/build308/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/308/

2018-05-03 14:10 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build308/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build308/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build308/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build308/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build308/blogWCAG2AAhtmlcs.txt

2018-05-04 07:35 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build311 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build311 |
| Installation process | http://install.openy-dev.ffwua.com/build311/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/311/

2018-05-04 07:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build311/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build311/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build311/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build311/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build311/blogWCAG2AAhtmlcs.txt

2018-05-07 13:11 UTC, podarok requested changes
Code needs some love

2018-05-07 13:11 UTC, podarok commented on modules/custom/location_finder/src/Plugin/Block/LocationFinder.php
> +    // Location view
Could you setup PHPStorm to be using Drupal code style formatting?

2018-05-07 13:11 UTC, podarok commented on modules/custom/location_finder/src/Plugin/Block/LocationFinder.php
> +    // Location view
Should be fullstop

2018-05-07 13:11 UTC, podarok commented on modules/custom/location_finder/src/Plugin/Block/LocationFinder.php
> +    // Render Locations block display with changed arguments
Fullstop, please

2018-05-07 13:11 UTC, podarok commented on modules/custom/openy_map/src/Form/SettingsForm.php
> +                              OpenyMapManager $openy_map_manager) {
This looks like not a Drupal code style. Could you fix it?

2018-05-07 13:11 UTC, podarok commented on modules/custom/openy_map/src/OpenyMapManager.php
> +                              EntityFieldManagerInterface $entity_field_manager) {
Not a Drupal code style, please fix

2018-05-07 13:11 UTC, podarok commented on modules/custom/openy_map/src/OpenyMapManager.php
> +}
New line please, needed everywhere for better git diff
https://www.drupal.org/docs/develop/standards/coding-standards#indenting

2018-05-08 15:00 UTC, podarok submitted a review, later dismissed

2018-05-08 15:01 UTC, podarok commented
@kolesnikoff is it possible to get video how to use this feature?
It looks like highly complicated from the step by step description

2018-05-08 15:06 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build330 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build330 |
| Installation process | http://install.openy-dev.ffwua.com/build330/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/330/

2018-05-08 15:11 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build330/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build330/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build330/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build330/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build330/blogWCAG2AAhtmlcs.txt

2018-05-08 15:12 UTC, podarok commented
![image](https://user-images.githubusercontent.com/563412/39765821-633788a0-52eb-11e8-83c8-76fb4391f3f7.png)
Icons should respect installation in subfolder.
Please fix

2018-05-08 15:14 UTC, podarok requested changes

2018-05-08 15:14 UTC, podarok commented on modules/custom/openy_map/src/Form/SettingsForm.php
> +          $fileOptions[$path] = '<img src="' . $path . '" />';
Images should recpect subfolder installation

2018-05-09 13:53 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build342 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build342 |
| Installation process | http://install.openy-dev.ffwua.com/build342/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/342/

2018-05-09 13:58 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build342/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build342/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build342/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build342/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build342/blogWCAG2AAhtmlcs.txt

2018-05-09 14:11 UTC, podarok commented
Functionality looks like not working
![image](https://user-images.githubusercontent.com/563412/39819361-eff4439e-53ab-11e8-8095-6ff1f9854008.png)
![image](https://user-images.githubusercontent.com/563412/39819367-f30ec87e-53ab-11e8-9246-7474b55af42b.png)

2018-05-09 14:13 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build343 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build343 |
| Installation process | http://install.openy-dev.ffwua.com/build343/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/343/

2018-05-09 14:18 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build343/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build343/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build343/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build343/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build343/blogWCAG2AAhtmlcs.txt

2018-05-09 19:00 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build346 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build346 |
| Installation process | http://install.openy-dev.ffwua.com/build346/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/346/

2018-05-09 19:05 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build346/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build346/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build346/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build346/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build346/blogWCAG2AAhtmlcs.txt

2018-05-16 12:00 UTC, merged

2018-05-16 12:01 UTC, podarok commented
Go go go @kolesnikoff