[1046] Paragraph links render issue
ymcatwincities/openy pull request #1054
Opened 2018-05-22 13:55 UTC by rotator

Paragraphs template fixes for issue #1046

2018-05-22 14:20 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build385 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build385 |
| Installation process | http://install.openy-dev.ffwua.com/build385/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/385/

2018-05-22 14:25 UTC, bjwilkins commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build385/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build385/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build385/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build385/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build385/blogWCAG2AAhtmlcs.txt

2018-05-23 12:09 UTC, podarok requested changes
Should be fixed

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_lily/templates/paragraphs/paragraph--gallery--default.html.twig
> +              {% if paragraph.field_prgf_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_lily/templates/paragraphs/paragraph--grid-columns.html.twig
> +      {% if paragraph.field_prgf_clm_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_lily/templates/paragraphs/paragraph--teaser--default.html.twig
> +    {% if paragraph.field_prgf_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--banner.html.twig
> +          {% if paragraph.field_prgf_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +          {% if paragraph.field_prgf_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--grid-columns.html.twig
> +      {% if paragraph.field_prgf_clm_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 12:09 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--teaser--default.html.twig
> +    {% if paragraph.field_prgf_link.0.uri %}
It is safe to use content here, not a paragraph
If uri is not defined - you'll get error 500 on template level

2018-05-23 16:05 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build397 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build397 |
| Installation process | http://install.openy-dev.ffwua.com/build397/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/397/

2018-05-23 16:10 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build397/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build397/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build397/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build397/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build397/blogWCAG2AAhtmlcs.txt

2018-05-24 06:24 UTC, podarok approved these changes
Great, thank you

2018-05-24 06:24 UTC, merged