[813] Membership calculator issues
ymcatwincities/openy pull request #1061
Opened 2018-05-24 14:14 UTC by rotator

More info: #813 issue.

2018-05-24 14:40 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build403 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build403 |
| Installation process | http://install.openy-dev.ffwua.com/build403/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/403/

2018-05-24 14:45 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build403/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build403/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build403/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build403/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build403/blogWCAG2AAhtmlcs.txt

2018-05-24 16:52 UTC, podarok requested changes
small fix, all other looks good

2018-05-24 16:52 UTC, podarok commented on modules/custom/openy_calc/src/CalcDataWrapper.php
> +        'icon' => file_create_url($uri),
file_create_url creates absolute url, which is not always good
Can we return only relative path from parse_url here?

2018-05-31 11:05 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build428 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build428 |
| Installation process | http://install.openy-dev.ffwua.com/build428/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/428/

2018-05-31 11:10 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build428/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build428/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build428/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build428/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build428/blogWCAG2AAhtmlcs.txt

2018-06-01 06:41 UTC, merged