Refactor OpenY upgrade tool
ymcatwincities/openy pull request #1084
Opened 2018-06-07 06:25 UTC by podarok

There is a hard rule which can't be skipped, and should be rethinked from the foundation
OpenY upgrade tool stops config updates when there is a manual change detected.
Which is wrong in terms of maintenance and upgrade.
There are other issues we need to address https://github.com/ymcatwincities/openy/issues/675

User story
I'm an OpenY developer and I need to upgrade from 8.0.1 to 8.1.12
For that, because of large number of updates and impossibility to predict quality of upgrade path support for the contrib modules it is impossible to upgrade in one leap - from 8.0.1 to 8.1.12. 
For that I have to update from version to version, relying on some investigation from the OpenY community https://github.com/ymcatwincities/openy/wiki/%5BDraft%5D-OpenY-upgrade-how-to-for-Developers
Thus, after first detected manually changed config I'm blocked from upgradig to latest version of OpenY with a huge scope in front of me
As a better resolution I'd like to be able to update to latest version even if my configs and manual changes are overridden. 
And as a feature from OpenY upgrade tool would be cool to keep is to show the diff between latest config from updated OpenY version of my site and old config that was overridden during upgrade

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-06-07 06:47 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build472 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build472 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build472 |
| Installation process | http://install.openy.cibox.tools/build472/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/472/

2018-06-07 06:47 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build472/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build472/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build472/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build472/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build472/blogWCAG2AAhtmlcs.txt

2018-06-08 15:41 UTC, hamrant commented
I think we need to do next things:
- No need to change `isManuallyChanged` function, we need to modify places where it used:
`openy/modules/custom/openy_upgrade_tool/src/ConfigParamUpgradeTool.php`
```php
if ($this->isManuallyChanged($config_name)) {
      // Skip config update and log this to logger entity.
      $this->updateLoggerEntity($config, $config_name, $param);
      $dashboard_url = Url::fromRoute('view.openy_upgrade_dashboard.page_1');
      $dashboard_link = Link::fromTextAndUrl(t('OpenY upgrade dashboard'), $dashboard_url);
      $this->logger->error($this->t('Cannot update config @name. Please add those changes manually. More info here - @link.',
        [
          '@name' => $config_name,
          '@link' => $dashboard_link->toString(),
        ]
      ));
      return;
    }
```
And same in `openy/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php`
- First of all we need to log here config overriding event (warning for user that openy override modified config with link to upgrade dashboard, where user can view diff with old config)
- we need to add new field to logger entity and store here full config before override.
- after this - modify diff logic and compare active storage with full config from logger entity (instead of config file from openy), in this case no need to store in logger entity path to config or updated param and we can delete this fields.
- check how it will work on sites with already created logger entities and provide smooth upgrade path

cc @podarok @Sanchiz @ddrozdik

2018-07-19 19:18 UTC, podarok commented
@hamrant the only issue is that every composer run you'll get old version of upgrade tool
So we need to probably inject patch somehow to be able to proceed for the older version users

2018-08-16 06:43 UTC, danylevskyi requested changes
We need to rethink this :)

2018-12-11 21:49 UTC, ddrozdik commented
@hamrant it's time to resolve this issue and close this PR

2019-01-09 16:28 UTC, ddrozdik commented
@podarok at this moment our team work on building a new upgrade path tool that will fix issues you described in this PR. I suggest closing it as not relevant anymore.

2019-01-09 17:14 UTC, podarok commented
ok, thanks

2019-01-09 17:14 UTC, closed without merging

2019-01-18 18:46 UTC, hamrant commented
This was implemented here - https://github.com/ymcatwincities/openy/pull/1466
Seem that code that was changed in PR not modified from first upgrade path release, we can use this patch for any Open Y version.

cc @podarok @ddrozdik