Daxko API v2 integration fixes
ymcatwincities/openy pull request #1110
Opened 2018-06-20 12:47 UTC by rotator

Module for Daxko API v2 integration had some errors. PR will fix it.
1. Upon data parsing received from Daxko, an error appears because parser expects string values instead of arrays. => Added default json_encode() for not string values.
2. ImportForm.php:runMigration() (line 263)  ---> $migration = \Drupal::service('plugin.manager.migration')->createInstance($migrationId);  -- this piece of code returns unexpected result. => There was an error with saving CSV file with Daxko data for import. 
3. After creating new Session node during import new related Session Instances will be created with Session node data. Date in Session Instance store in timestamp with limitation from '1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999'. There was SQL error after attempt to save timestamp value out of this range. => Added check for timestamp value.

@podarok please, review it.

2018-06-20 13:13 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build505 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build505 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build505 |
| Installation process | http://install.openy.cibox.tools/build505/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/505/

2018-06-20 13:13 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build505/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build505/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build505/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build505/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build505/blogWCAG2AAhtmlcs.txt

2018-06-28 14:05 UTC, podarok requested changes
Small change to get merged, please

2018-06-28 14:05 UTC, podarok commented on modules/custom/openy_daxko2/src/Plugin/migrate/process/OpenYDaxkoSchedule.php
> +    $maxDt->setTimestamp(2147483647);
Let's make this as a constant, it is better to avoid hardcoded variables in the code

2018-06-28 14:05 UTC, podarok commented on modules/custom/openy_daxko2/src/Plugin/migrate/process/OpenYDaxkoSchedule.php
> +      if (strtotime($startDate) > 2147483647) {
constant, please

2018-06-28 14:05 UTC, podarok commented on modules/custom/openy_daxko2/src/Plugin/migrate/process/OpenYDaxkoSchedule.php
> +      if (strtotime($endDate) > 2147483647) {
constatnt, please

2018-07-05 13:28 UTC, rotator commented
Right, fixed

2018-07-05 14:04 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build568 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build568 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build568 |
| Installation process | http://install.openy.cibox.tools/build568/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/568/

2018-07-05 14:26 UTC, bjwilkins commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build569 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build569 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build569 |
| Installation process | http://install.openy.cibox.tools/build569/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/569/

2018-07-05 14:27 UTC, bjwilkins commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build569/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build569/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build569/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build569/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build569/blogWCAG2AAhtmlcs.txt

2018-07-20 15:22 UTC, jediandrey commented
@podarok please review

2019-04-24 07:00 UTC, kolesnikoff commented
@podarok is this PR still needed? Should it be merged into 2.0 or closed?

2019-05-24 15:51 UTC, ygerasimov commented
We have changed the way OpenY integrates with Daxko. Now we do not do import (like this PR) but rather use Daxko API calls live when powering Activity Finder. Closing this PR.

2019-05-24 15:51 UTC, closed without merging