Add entity reference selection plugins
ymcatwincities/openy pull request #1118
Opened 2018-06-26 09:54 UTC by hamrant

## Info
In `ymcatwincities:decoupling` branch we have created` OpenY Entity Reference Tweaks` module, and some of openy custom modules depend on hook number where `openy_er` enabled. On every code back porting from `ymcatwincities:8.x-1.x` branch we have broken builds. To avoid this issue every time we decide to move this module with hook_update to `ymcatwincities:8.x-1.x` branch 

## Steps for review

- [ ] Login as admin
- [ ] Go to /admin/modules
- [ ] Check that OpenY Entity Reference Tweaks module is enabled

2018-06-26 09:56 UTC, AndreyMaximov approved these changes

2018-06-26 10:18 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build517 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build517 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build517 |
| Installation process | http://install.openy.cibox.tools/build517/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/517/

2018-06-26 21:29 UTC, podarok commented
all new features should go to major version branch, which is 8.x-1.13-dev now @hamrant

2018-06-26 21:30 UTC, podarok commented
retest this please

2018-06-26 21:31 UTC, podarok requested changes
I don't understand why we have changes to theme here
Looks like some other code was pulled to the source branch

2018-06-26 21:55 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build533 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build533 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build533 |
| Installation process | http://install.openy.cibox.tools/build533/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/533/

2018-07-02 11:56 UTC, hamrant commented
@podarok looks like this is some changes that exist in `8.x-1.x` but not merged to `8.x-1.13-dev`. I will update this PR later

2018-07-10 08:44 UTC, podarok approved these changes

2018-07-10 08:44 UTC, merged

2018-07-10 08:53 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build579 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build579 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build579 |
| Installation process | http://install.openy.cibox.tools/build579/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/579/

2018-07-10 08:54 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build579/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build579/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build579/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build579/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build579/blogWCAG2AAhtmlcs.txt