[OPENY-72] openy_addthis decoupling
ymcatwincities/openy pull request #1141
Opened 2018-07-02 13:30 UTC by hamrant

## Steps for review

- [ ] Login as admin
- [ ] go to any blog or news page
- [ ] check that you can see social sharing block
- [ ] create new landing page with "Social share icons" paragraph
- [ ] check that you can see social sharing block
- [ ] go to /admin/modules/uninstall
- [ ] uninstall "OpenY Demo AddThis" module
- [ ] check that you can see "Remove field values: addthis on entity type Content." message with link for "Openy addThis" module
![uninstall-addthis](https://user-images.githubusercontent.com/13733670/42166682-6cfde75e-7e14-11e8-97f7-2d23449428b4.png)
- [ ] Click on link "Remove field values"
- [ ] Press "Delete all addthis field values" button on form
- [ ] After this you will be redirected back to  /admin/modules/uninstall
- [ ] check that now you can uninstall "Openy addThis" module
- [ ] uninstall "OpenY AddThis" module
- [ ] go to /admin/structure/paragraphs_type
- [ ] check that  "Social share icons" paragraph not exist in this list
- [ ] go to any blog or news page
- [ ] check that  "Social share icons" not exist in this pages
- [ ] also check created landing page with this paragraph
- [ ] go to /admin/modules
- [ ] install "OpenY AddThis" and  "OpenY Demo AddThis"  modules (Demo module contain openy_addthis.settings.public_id)
- [ ] go to any blog page and resave node - check that you can see  "Social share icons" on blog page
- [ ] check that all components related to "OpenY AddThis" module was restored and works fine

2018-07-02 13:56 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build548 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build548 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build548 |
| Installation process | http://install.openy.cibox.tools/build548/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/548/

2018-07-02 16:59 UTC, ddrozdik approved these changes

2018-07-03 10:32 UTC, podarok requested changes

2018-07-03 10:32 UTC, podarok commented on modules/custom/openy_addthis/src/Form/PrepareUninstallForm.php
> +    $db_connection = Database::getConnection();
could you use Dependency Injection to pass DB connection?

2018-07-03 11:03 UTC, podarok approved these changes

2018-07-03 12:22 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build556 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build556 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build556 |
| Installation process | http://install.openy.cibox.tools/build556/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/556/

2018-07-03 12:23 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build556/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build556/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build556/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build556/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build556/blogWCAG2AAhtmlcs.txt

2018-07-03 13:02 UTC, merged