[OPENY-82] Facility CT decoupling
ymcatwincities/openy pull request #1184
Opened 2018-07-23 10:22 UTC by anprok

We can't do normal testing of this PR because "OpenY Camp" exist in dependencies in some OpenY modules and some of them can't be uninstalled 

``` Title         :  OpenY Facility
Required by   :  openy_node_session, openy_session_instance, openy_schedules, openy_prgf_schedule_search, openy_prgf_class_sessions, openy_prgf_loc_finder, openy, openy_demo_nlanding, openy_demo_nalert, 
                  openy_demo_tfacility, openy_demo_nfacility, openy_demo_nsessions  .```

## Steps for review

- [ ]  login as admin
- [ ]   go to /admin/content?title=&type=facility&status=All&langcode=All
- [ ]   Check that some facility nodes exist in this list
- [ ]   go to /admin/modules
- [ ]   install devel module
- [ ]   go to /devel/php
- [ ]   run code from hook_uninstall
- [ ]   return to /admin/content?title=&type=facility&status=All&langcode=All
- [ ]   check that facility nodes was removed
- [ ]   go to /admin/structure/types
- [ ]   check that "Facility" not exist in this list

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-07-23 10:23 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-07-23 19:13 UTC, ddrozdik approved these changes

2018-07-24 08:06 UTC, AlexNetman commented
ok to test

2018-07-24 08:39 UTC, ddrozdik commented
retest this please

2018-07-24 09:18 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build631 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build631 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build631 |
| Installation process | http://install.openy.cibox.tools/build631/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/631/

2018-07-24 09:19 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build631/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build631/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build631/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build631/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build631/blogWCAG2AAhtmlcs.txt

2018-07-24 10:13 UTC, ddrozdik commented
@anprok currently, `OpenY Facility` module has a lot of dependencies to content types that should not be in the list of direct dependencies, for example `OpenY Session`. First of all, we have to resolve these dependencies. See how we did this before #1118

2018-07-24 16:16 UTC, ddrozdik commented
@anprok there is no upgrade path for the modified configs. Please add upgrade path.

2018-07-25 05:04 UTC, podarok requested changes
Needs work

2018-07-25 05:04 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_facility/config/install/core.entity_form_display.node.facility.default.yml
> +    - content_moderation
No need to add content moderation for facility. This is the super rare case when Ys adding facilities.

2018-07-25 05:04 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_facility/config/install/core.entity_form_display.node.facility.default.yml
> +      placeholder: ''
Could we have placeholder added bu default?

2018-07-25 05:04 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_facility/config/install/core.entity_view_display.node.facility.default.yml
> +  addthis:
I don't like dependency from addthis here
Could we remove it?
add this should be on blogs, news, probably Landing Pages. But Facility  - no need

2018-07-25 05:04 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_facility_loc.yml
> +    expose: 0
we aren't exposing this field, let's remove dependency from dataLayer

2018-07-27 11:21 UTC, ddrozdik approved these changes

2018-07-27 11:23 UTC, ddrozdik commented
retest this please

2018-07-27 12:06 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build636 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build636 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build636 |
| Installation process | http://install.openy.cibox.tools/build636/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/636/

2018-07-27 12:59 UTC, podarok approved these changes

2018-07-27 15:28 UTC, merged