[OPENY-96] Add version to openy_font
ymcatwincities/openy pull request #1189
Opened 2018-07-25 16:49 UTC by anprok

OpenY FOnt module not required by any module

## Steps for review

- [ ] login as admin
- [ ] go to /admin/modules/uninstall
- [ ] Uninstall "OpenY Font"
- [ ] make sure that '/admin/config/user-interface/fonts` not work
- [ ] go to /admin/modules/install
- [ ] enable "OpenY Font"
- [ ] make sure that path is working /admin/config/user-interface/fonts

 

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-07-25 16:50 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-07-27 11:37 UTC, ddrozdik commented on modules/custom/openy_font/openy_font.info.yml
>  package: OpenY
Let's change package to the `OpenY (Deprecated)` And change description - `This module is deprecated and will be removed in future versions. Use FontYourFace module instead.`

2018-07-27 11:38 UTC, ddrozdik requested changes
Let's change package to the `OpenY (Deprecated)` And change description - `This module is deprecated and will be removed in future versions. Use FontYourFace module instead.`

2018-07-27 11:56 UTC, ddrozdik approved these changes

2018-07-27 11:57 UTC, merged