Make BRANCH AMENITIES fieldset collapsible
ymcatwincities/openy pull request #1200
Opened 2018-08-06 13:36 UTC by Fant0m771

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Go to admin area and add new content "Branch" type
- [ ] On adding page you should see "AMENITIES" collapsed fieldset

2018-08-06 13:38 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-08-08 09:25 UTC, ddrozdik requested changes
Upgrade path is missing.

2018-08-08 09:25 UTC, ddrozdik commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
> +    - content_moderation
Why content moderation added? there is no request to add it in the original issue.

2018-08-08 09:25 UTC, ddrozdik commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
> +        description: ''
Please provide a description, that will provide information about Amenities to the end user.

2018-08-08 09:25 UTC, ddrozdik commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
> +        formatter: open
should be collapsed by default

2018-10-08 16:46 UTC, ddrozdik commented
@Fant0m771 will you be able to finish this PR?

2018-10-16 08:02 UTC, podarok requested changes
@Fant0m771 please fix review comments

2018-12-11 21:51 UTC, ddrozdik commented
@Fant0m771 any plans to finish work on this PR?

2019-10-11 12:10 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-03-04 19:35 UTC, AndreyMaximov commented
@podarok this one can be closed as it was finalized in #1925

2020-04-07 17:13 UTC, closed without merging