Retention Campaign
ymcatwincities/openy pull request #1203
Opened 2018-08-09 16:20 UTC by kolesnikoff

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-08-09 16:39 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/721/

**Build Log**
*last 1000 lines*

 ```
[...truncated 610 lines...]
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/669/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/67/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/670/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/671/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/672/head^{commit} # timeout=10
 > git rev-parse remo [...]

2018-08-10 05:49 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/725/

**Build Log**
*last 1000 lines*

 ```
[...truncated 607 lines...]
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/669/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/67/head^{commit} # timeout=10
 > git rev-parse remot [...]

2018-08-10 06:04 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/726/

**Build Log**
*last 1000 lines*

 ```
[...truncated 600 lines...]
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse r [...]

2018-08-10 06:18 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/727/

**Build Log**
*last 1000 lines*

 ```
[...truncated 596 lines...]
 > git rev-parse remotes/origin/pr/532/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse [...]

2018-08-10 06:33 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/728/

**Build Log**
*last 1000 lines*

 ```
[...truncated 600 lines...]
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse r [...]

2018-08-10 07:36 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/731/

**Build Log**
*last 1000 lines*

 ```
[...truncated 601 lines...]
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse re [...]

2018-08-10 07:51 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/732/

**Build Log**
*last 1000 lines*

 ```
[...truncated 602 lines...]
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse re [...]

2018-08-10 08:01 UTC, podarok requested changes
3h of review
Thanks for this work, team. Impressive.

Down below are  major points should be fixed
### Architcture flaws:

- tons of custom fields - let's consider moving them to basefields for performance and easy of usage
- tons, tons of forms. Would be cool to rebuilds them in ReactJS, VueJS, or Angular. This will remove ~20% of drupal code and make life easier for everyone
- cache is disabled globally. Mistake must be fixed. Ys are not profit companies and adding additional servers for hosting applications with cache disabled - is a pain.

### Development issues
- Dependency Injection everywhere. I know, Drupal::something makes life easier on MVP level, but maintenance is a big part when it comes to distribution. Also - performance. static calls add memory consumption and non needed function calls.
- module, theme, libraries versions needed everywhere. When it comes to cache clearing during upgrade scripts, styles, without versions are pain in the butt
- Hardcoded values.
- dependency issues
- hook_update_N

### Documentation issues
Right now there is no any documentation integrated into OpenY Campaign @ymcagtc @YMCA-GTC 
Would be nice to create at least basic tutorials for the users to be able to setup a campaign.

I've marked all modules in this PR as OpenY Experimental

2018-08-10 08:01 UTC, podarok commented on composer.json
> +        "drupal/tzfield": "1.x-dev",
let's tie to specific hash of git

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/css/games/scratchcard.css
> +.hide {
c'mon, guys
We have ```hidden``` in Drupal core. Get used to standard classes, avoid reinventing the wheel

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/js/activityTracking.js
> +jQuery(function () {
why not drupalBehaviours?
We have to use behaviours, because of BigPipe
https://www.drupal.org/docs/8/api/javascript-api/javascript-api-overview

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/js/campaign-modal.js
> +(function ($, Drupal, drupalSettings) {
why not drupalBehaviours?
We have to use behaviours, because of BigPipe
https://www.drupal.org/docs/8/api/javascript-api/javascript-api-overview

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/js/games/scratchcard.js
> +var doc = document,
why not drupalBehaviours?
We have to use behaviours, because of BigPipe
https://www.drupal.org/docs/8/api/javascript-api/javascript-api-overview

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/js/marquee.js
> +(function ($, Drupal, drupalSettings) {
why not drupalBehaviours?
We have to use behaviours, because of BigPipe
https://www.drupal.org/docs/8/api/javascript-api/javascript-api-overview

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> +define('OPENY_THEME', 'openy_rose');
This should be settings

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> +  // Disable caching for the Campaign's pages.
why????
We have caching tools like invalidation
Could you explain why we should disable caching globally?
marking modules as experimental. 
Campaigns are sites with high traffic, without cache Ys will spend a lot of funds on hosting

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> +  /*$timezone = $form['field_campaign_timezone']['widget'][0]['value']['#default_value'];
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> + * {@inheritdoc}
this is a function, there is no inheritance, please provide correct docblocks

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> + * {@inheritdoc}
this is a function, there is no inheritance, please provide correct docblocks

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.module
> + * {@inheritdoc}
this is a function, there is no inheritance, please provide correct docblocks

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_custom_access: '\Drupal\openy_campaign\Controller\CampaignController::campaignPagesAccess'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_custom_access: '\Drupal\openy_campaign\Controller\CampaignController::campaignPagesAccess'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_custom_access: '\Drupal\openy_campaign\Controller\CampaignController::campaignPagesAccess'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_custom_access: '\Drupal\openy_campaign\Controller\CampaignController::campaignPagesAccess'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_permission: 'administer retention campaign'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    #_permission: 'administer retention campaign'
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/CampaignMenuService.php
> +    // ->condition('field_campaign_reg_start_date', $now->format(DATETIME_DATETIME_STORAGE_FORMAT), '<=')
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/CampaignScorecardService.php
> +  public static function create(Connection $connection, ContainerInterface $container) {
why $connection argument needed? It is not used

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/CampaignScorecardService.php
> +  public function __construct(Connection $connection, ContainerInterface $container) {
arguments sent by create method should be database and connection, connection and container used
looks like a weird error. How this code is working at all?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Controller/CampaignReportsController.php
> +    $result = \Drupal::service('openy_campaign.generate_campaign_scorecard')->generateLiveScorecard($node);
pass service via DI, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Controller/CampaignReportsController.php
> +    $result = \Drupal::service('openy_campaign.generate_campaign_scorecard')->generateLiveScorecard($node);
pass service via DI, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Controller/CampaignReportsController.php
> +    $renderer = \Drupal::service('renderer');
pass service via DI, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Entity/MemberCampaign.php
> +    // Payment type is of the selected in the Target Audience Setting from Campaign.
remove commented code

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Entity/MemberCheckin.php
> +  private function getActiveCampaignMembers() {
needs docblock

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/ActivityTrackingModalForm.php
> +    $term = Term::load($topTermId);
use ```$this->entityTypeManager->getStorage("taxonomy_term")``` instead of static call, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/ActivityTrackingModalForm.php
> +    $memberCampaign = MemberCampaign::load($memberCampaignId);
you have ```$this->entityTypeManager``` in this context, use it for avoiding static calls

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/ActivityTrackingModalForm.php
> +    $campaign = Node::load($campaignId);
you have ```$this->entityTypeManager``` in this context, use it for avoiding static calls

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/LeadershipBlockForm.php
> +    $campaign = Node::load($campaignId);
```$this->entityTypeManager->getStorage('node')->load($campaignId);``` please
You are using it above on like 226.

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/LeadershipBlockForm.php
> +      $topTerm = Term::load($categoryId);
```$this->entityTypeManager->getStorage("taxonomy_term")->load```, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberEmailEditForm.php
> +    $member = Member::load($member_id);
```$this->entityTypeManager->getStorage("$_member_machine_name_$")->load```, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberLoginForm.php
> +    $campaign = Node::load($campaignID);
```$this->entityTypeManager->getStorage("node")->load```, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberLoginForm.php
> +    $member = Member::loadMemberFromCRMData($membershipID);
$this->entityTypeManager->getStorage("$_member_$")->loadMemberFromCRMData```, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberRegisterForm.php
> +    $campaign = Node::load($campaignID);
via storage, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberRegisterForm.php
> +    /*if (!is_numeric($membershipID)) {
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberRegisterForm.php
> +    if ($memberCampaignID) {
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/WinnersBlockForm.php
> +    $connection = \Drupal::service('database');
let's get it via DI. Especially database!!!

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/WinnersCalculateForm.php
> +    $connection = \Drupal::service('database');
pass via DI, please.

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Form/WinnersCalculateForm.php
> +    $connection = \Drupal::service('database');
DI, please. You are using db in every method. SHould be in constructor as well as other \Drupal:: calls in this file

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/OpenYLocaleDate.php
> +class OpenYLocaleDate {
this class should be a service, looks like commonly needed

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignActivityStatisticsBlock.php
> +    $block['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignActivityStatisticsBlock.php
> +    $terms = Term::loadMultiple($tids);
get is via DI+ storage, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignActivityVisitsBlock.php
> +    $block['#cache']['max-age'] = 0;
why??????????

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignGameBlock.php
> +    $block['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignLeadershipBlock.php
> +    $block['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignMenuBlock.php
> +    $noCache = ['#cache' => ['max-age' => 0]];
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignRegisterBlock.php
> +    $block['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignRegisterBlock.php
> +        'max-age' => 0,
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignUserMenuBlock.php
> +    $build['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignWinnersBlock.php
> +    $block['#cache']['max-age'] = 0;
why?????
could you invalidate it at least every 5 minutes?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/QueueWorker/MemberVisitsWorkerUpdate.php
> +    $client = \Drupal::getContainer()->get('openy_campaign.client_factory')->getClient();
should be DI
this is a batch but you calling container every run. Take care about performance, please.
Maintenance is a flaw in whole codebase of the PR, guys (((

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/QueueWorker/MemberVisitsWorkerUpdate.php
> +      $logger = \Drupal::logger('openy_campaign_queue');
same here, why access container every loop? Could you pass pre-created logger channel to this class in constructor?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/QueueWorker/MemberVisitsWorkerUpdate.php
> +      $checkin->save();
due to the queue nature - we have to try catch possible exceptions here. Otherwise you'll get interrupted in the middle of the process

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/src/RegularUpdater.php
> +    $connection = \Drupal::service('database');
DI, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/games/flip-cards.html.twig
> +<div class="flip-cards">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/games/magic-ball.html.twig
> +<div class="back-link">{{ link }}</div>
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/games/scratchcard.html.twig
> +<div class="back-link">{{ link }}</div>
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-activity-block.html.twig
> +<div class="activity">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-activity-block.html.twig
> +            {# key should match 2017-08-12 pattern #}
this condition should be checked on preprocess and user input level, avoid of showing empty page without any messages on template level.

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-campaign-register.html.twig
> +<style scoped>
c'mon. Inline styles in templates are prohibited.
Maintenance will be a pain.
Could you move inline style to libraries and include library here, in template?

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-campaign-register.html.twig
> +    <div class="content-wrapper">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-campaign-register.html.twig
> +            height: {{  campaign.field_campaign_image.0.height }}px !important;
what if height equals 0?
You'll see white screen without content and tough to debug situation

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-games.html.twig
> +<div class="campaign-game">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-leadership.html.twig
> +<div class="leadership-wrapper">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-register-text.html.twig
> +<div class="campaign-link-collapsed">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-popup.html.twig
> +</div>
newline at the end of file, everywhere, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-scorecard.html.twig
> +      <th class="blue" colspan="4" align="center">EARLY REG ({{ result.dates.registration_start }} - {{ result.dates.registration_end }})</th>
translate strings everythere, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-scorecard.html.twig
> +<div class="campaign-scorecard">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-scorecard.html.twig
> +      <th class="blue-outline" colspan="9" align="center">Registration</th>
translate strings everywhere, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-scorecard.html.twig
> +      <td class="green" align="right" colspan="2">ASSOCIATION&nbsp;TOTAL:</td>
translate strings, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-visits-goal.html.twig
> +<div class="visits-goal">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-winner-stream.html.twig
> +{% if winners is not empty %}
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_campaign/templates/openy-campaign-winners.html.twig
> +<div class="winners-wrapper">
docblock with variables needed, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_font/src/Form/FontSettingsForm.php
> -    if (\Drupal::service('module_handler')->moduleExists('fontyourface')) {
let's keep it

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_interstitial/config/optional/block.block.interstitialcontentblock.yml
> +visibility: {  }
end of file, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/openy_interstitial/src/Plugin/Block/InterstitialContentBlock.php
> +    $block['#cache']['max-age'] = 0;
why????
Can we use cache invalidation?
Take care about performance, please

2018-08-10 08:01 UTC, podarok commented on modules/custom/personify/src/PersonifyClient.php
> +      'CL_GetCustomerBranchInformationInput' => [
Community Layer functions available for TwinCities only. @YMCA-GTC @ymcagtc help with managing this issue

2018-08-10 08:01 UTC, podarok commented on modules/custom/personify/src/PersonifyClient.php
> +      'CL_GetFacilityVisitCountByDateInput' => [
Community Layer functions available for TwinCities only. @YMCA-GTC @ymcagtc help with managing this issue

2018-08-10 08:01 UTC, podarok commented on modules/custom/personify/src/PersonifyClient.php
> +      'CL_GetFacilityVisitCountByDateInput' => [
Community Layer functions available for TwinCities only. @YMCA-GTC @ymcagtc help with managing this issue

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_demo_content/modules/openy_demo_ncampaign/config/install/migrate_plus.migration.node_campaign.yml
> +  #field_error_default
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_demo_content/modules/openy_demo_ncampaign/includes/openy_demo_ncampaign.members.inc
> +    // _openy_demo_ncampaign_activities_create($member);
remove commented code, please

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_editor/config/install/filter.format.full_html.yml
> +    status: true
ensure this is added to hook_update_N

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_end_date.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_expected_visits.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_fitness_category.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_game_description.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_game_short_info.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_game_title.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_image.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_image.yml
> +  max_filesize: ''
let's add limit 50M at least

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_membership_u_t.yml
> +    - datalayer
are we using this in dataLayer?
If no - let's remove module dependency
Make it globally, please

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_membership_u_t.yml
> +    expose: 0
we aren't using it!!!! No need for dependency.

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_menu.yml
> +    - datalayer
no need for dependency!!!

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_pages.yml
> +    - datalayer
no need for dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_palette.yml
> +    - datalayer
no need for dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_payment_types.yml
> +    - datalayer
remove dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_prize_coefficient.yml
> +    - datalayer
remove dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_prize_nowin.yml
> +    - datalayer
remove dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_prizes.yml
> +    - datalayer
remove dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_campaign/config/install/field.field.node.campaign.field_campaign_reg_end_date.yml
> +    - datalayer
remove dependency

2018-08-10 08:01 UTC, podarok commented on modules/openy_features/openy_taxonomy/modules/openy_txnm_fitness_category/config/install/field.storage.taxonomy_term.field_activity_icon.yml
> +custom_storage: false
number of fields above is so huge 
Let's consider to convert them to basefields and store in single table
Every field creates dedicated 2 tables in database.
Performance! Maintenance!
Looks like architecture flaw (((

2018-08-10 08:01 UTC, podarok commented on openy.install
> +  /*$theme_installer = \Drupal::service('theme_installer');
remove commented code

2018-08-10 08:01 UTC, podarok commented on openy.install
> +
remove empty lines, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/config/install/block.block.campaignusermenublock.yml
> +    - openy_rose
why needed dependency from openy_rose?

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/css/styles.css
> +@font-face {
include https://github.com/ymcatwincities/openy/blob/8.x-1.13-dev/themes/openy_themes/scss/modules.scss globals, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/css/styles.css
> +  &.Aquatics {
remove commented code

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/css/styles.css
> +  border: 1px solid #92278f;
all colors should be variables!

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/css/styles.css
> +  color: #92278f;
all colors should be variables!

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/base/_fonts.scss
> +$font-style-cachet-ubuntu: "Cachet W01 Book", 'Ubuntu Condensed', sans-serif;
secondary font should be Verdana accordingly to YMCA branding guidelines

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/base/_mixins.scss
> +  font-family: "Cachet W01 Book", 'Ubuntu Condensed', sans-serif;
Secondary font should be Verdana

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_dialog.scss
> +    font-family: "Cachet W01 Book";
use variable everywhere, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_dialog.scss
> +    color: #fff;
use color variables everywhere, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_dialog.scss
> +    background: #fff;
use color variables everywhere, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_forms.scss
> +      &.Aquatics {
remove commented code or store it in disabled folder as dedicated file if there is a need for it in the future

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_forms.scss
> +          border-bottom: 30px solid #fff;
colors as variables, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_forms.scss
> +      color: #0060ac;
colors as variables, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/modules/_page.scss
> +.node-422 {
????????
This code is not acceptable!!
You'll never have same node on different environments

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/scss/styles.scss
> +@import 'state/state';
import global module styles, please
https://github.com/ymcatwincities/openy/tree/8.x-1.13-dev/themes/openy_themes/scss

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/templates/block--system-branding-block.html.twig
> +    <a href="https://www.ymcamn.org/" title="{{ 'Home'|t }}" rel="home">
make url dynamic via theme layer, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_campaign_theme/templates/page/_includes/page--header--top-navs.html.twig
> +{% if not is_mobile %}
add docblock with all variables, please

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--campaign.html.twig
> +        <iframe style="top:-144px;position:absolute;border: 0;" src="https://ymcamn.org/header.html" width="100%" height="144"></iframe>
let's remove it or make it dynamic

2018-08-10 08:01 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--campaign.html.twig
> +        <iframe style="border: 0;" src="https://ymcamn.org/footer.html" width="100%" height="160"></iframe>
remove or make dynamically via openy_hf module

2018-08-10 08:04 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/733/

**Build Log**
*last 1000 lines*

 ```
[...truncated 605 lines...]
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse rem [...]

2018-08-10 08:19 UTC, bjwilkins commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/734/

**Build Log**
*last 1000 lines*

 ```
[...truncated 599 lines...]
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse r [...]

2018-08-10 08:33 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/735/

**Build Log**
*last 1000 lines*

 ```
[...truncated 603 lines...]
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse re [...]

2018-08-10 10:02 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/738/

**Build Log**
*last 1000 lines*

 ```
[...truncated 602 lines...]
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse re [...]

2018-08-14 08:42 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/778/

**Build Log**
*last 1000 lines*

 ```
[...truncated 631 lines...]
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/669/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/67/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/670/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/671/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/672/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/672/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/673/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/674/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/68/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/681/head^{commit} # timeout=10
 > git rev-parse remo [...]

2018-08-14 10:45 UTC, podarok approved these changes
Thanks, good cleanup
See comments for post release follow up

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberEmailEditForm.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Form/MemberRegistrationPortalForm.php
> +    // We shouldn't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Form/ScorecardForm.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignActivityStatisticsBlock.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignActivityVisitsBlock.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignGameBlock.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 10:45 UTC, podarok commented on modules/custom/openy_campaign/src/Plugin/Block/CampaignUserMenuBlock.php
> +    // We can't cache it.
we have user cache tags, or user context. https://www.drupal.org/docs/8/api/cache-api/cache-contexts
Let's work on this after release.

2018-08-14 11:03 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/786/

**Build Log**
*last 1000 lines*

 ```
[...truncated 620 lines...]
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/669/head^{commit} # timeout=10
 > git rev-parse remo [...]

2018-08-14 11:43 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/788/

**Build Log**
*last 1000 lines*

 ```
[...truncated 621 lines...]
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/660/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/661/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/662/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/663/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/664/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/666/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/667/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/668/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/669/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/67/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/670/head^{commit} # timeout=10
 > git rev-parse remot [...]

2018-08-14 11:44 UTC, podarok commented
we need to recreate a PR

2018-08-14 11:44 UTC, closed without merging