Programs Event Framework
ymcatwincities/openy pull request #1205
Opened 2018-08-10 14:52 UTC by ygerasimov

recreating PR from ygerasimov username.

2018-08-10 15:28 UTC, podarok requested changes
Needs some love
Overall - good progress

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_gxp/openy_gxp_example/openy_gxp_example.module
> +//function openy_gxp_example_openy_gxp_categories_csv_row_alter(&$row) {
remove commented code, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_gxp/src/Plugin/migrate/process/OpenYGXPCategory.php
> +//    {"title":"Cardio","description":"A great cardio experience...","activity":119}
remove commented code, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/js/repeat.js
> +        // this.$root.mounted();
remove commented code, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/js/vue/vue-router.js
> +  * vue-router v3.0.1
is it possible to add vue via composer into vendors  folder?

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/openy_repeat.libraries.yml
> +  version: VERSION
provide versions everywhere, please
Use 0.1 as initial

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Controller/RepeatController.php
> +    $connection = \Drupal::database();
pass database via DI, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Controller/RepeatController.php
> +    $classes = Node::loadMultiple($nids);
we can have tons of classes
loadmultiple is not an option, especially when you foreach array 
please splice array by 50 maximum

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
> +    $connection = \Drupal::database();
pass via DI, please
Take care about performance

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
> +    $connection = \Drupal::database();
DI

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
> +    $request_stack = \Drupal::service('request_stack');
DI, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesLocBlock.php
> +    $connection = \Drupal::database();
DI, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat/src/RepeatManager.php
> +    $moderation_wrapper = Drupal::service('openy_moderation_wrapper.entity_moderation_status');
DI, please

2018-08-10 15:28 UTC, podarok commented on modules/custom/openy_repeat_entity/src/Entity/RepeatInterface.php
> +}
please make all files 644, not 755
modules/custom/openy_schedules/js/openy_schedules.js

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/openy_demo_nlanding.module
> +  $parent_menu_link = \Drupal\menu_link_content\Entity\MenuLinkContent::load(39);
remove hardcoded ID

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_form_display.paragraph.session_time.default.yml
> +  moderation_state:
remove moderation dependency. We shouldn't moderate paragraphs globally

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_instructor.yml
> +    - datalayer
datalayer is not used, no need for dependency

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_plocation.yml
> +    expose: 0
datalayer is not used, no need for dependency

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
> +  - datalayer
both not needed
add module version, please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_schedule_categ.yml
> +    expose: 0
not used datalayer, no need for dependency

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_schedule_excl.yml
> +    expose: 0
remove datalayer dependency, please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_schedule_instr.yml
> +    expose: 0
remove datalayer dependency globally, please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/paragraphs.paragraphs_type.repeat_schedules.yml
> +description: null
add descriptions for all paragraps

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/openy_prgf_repeat_schedules.info.yml
> +  - datalayer
not used, remove please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules_loc/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_lschedules_prf.yml
> +    expose: 0
not used, remove dependency, please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules_loc/config/install/paragraphs.paragraphs_type.repeat_schedules_loc.yml
> +description: null
provide description, please

2018-08-10 15:28 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules_loc/openy_prgf_repeat_schedules_loc.info.yml
> +  - datalayer
not used, remove, please

2018-08-10 15:28 UTC, podarok commented on themes/openy_themes/openy_lily/sass/modules/_schedules.scss
> +  border: 1px solid #bababa;
colors as variables, please

2018-08-10 15:28 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build743 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build743 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build743 |
| Installation process | http://install.openy.cibox.tools/build743/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/743/

2018-08-10 15:29 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build743/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build743/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build743/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build743/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build743/blogWCAG2AAhtmlcs.txt

2018-08-10 16:04 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build744 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build744 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build744 |
| Installation process | http://install.openy.cibox.tools/build744/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/744/

2018-08-10 16:05 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build744/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build744/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build744/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build744/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build744/blogWCAG2AAhtmlcs.txt

2018-08-10 16:42 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build745 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build745 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build745 |
| Installation process | http://install.openy.cibox.tools/build745/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/745/

2018-08-10 16:42 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build745/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build745/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build745/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build745/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build745/blogWCAG2AAhtmlcs.txt

2018-08-10 17:15 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build746 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build746 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build746 |
| Installation process | http://install.openy.cibox.tools/build746/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/746/

2018-08-10 17:16 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build746/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build746/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build746/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build746/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build746/blogWCAG2AAhtmlcs.txt

2018-08-10 17:53 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build748 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build748 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build748 |
| Installation process | http://install.openy.cibox.tools/build748/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/748/

2018-08-10 17:54 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build748/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build748/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build748/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build748/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build748/blogWCAG2AAhtmlcs.txt

2018-08-10 18:29 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build749 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build749 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build749 |
| Installation process | http://install.openy.cibox.tools/build749/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/749/

2018-08-10 19:53 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build750 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build750 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build750 |
| Installation process | http://install.openy.cibox.tools/build750/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/750/

2018-08-10 20:27 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build751 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build751 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build751 |
| Installation process | http://install.openy.cibox.tools/build751/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/751/

2018-08-10 21:02 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build752 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build752 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build752 |
| Installation process | http://install.openy.cibox.tools/build752/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/752/

2018-08-10 21:04 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build752/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build752/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build752/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build752/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build752/blogWCAG2AAhtmlcs.txt

2018-08-13 06:51 UTC, podarok commented
retest this please

2018-08-13 07:27 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build753 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build753 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build753 |
| Installation process | http://install.openy.cibox.tools/build753/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/753/

2018-08-13 07:28 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build753/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build753/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build753/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build753/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build753/blogWCAG2AAhtmlcs.txt

2018-08-13 11:52 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build760 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build760 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build760 |
| Installation process | http://install.openy.cibox.tools/build760/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/760/

2018-08-13 11:53 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build760/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build760/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build760/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build760/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build760/blogWCAG2AAhtmlcs.txt

2018-08-13 16:05 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build768 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build768 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build768 |
| Installation process | http://install.openy.cibox.tools/build768/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/768/

2018-08-13 16:30 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build769 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build769 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build769 |
| Installation process | http://install.openy.cibox.tools/build769/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/769/

2018-08-13 18:50 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build772 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build772 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build772 |
| Installation process | http://install.openy.cibox.tools/build772/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/772/

2018-08-13 19:22 UTC, bjwilkins commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build773 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build773 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build773 |
| Installation process | http://install.openy.cibox.tools/build773/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/773/

2018-08-13 19:24 UTC, bjwilkins commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build773/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build773/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build773/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build773/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build773/blogWCAG2AAhtmlcs.txt

2018-08-13 20:03 UTC, podarok approved these changes

2018-08-13 20:04 UTC, merged