[OYPD-124] Entity browser enhancements
ymcatwincities/openy pull request #126
Opened 2017-02-07 23:16 UTC by david-hernandez

I'm making changes for image browser only at the moment, to make sure this is an accepted direction, and then I'll repeat for docs and video. They have to be done separately, unfortunately, because they have separate views, browsers, and forms.

Steps to review

- [ ] Add a node, for example landing page.
- [ ] Add content with WYSIWYG browser, for example "simple content" paragraph type.
- [ ] Click entity embed image icon to load pop up browser.
- [ ] Verify the gallery display looks good.
- [ ] Also verify the select item has a selected style.

2017-02-07 23:18 UTC, david-hernandez commented
![screen shot 2017-02-07 at 5 51 00 pm](https://cloud.githubusercontent.com/assets/1504038/22715995/a9c1673c-ed61-11e6-9625-7848e39b5c65.png)

![screen shot 2017-02-07 at 5 51 09 pm](https://cloud.githubusercontent.com/assets/1504038/22715994/a9bdc366-ed61-11e6-979f-16362962c0fd.png)

The selected image should have a blue halo.

2017-02-07 23:19 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build389/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build389

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/389/

2017-02-07 23:20 UTC, david-hernandez commented
Another note. I looked at both media module and lightening. This is mostly a copy from lightening. It looks good and is a much simpler implementation. If I would try to copy the js and css from media module it would require rewriting most of it as the structure of the form and markup isn't the same. Lightening is basically using the exact same setup as openy so it already matches everything.

2017-02-07 23:21 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build389/profiles/openy/build/reports/behat

2017-02-08 08:23 UTC, Sanchiz commented
retest this please

2017-02-08 08:26 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build392/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build392

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/392/

2017-02-08 08:28 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build392/profiles/openy/build/reports/behat

2017-02-08 08:33 UTC, Sanchiz commented
1. CodeSniffer errors http://openy-dev.ffwua.com/build392/build_reports/Drupalsniff.txt
2. Instead of load more we should keep mini pager or full page
4. Can we use another image style where all images will have the same width and height?
Example:
![image](https://cloud.githubusercontent.com/assets/1316234/22729041/995a3922-ede9-11e6-9ab0-0edc2aafb98d.png)
5. There's another entity browser preset that is visible when you upload image to field, not in WYSIWYG. There are following problems:
- weird padding at the bottom of browser
![image](https://cloud.githubusercontent.com/assets/1316234/22729065/b72964a0-ede9-11e6-9d54-0fed9cf77767.png)
- It's impossible to select image right now as in WYSIWYG media browser
- No styles for tabs and in WYSIWYG media browser

2017-02-08 16:16 UTC, david-hernandez commented
Update will look like this, with multiple selection possible.


![screen shot 2017-02-08 at 11 10 05 am](https://cloud.githubusercontent.com/assets/1504038/22745869/fb8dfe0c-edef-11e6-8b5e-5d8a27d7fd9f.png)
![screen shot 2017-02-08 at 11 10 18 am](https://cloud.githubusercontent.com/assets/1504038/22745870/fb8e74ae-edef-11e6-8f93-0175e79f5019.png)

2017-02-08 21:21 UTC, david-hernandez commented
Document is kind of tough. It will look like this unless I put a lot more work into it, which I'm not sure it is worth it at the moment. Video will likely have to look similar since we're mostly dealing with icon and name. We could probably do teasers if we're only dealing with youtube or something, but I don't know if that is the case. Can someone clarify if we can get thumbnail previews on all videos?

![screen shot 2017-02-08 at 4 17 33 pm](https://cloud.githubusercontent.com/assets/1504038/22757857/75f87ecc-ee1a-11e6-8540-c5a4db432151.png)

2017-02-08 21:35 UTC, david-hernandez commented
How do I test the document regular browser, not embed? I don't see any paragraphs that use it.

2017-02-08 22:44 UTC, david-hernandez commented
Same thing with videos. Is the embedding functionality even complete? It looks like you can only embed a teaser or thumbnail for a video which doesnt even make sense. Document might be the same.

![screen shot 2017-02-08 at 5 42 59 pm](https://cloud.githubusercontent.com/assets/1504038/22760821/270fea3c-ee26-11e6-96bd-c9c52c8dc86e.png)

2017-02-08 23:00 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build397

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/397/

2017-02-08 23:02 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build397/profiles/openy/build/reports/behat

2017-02-09 11:19 UTC, Sanchiz commented
retest this please

2017-02-09 11:22 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build401

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/401/

2017-02-09 11:24 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build401/profiles/openy/build/reports/behat

2017-02-09 12:18 UTC, Sanchiz commented
@david-hernandez Current version of thumbnails for Documents looks awesome! We don't need document thumbnails right now.

In order to test regular browser for Video and Document you can create test field and select appropriate browser.

### Images browser
1. White padding + overflow problems
![image](https://cloud.githubusercontent.com/assets/1316234/22782863/c3afa336-eed1-11e6-8c0f-a1bac23e73c2.png)
2. When selection hasn't been validated, grid looks broken
![image](https://cloud.githubusercontent.com/assets/1316234/22782922/ee0d6c3a-eed1-11e6-8d87-e706b49b747a.png)


## Documents browser
1. White padding + overflow problems
![image](https://cloud.githubusercontent.com/assets/1316234/22782934/f9e7a516-eed1-11e6-8729-501c1273e0cc.png)

## Video browser
1. White padding + overflow problems
![image](https://cloud.githubusercontent.com/assets/1316234/22783011/8bb4c32a-eed2-11e6-9236-93e6b6853392.png)

2017-02-09 12:19 UTC, alexschedrov requested changes
Code changes.

2017-02-09 12:19 UTC, Sanchiz commented on modules/openy_features/openy_media/js/browser.js
> +        //$selectables.not(this).removeClass('selected').find(input).prop('checked', false);
Let's remove if we aren't using it.

2017-02-09 12:19 UTC, Sanchiz commented on modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
> +  - views_infinite_scroll
Since pager has been reverted back to mini pager, we no longer need this in dependencies.

2017-02-09 14:07 UTC, david-hernandez commented
That should fix the padding and the validation issue. Also, removed to unneeded code.

![screen shot 2017-02-09 at 9 02 07 am](https://cloud.githubusercontent.com/assets/1504038/22786583/1c8c7aa4-eea7-11e6-8543-94fbcea2a7d2.png)
![screen shot 2017-02-09 at 9 01 40 am](https://cloud.githubusercontent.com/assets/1504038/22786582/1c8a5bd4-eea7-11e6-96bb-fa8d93e5137d.png)
![screen shot 2017-02-09 at 8 57 14 am](https://cloud.githubusercontent.com/assets/1504038/22786580/1c86e6c0-eea7-11e6-8706-613a7b81041d.png)
![screen shot 2017-02-09 at 8 56 55 am](https://cloud.githubusercontent.com/assets/1504038/22786581/1c895af4-eea7-11e6-9cbb-d4dfab58f916.png)
![screen shot 2017-02-09 at 8 51 56 am](https://cloud.githubusercontent.com/assets/1504038/22786584/1c9031f8-eea7-11e6-837b-c6a07cec8805.png)

2017-02-09 14:09 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build407

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/407/

2017-02-09 14:10 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build407/profiles/openy/build/reports/behat

2017-02-09 14:39 UTC, alexschedrov approved these changes
Approved.

2017-02-09 14:39 UTC, merged