[OPENY-144] Interface for enabling/disabling packages in Admin Interface
ymcatwincities/openy pull request #1268
Opened 2018-09-06 08:35 UTC by anprok

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature, please create PR against 8.x-1.xx-dev branch.

If this is a bug fix - use 8.x-1.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-09-06 11:36 UTC, gundevel commented
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/897/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #1268 of commit 17f82e43bbdd9a0536f00fc74fd8132e822ee6a2 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build897/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3724336179902715119.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
Build was aborted
Aborted by anonymous
Couldn't read comment file
java.io.FileNotFoundException: File '/var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace@2/build897/commentinfo.md' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:124)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

2018-09-06 11:38 UTC, ddrozdik commented
retest this please

2018-09-06 12:09 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build902/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build902/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build902/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build902/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build902/blogWCAG2AAhtmlcs.txt

2018-09-06 13:36 UTC, hamrant requested changes
1) `OpenY System` module must be enabled by default.
2) After package uninstall it redirects to standard modules uninstall page
3) Let's add to package description modules list (Like "Requires" section from description on standard modules list page)

2018-09-06 21:20 UTC, anprok commented
retest this please

2018-09-07 08:29 UTC, gundevel commented
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/908/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #1268 of commit 3a23b8e54f696deb44e6625b64d5ca775b57ff33 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER_COMPOSER/workspace/build908/openy-profile # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3940718532667469376.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
Could not remove the credential section from the git configuration
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 128:
stdout: 
stderr: remote: Counting objects: 9353, done.
remote: Compressing objects:   0% (1/5716)   
remote: Compressing objects:   1% (58/5716)   
remote: Compressing objects:   2% (115/5716)   
remote: Compressing objects:   3% (172/5716)   
remote: Compressing objects:   4% (229/5716)   
remote: Compressing objects:   5% (286/5716)   
remote: Compressing objects:   6% (343/5716)   
remote: Compressing objects:   7% (401/5716)   
remote: Compressing objects:   8% (458/5716)   
remote: Compressing objects:   9% (515/5716)   
remote: Compressing objects:  10% (572/5716)   
remote: Compressing objects:  11% (629/5716)   
remote: Compressing objects:  12% (686/5716)   
remote: Compressing objects:  13% (744/5716)   
remote: Compressing objects:  14% (801/5716)   
remote: Compressing objects:  15% (858/5716)   
remote: Compressing objects:  16% (915/5716)   
remote: Compressing objects:  17% (972/5716)   
remote: Compressing objects:  18% (1029/5716)   
remote: Compressing objects:  19% (1087/5716)   
remote: Compressing objects:  20% (1144/5716)   
remote: Compressing objects:  21% (1201/5716)   
remote: Compressing objects:  22% (1258/5716)   
remote: Compressing objects:  23% (1315/5716)   
remote: Compressing objects:  24% (1372/5716)   
remote: Compressing objects:  25% (1429/5716)   
remote: Compressing objects:  26% (1487/5716)   
remote: Compressing objects:  27% (1544/5716)   
remote: Compressing objects:  28% (1601/5716)   
remote: Compressing objects:  29% (1658/5716)   
remote: Compressing objects:  30% (1715/5716)   
remote: Compressing objects:  31% (1772/5716)   
remote: Compressing objects:  32% (1830/5716)   
remote: Compressing objects:  33% (1887/5716)   
remote: Compressing objects:  34% (1944/5716)   
remote: Compressing objects:  35% (2001/5716)   
remote: Compressing objects:  36% (2058/5716)   
remote: Compressing objects:  37% (2115/5716)   
remote: Compressing objects:  38% (2173/5716)   
remote: Compressing objects:  39% (2230/5716)   
remote: Compressing objects:  40% (2287/5716)   
remote: Compressing objects:  41% (2344/5716)   
remote: Compressing objects:  42% (2401/5716)   
remote: Compressing objects:  43% (2458/5716)   
remote: Compressing objects:  44% (2516/5716)   
remote: Compressing objects:  45% (2573/5716)   
remote: Compressing objects:  46% (2630/5716)   
remote: Compressing objects:  47% (2687/5716)   
remote: Compressing objects:  48% (2744/5716)   
remote: Compressing objects:  49% (2801/5716)   
remote: Compressing objects:  50% (2858/5716)   
remote: Compressing objects:  51% (2916/5716)   
remote: Compressing objects:  52% (2973/5716)   
remote: Compressing objects:  53% (3030/5716)   
remote: Compressing objects:  54% (3087/5716)   
remote: Compressing objects:  55% (3144/5716)   
remote: Compressing objects:  56% (3201/5716)   
remote: Compressing objects:  57% (3259/5716)   
remote: Compressing objects:  58% (3316/5716)   
remote: Compressing objects:  59% (3373/5716)   
remote: Compressing objects:  60% (3430/5716)   
remote: Compressing objects:  61% (3487/5716)   
remote: Compressing objects:  62% (3544/5716)   
remote: Compressing objects:  63% (3602/5716)   
remote: Compressing objects:  64% (3659/5716)   
remote: Compressing objects:  65% (3716/5716)   
remote: Compressing objects:  66% (3773/5716)   
remote: Compressing objects:  67% (3830/5716)   
remote: Compressing objects:  68% (3887/5716)   
remote: Compressing objects:  69% (3945/5716)   
remote: Compressing objects:  70% (4002/5716)   
remote: Compressing objects:  71% (4059/5716)   
remote: Compressing objects:  72% (4116/5716)   
remote: Compressing objects:  73% (4173/5716)   
remote: Compressing objects:  74% (4230/5716)   
remote: Compressing objects:  75% (4287/5716)   
remote: Compressing objects:  76% (4345/5716)   
remote: Compressing objects:  77% (4402/5716)   
remote: Compressing objects:  78% (4459/5716)   
remote: Compressing objects:  79% (4516/5716)   
remote: Compressing objects:  80% (4573/5716)   
remote: Compressing objects:  81% (4630/5716)   
remote: Compressing objects:  82% (4688/5716)   
remote: Compressing objects:  83% (4745/5716)   
remote: Compressing objects:  84% (4802/5716)   
remote: Compressing objects:  85% (4859/5716)   
remote: Compressing objects:  86% (4916/5716)   
remote: Compressing objects:  87% (4973/5716)   
remote: Compressing objects:  88% (5031/5716)   
remote: Compressing objects:  89% (5088/5716)   
remote: Compressing objects:  90% (5145/5716)   
remote: Compressing objects:  91% (5202/5716)   
remote: Compressing objects:  92% (5259/5716)   
remote: Compressing objects:  93% (5316/5716)   
remote: Compressing objects:  94% (5374/5716)   
remote: Compressing objects:  95% (5431/5716)   
remote: Compressing objects:  96% (5488/5716)   
remote: Compressing objects:  97% (5545/5716)   
remote: Compressing objects:  98% (5602/5716)   
remote: Compressing objects:  99% (5659/5716)   
remote: Compressing objects: 100% (5716/5716)   
remote: Compressing objects: 100% (5716/5716), done.
Receiving objects:   0% (1/9353)   
Receiving objects:   1% (94/9353)   
Receiving objects:   2% (188/9353)   
Receiving objects:   3% (281/9353)   
Receiving objects:   4% (375/9353)   
Receiving objects:   5% (468/9353)   
Receiving objects:   6% (562/9353)   
Receiving objects:   7% (655/9353)   
Receiving objects:   8% (749/9353)   
Receiving objects:   9% (842/9353)   
Receiving objects:  10% (936/9353)   
Receiving objects:  11% (1029/9353)   
Receiving objects:  12% (1123/9353)   
Receiving objects:  13% (1216/9353)   
Receiving objects:  14% (1310/9353)   
Receiving objects:  15% (1403/9353)   
Receiving objects:  16% (1497/9353)   
Receiving objects:  17% (1591/9353)   
Receiving objects:  18% (1684/9353)   
Receiving objects:  19% (1778/9353)   
Receiving objects:  20% (1871/9353)   
Receiving objects:  21% (1965/9353)   
Receiving objects:  22% (2058/9353)   
Receiving objects:  23% (2152/9353)   
Receiving objects:  24% (2245/9353)   
Receiving objects:  25% (2339/9353)   
Receiving objects:  26% (2432/9353)   
Receiving objects:  27% (2526/9353)   
Receiving objects:  28% (2619/9353)   
Receiving objects:  29% (2713/9353)   
Receiving objects:  30% (2806/9353)   
Receiving objects:  31% (2900/9353)   
Receiving objects:  32% (2993/9353)   
Receiving objects:  33% (3087/9353)   
Receiving objects:  34% (3181/9353)   
Receiving objects:  34% (3258/9353), 2.23 MiB | 4.42 MiB/s   
Receiving objects:  35% (3274/9353), 2.23 MiB | 4.42 MiB/s   
Receiving objects:  36% (3368/9353), 2.23 MiB | 4.42 MiB/s   
Receiving objects:  37% (3461/ [...]

2018-09-07 08:39 UTC, gundevel commented
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/909/

**Build Log**
*last 1000 lines*

 ```
[...truncated 92 lines...]
 > git rev-parse remotes/origin/pr/1047/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1048/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/105/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1052/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1053/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1054/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1055/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1057/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1058/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1059/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1059/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/106/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1060/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1061/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1062/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1064/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1065/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1066/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1071/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1073/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1074/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1075/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1076/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1079/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1080/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1081/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1082/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1090/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1091/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1094/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1095/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1098/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1099/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/11/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1100/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1102/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1103/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1104/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1105/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1106/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1119/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1120/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1121/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1123/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1124/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1125/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1126/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1127/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1128/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1129/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1137/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1138/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1139/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1141/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1142/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1144/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1146/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1147/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1148/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1149/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1150/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1151/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1154/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1155/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1160/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1161/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1162/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1163/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1166/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1167/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1168/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1169/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1170/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1171/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1174/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1175/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1176/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1177/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1179/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1180/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1181/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1182/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1183/head^{commit}  [...]

2018-09-07 08:39 UTC, gundevel commented
!!! Couldn't read comment file !!!
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/912/

**Build Log**
*last 1000 lines*

 ```
[...truncated 109 lines...]
 > git rev-parse remotes/origin/pr/1066/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1071/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1073/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1074/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1075/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1076/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1079/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1080/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1081/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1082/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1084/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1090/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1091/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1094/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1095/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1097/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1098/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1099/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/11/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1100/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1102/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1103/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1104/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1105/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1106/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1107/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1108/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1109/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1110/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1111/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1119/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/112/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1120/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1121/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1123/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1124/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1125/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1126/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1127/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1128/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1129/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/113/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1136/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1137/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1138/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1139/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/114/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1141/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1142/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1144/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1146/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1147/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1148/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1149/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/115/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1150/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1151/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1154/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1155/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/116/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1160/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1161/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1162/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1163/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1166/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1167/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1168/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1169/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/117/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1170/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1171/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1174/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1175/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1176/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1177/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1178/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1179/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/118/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1180/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1181/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1182/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1183/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1184/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1185/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1186/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1187/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1188/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1189/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/119/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1190/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1191/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1192/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1193/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1194/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1198/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1199/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/12/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/120/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/1200/head^{commit} # t [...]

2018-09-07 10:17 UTC, anprok commented
retest this please

2018-09-07 13:17 UTC, ddrozdik requested changes

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.routing.yml
> +openy_system.modules_uninstall:
I suggested creating a new structure for the Open Y menu items https://github.com/ymcatwincities/openy/issues/1045
Let's create a base in this PR and place these two new menu items in the following structure 
`Open Y -> Extend -> List && Uninstall`

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.routing.yml
> +    _title: 'OpenY Uninstall'
Change to `List`, see my comment above

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesListForm.php
> +      '#title' => $this->t('Filter modules'),
Change title to  `Filter packages`

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesListForm.php
> +
remove the empty line

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesListForm.php
> +        drupal_set_message($this->formatPlural(count($modules_to_install), 'Module %name has been enabled.', '@count modules have been enabled: %names.', [
Let's print a message that package was installed instead of modules

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesUninstallConfirmForm.php
> + * Builds a confirmation form to uninstall selected Open Y project modules.
packages not modules

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesUninstallForm.php
> +      '#title' => $this->t('Filter modules'),
Filter packages

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesUninstallForm.php
> + * Provides openy modules uninstall interface.
packages not modules

2018-09-07 13:17 UTC, ddrozdik commented on modules/custom/openy_system/src/Form/OpenyModulesUninstallForm.php
> +    // Iterate over each of the modules.
packages not modules

2018-09-07 21:31 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build921 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build921 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build921 |
| Installation process | http://install.openy.cibox.tools/build921/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/921/

2018-09-07 21:32 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build921/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build921/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build921/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build921/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build921/blogWCAG2AAhtmlcs.txt

2018-09-08 14:44 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build922 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build922 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build922 |
| Installation process | http://install.openy.cibox.tools/build922/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/922/

2018-09-08 14:45 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build922/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build922/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build922/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build922/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build922/blogWCAG2AAhtmlcs.txt

2018-09-09 09:59 UTC, ddrozdik commented
retest this please

2018-09-09 10:21 UTC, bjwilkins commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build925 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build925 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build925 |
| Installation process | http://install.openy.cibox.tools/build925/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/925/

2018-09-09 10:22 UTC, bjwilkins commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build925/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build925/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build925/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build925/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build925/blogWCAG2AAhtmlcs.txt

2018-09-10 08:04 UTC, ddrozdik approved these changes
All fixes to this PR will be added in the follow-up PR.

2018-09-10 08:07 UTC, merged