[OPENY-171] Incorporate all Open Y settings in one place
ymcatwincities/openy pull request #1352
Opened 2018-10-25 13:05 UTC by anprok

https://github.com/ymcatwincities/openy/issues/1045
## Steps for review

- [ ] login as admin.
- [ ] visit admin/openy .
- [ ] check menu tree works according to doc https://docs.google.com/document/d/1OoHpNe9A-Yy2eltPU0jviW5qTay4GKfNy-CzAuOxmsI.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2018-10-25 13:39 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1084 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1084 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1084 |
| Installation process | http://install.openy.cibox.tools/build1084/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1084/

2018-10-25 13:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1084/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1084/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1084/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1084/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1084/blogWCAG2AAhtmlcs.txt

2018-10-25 13:47 UTC, podarok approved these changes

2018-10-25 15:40 UTC, ddrozdik requested changes

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.routing.yml
> +    _title: 'Integration'
```suggestion
    _title: 'Open Y Integration'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.routing.yml
> +    _title: 'Extend'
```suggestion
    _title: 'Extend Open Y'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_addthis/openy_addthis.routing.yml
>      _title: 'Openy addThis'
```suggestion
    _title: 'AddThis settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on docs/Development/AddThis.md
In the line above replace `OpenY AddThis` to the `Open Y AddThis`

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_addthis/openy_addthis.links.menu.yml
> +  title: 'addThis settings'
```suggestion
  title: 'AddThis settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_addthis/openy_addthis.links.menu.yml
> +  description: 'Configure Open Y addThis settings.'
```suggestion
  description: 'Configure Open Y AddThis settings.'
```

2018-10-25 15:40 UTC, ddrozdik commented on docs/Development/AddThis.md
Also found a line in the code `Select list of content types where addThis should be enabled by default.` and change `addThis` to the `AddThis`. Try to find all such places.

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.links.menu.yml
> +  title: Open Y Retention Campaign
```suggestion
  title: Retention Campaign
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.links.menu.yml
> +  description: 'Configure Open Y retention campaign settings.'
```suggestion
  description: 'Configure Open Y Retention Campaign settings.'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.links.menu.yml
> +
```suggestion
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Member List'
```suggestion
    _title: 'Member List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Member List'
```suggestion
    _title: 'Member List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Add OpenY Member'
```suggestion
    _title: 'Add Retention Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Edit OpenY Member'
```suggestion
    _title: 'Edit Retention Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Delete OpenY Member'
```suggestion
    _title: 'Delete Retention Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign Delete All Members'
```suggestion
    _title: 'Delete All Members'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Member Campaign List'
```suggestion
    _title: 'Member Campaign List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
> +    _title: 'OpenY Retention Campaign'
```suggestion
    _title: 'Retention Campaign'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign Settings'
```suggestion
    _title: 'Campaign settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Delete OpenY Mapping Branch'
```suggestion
    _title: 'Delete Mapping Branch'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Edit OpenY Mapping Branch'
```suggestion
    _title: 'Edit Mapping Branch'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Add OpenY Mapping Branch'
```suggestion
    _title: 'Add Mapping Branch'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Mapping Branch List'
```suggestion
    _title: 'Mapping Branch List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Mapping Branch List'
```suggestion
    _title: 'Mapping Branch List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Edit OpenY Member Campaign'
```suggestion
    _title: 'Edit Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Add OpenY Member Campaign'
```suggestion
    _title: 'Add Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'Delete OpenY Member Campaign'
```suggestion
    _title: 'Delete Campaign Member'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_campaign/openy_campaign.routing.yml
>      _title: 'OpenY Campaign: Member Campaign List'
```suggestion
    _title: 'Member Campaign List'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_daxko2/README.md
>   - Imports Daxko Categories into OpenY Classes.
```suggestion
 - Imports Daxko Categories into Open Y Classes.
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_daxko2/README.md
>   - Imports Daxko Offerings into OpenY Sessions.
```suggestion
 - Imports Daxko Offerings into Open Y Sessions.
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.links.menu.yml
>    description: 'List Groupex Form Cache entities'
```suggestion
  description: 'List GroupEx Pro Form Cache entities'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.links.menu.yml
> +  description: 'Configure GroupEx Form Cache entities'
```suggestion
  description: 'Configure GroupEx Pro Form Cache entities'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_group_schedules/openy_group_schedules.links.menu.yml
> +  description: 'Configure GroupEx settings'
```suggestion
  description: 'Configure GroupEx Pro settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_gxp/README.md
>   - Imports Daxko Categories into OpenY Classes.
```suggestion
 - Imports Daxko Categories into Open Y Classes.
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_gxp/README.md
>   - Imports Daxko Offerings into OpenY Sessions.
```suggestion
 - Imports Daxko Offerings into Open Y Sessions.
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_gxp/openy_gxp.routing.yml
>      _title: 'Run GroupExPro Import'
```suggestion
    _title: 'Run GroupEx Pro Import'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_gxp/openy_gxp.routing.yml
>      _title: 'GroupExPro settings'
```suggestion
    _title: 'GroupEx Pro settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_map/openy_map.routing.yml
>      _title: 'OpenY Map settings'
```suggestion
    _title: 'Map settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_programs_search/openy_programs_search.routing.yml
>      _title: 'Programs Search settings'
```suggestion
    _title: 'Daxko Programs Search settings'
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.links.menu.yml
> +  title: Integration
```suggestion
  title: Integrations
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.links.menu.yml
> +
```suggestion
```

2018-10-25 15:40 UTC, ddrozdik commented on modules/custom/openy_system/openy_system.links.menu.yml
> +
```suggestion
```

2018-10-25 16:47 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1085 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1085 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1085 |
| Installation process | http://install.openy.cibox.tools/build1085/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1085/

2018-10-25 16:52 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1086 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1086 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1086 |
| Installation process | http://install.openy.cibox.tools/build1086/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1086/

2018-10-25 17:09 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1087 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1087 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1087 |
| Installation process | http://install.openy.cibox.tools/build1087/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1087/

2018-10-25 17:10 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1088 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1088 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1088 |
| Installation process | http://install.openy.cibox.tools/build1088/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1088/

2018-10-25 17:50 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1089 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1089 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1089 |
| Installation process | http://install.openy.cibox.tools/build1089/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1089/

2018-10-25 18:00 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1090 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1090 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1090 |
| Installation process | http://install.openy.cibox.tools/build1090/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1090/

2018-10-26 14:12 UTC, ddrozdik commented
retest this please

2018-10-26 15:00 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1092 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1092 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1092 |
| Installation process | http://install.openy.cibox.tools/build1092/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1092/

2018-10-26 15:35 UTC, ddrozdik commented
@anprok
- change `OpenY upgrade dashboard` to `Upgrade dashboard`, I have not found this title in the list of your changes. 
- change `No conflicts found during OpenY upgrade.` -> `No conflicts found during Open Y upgrade.`
- `/admin/openy/settings/openy_map` and `/admin/openy/integration/activenet` - do not have a description. Please add. 
- Session Instance settings is located under Open Y -> Settings menu but when I click it redirects me to `Home ->  Administration  -> Structure  -> Session Instances Listing -> Session Instance settings` It should be moved to the new structure. 
- The same thing as above with `Groupex Form Cache settings` page. also Fix `Groupex`, should be `GroupEx Pro`
- `/admin/openy/integration` chnage  title on this page to `Integrations`
- `GroupEx Form Cache list` opens a wrong URL and breadcrumbs are lost. 
- Change title on the page `/admin/openy/extend/list` from `List` to `Install` so we could have two menu items nstall and Uninstall

2018-10-29 11:56 UTC, anprok commented
> * change `OpenY upgrade dashboard` to `Upgrade dashboard`, I have not found this title in the list of your changes.

Here place where that menu title changed https://github.com/ymcatwincities/openy/pull/1352/files#diff-f1181ba5d8035c931f7fc8df75171e04R427

2018-10-29 12:17 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1096 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1096 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1096 |
| Installation process | http://install.openy.cibox.tools/build1096/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1096/

2018-10-31 08:50 UTC, ddrozdik commented
@anprok please make sure you have updated all documentation files where old paths are used. For example https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Daxko.md
Please check all of them to make sure documentation will have correct URLs.

2018-10-31 11:24 UTC, anprok commented
I double-checked routes in documentation, all routes updated

2018-10-31 11:54 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1104 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1104 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1104 |
| Installation process | http://install.openy.cibox.tools/build1104/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1104/

2018-11-06 05:55 UTC, ddrozdik commented
retest this please

2018-11-06 06:31 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1119 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1119 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1119 |
| Installation process | http://install.openy.cibox.tools/build1119/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1119/

2018-11-06 09:25 UTC, ddrozdik approved these changes

2018-11-06 15:57 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1128 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1128 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1128 |
| Installation process | http://install.openy.cibox.tools/build1128/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1128/

2018-11-06 16:09 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1128/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1128/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1128/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1128/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1128/blogWCAG2AAhtmlcs.txt

2018-11-07 11:01 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1133 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1133 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1133 |
| Installation process | http://install.openy.cibox.tools/build1133/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1133/

2018-11-07 11:02 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1133/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1133/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1133/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1133/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1133/blogWCAG2AAhtmlcs.txt

2018-11-08 11:58 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1137 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1137 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1137 |
| Installation process | http://install.openy.cibox.tools/build1137/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1137/

2018-11-08 11:59 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1137/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1137/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1137/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1137/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1137/blogWCAG2AAhtmlcs.txt

2018-11-08 14:12 UTC, merged