[OPENY-177] Decouple camp and location finder paragraph
ymcatwincities/openy pull request #1354
Opened 2018-10-26 14:01 UTC by anprok

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

2018-10-26 14:28 UTC, hamrant requested changes

2018-10-26 14:28 UTC, hamrant commented on modules/custom/openy_map/config/install/openy_map.settings.yml
>    camp: '/profiles/contrib/openy/modules/custom/openy_map/img/map_icon_green.png'
I think we need move all related to camps parts too

2018-10-26 14:28 UTC, hamrant commented on modules/custom/openy_map/openy_map.install
> + * Update description for fields.
wrong description

2018-10-26 14:28 UTC, hamrant commented on modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.install
> +    $config_factory
For this better to use $config_updater service, otherwise config will be mark as manual edited

2018-10-26 14:28 UTC, hamrant commented on modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.install
> +    $config_factory
For this better to use $config_updater service, otherwise config will be mark as manual edited

2018-10-26 14:28 UTC, hamrant commented on modules/custom/openy_map/config/install/openy_map.settings.yml
>    camp: '/profiles/contrib/openy/modules/custom/openy_map/img/map_icon_green.png'
I mean type_icons and etc

2018-10-26 14:47 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1091 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1091 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1091 |
| Installation process | http://install.openy.cibox.tools/build1091/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1091/

2018-10-26 15:10 UTC, hamrant approved these changes

2018-10-26 15:46 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1094 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1094 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1094 |
| Installation process | http://install.openy.cibox.tools/build1094/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1094/

2018-10-29 09:07 UTC, ddrozdik commented
retest this please

2018-10-29 09:41 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1095 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1095 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1095 |
| Installation process | http://install.openy.cibox.tools/build1095/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1095/

2018-10-29 09:55 UTC, ddrozdik approved these changes

2018-10-29 11:12 UTC, ddrozdik commented
@anprok After enabling Camps back they do not appear on the Location finder

2018-10-29 16:35 UTC, anprok commented
When removing the Camp package, the camp nodes are also deleted. Therefore, after re-enabling the camp package, you need to add camps manually. I have added the camp manually and it is displayed without problems.
![image](https://user-images.githubusercontent.com/16559938/47665296-709b9300-dba9-11e8-944e-85fef7141049.png)

2018-10-29 16:41 UTC, merged