[OPENY-178] Include modules in package
ymcatwincities/openy pull request #1360
Opened 2018-10-30 14:49 UTC by anprok

2018-10-30 15:23 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1101 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1101 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1101 |
| Installation process | http://install.openy.cibox.tools/build1101/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1101/

2018-10-30 15:37 UTC, ddrozdik requested changes

2018-10-30 15:37 UTC, ddrozdik commented on modules/custom/openy_development/openy_development.info.yml
> +# @todo Module machine name should be changed to openy_ci after upgrade all sites to OpenY 2.0
```suggestion
# @todo Module machine name should be changed to openy_ci after switching CI to OpenY 2.0
```

2018-10-31 10:15 UTC, ddrozdik requested changes

2018-10-31 10:15 UTC, ddrozdik commented on openy.packages.yml
> +    - openy_field_hours
@anprok please check what is the difference between all 3 fields `openy_field_hours`,  `openy_field_custom_hours` and `openy_field_holiday_hours `. 
I think they will conflict with each other if enable all of them at the same time. I guess the original idea was to replace default fields with these two extended modules. If so, let's remove them from the list of package and create a new package for each of them.

2018-11-06 07:45 UTC, podarok approved these changes

2018-11-06 07:45 UTC, podarok commented on openy.packages.yml
> +    - openy_field_hours
These are different fields, @ddrozdik

2018-11-06 14:38 UTC, ddrozdik approved these changes

2018-11-06 14:55 UTC, merged

2018-11-06 15:54 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1127 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1127 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1127 |
| Installation process | http://install.openy.cibox.tools/build1127/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1127/