[OYPD-241] Google Map API during installation.
ymcatwincities/openy pull request #143
Opened 2017-02-13 22:55 UTC by Kerby70

Jira https://propeople-us.atlassian.net/browse/OYPD-241
D.o 

Steps to review:
- [ ] Manually install
- [ ] See step "3rd party services"
- [ ] At that step in field "Google Maps API Key" enter a string like https://github.com/ymcatwincities/openy/pull/131/files#diff-88f19bef09097e5fc1c1dcf92336950eR1 make some notable variation to allow verification.
- [ ] Complete install
- [ ] Go to /admin/config/services/geolocation
- [ ] See the key entered is present in that form

2017-02-13 22:59 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build441

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/441/

2017-02-13 23:00 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build441/profiles/openy/build/reports/behat

2017-02-14 09:45 UTC, Sanchiz commented
retest this please

2017-02-14 09:48 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build448

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/448/

2017-02-14 09:50 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build448/profiles/openy/build/reports/behat

2017-02-14 10:05 UTC, Sanchiz commented
1. We should set empty value here https://github.com/ymcatwincities/openy/pull/131/files#diff-88f19bef09097e5fc1c1dcf92336950eR1, because it's key from another project.

2017-02-14 10:21 UTC, alexschedrov requested changes

2017-02-14 10:21 UTC, Sanchiz commented on src/Form/ThirdPartyServicesForm.php
> +      '#description' => $this->t('For help see the <a href="https://developers.google.com/maps/documentation/javascript/get-api-key#key">Google Maps API documentation</a>.'),
Please add `target="blank"` for link in description.

2017-02-14 13:07 UTC, Kerby70 commented
@Sanchiz New changes added, per last comment.

2017-02-14 13:09 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build453

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/453/

2017-02-14 13:11 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build453/profiles/openy/build/reports/behat

2017-02-14 13:28 UTC, Kerby70 commented
@Sanchiz Latest commit removes the google maps api key from configuration.

2017-02-14 13:30 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build454

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/454/

2017-02-14 13:32 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build454/profiles/openy/build/reports/behat

2017-02-14 13:58 UTC, alexschedrov approved these changes

2017-02-14 13:58 UTC, merged