[OPENY-240] Breadcrumbs isn't visible
ymcatwincities/openy pull request #1436
Opened 2019-01-10 12:32 UTC by miroslav-lee

## Issue details:
When add Limited Time Offer paragraph, we are not see block with breadcrumbs
![not visible](https://user-images.githubusercontent.com/24233384/50968532-6e7c7b80-14ec-11e9-9c78-72721eb0445e.png)

## Step for review:
- [ ] Sign up as admin
- [ ] Add new page of Landing page CT
- [ ] Add Limited Time Offer paragraph to Content area
- [ ] Save this page
- [ ] Check that breadcrumbs is visible.
![breadcrumbs](https://user-images.githubusercontent.com/24233384/50968655-c915d780-14ec-11e9-86ab-ecb20ae54423.png)

Thank you for your contribution!

2019-01-10 12:35 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2019-01-10 13:04 UTC, hamrant requested changes

2019-01-10 13:04 UTC, hamrant commented on themes/openy_themes/openy_rose/css/styles.css
> -  margin: -20px 0 40px;
I think we need some positive margin top and bottom in this paragraph.

2019-01-10 13:05 UTC, hamrant commented on themes/openy_themes/openy_rose/css/styles.css
> -  margin: -20px 0 40px;
Let's use `margin: 20px 0;` or `margin: 40px 0;`

2019-01-10 13:26 UTC, miroslav-lee commented on themes/openy_themes/openy_rose/css/styles.css
> -  margin: -20px 0 40px;
@hamrant I fixed it

![margin](https://user-images.githubusercontent.com/24233384/50971197-7809e180-14f4-11e9-82af-5be17b2875d8.png)

2019-01-10 20:41 UTC, ddrozdik approved these changes

2019-01-10 20:42 UTC, ddrozdik commented
retest this please

2019-01-10 21:23 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1256 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1256 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1256 |
| Installation process | http://install.openy.cibox.tools/build1256/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1256/

2019-01-14 16:55 UTC, ddrozdik commented
retest this please

2019-01-14 17:16 UTC, hamrant approved these changes

2019-01-14 17:54 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation - Rose theme | http://openy.cibox.tools/build1270 |
| Fresh OpenY installation - Lily theme | http://lily.openy.cibox.tools/build1270 |
| Upgraded(upgrade path) installation | http://upgrade.openy.cibox.tools/build1270 |
| Installation process | http://install.openy.cibox.tools/build1270/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1270/

2019-01-14 20:12 UTC, podarok approved these changes

2019-01-14 20:12 UTC, merged