[OYPD-122] WYSIWYG embed configuration.
ymcatwincities/openy pull request #154
Opened 2017-02-15 21:54 UTC by Kerby70

Jira https://propeople-us.atlassian.net/browse/OYPD-122
D.o 

Steps for review
- [ ] Add a new blog post /node/add/blog
- [ ] In the content area:
  - [ ] Embed an image (via the media image embed button)
    - [ ] Selecting an image
    - [ ] See "Display as" dropdown has "Full", "Half", and "Link".
    - [ ] Select "Full" of these options and click "Embed"
    - [ ] Repeat for "Half", and "Link" display option.
  - [ ] Embed an video (via the media video embed button)
    - [ ] Selecting/Add a video
    - [ ] See "Display as" dropdown has "Full", "Half", and "Link".
    - [ ] Select "Full" of these options and click "Embed"
    - [ ] Repeat for "Half", and "Link" display option.
  - [ ] Embed an document (via the media document embed button)
    - [ ] Selecting/Add a document
    - [ ] See "Display as" dropdown has "Full", "Half", and "Link".
    - [ ] Select "Full" of these options and click "Embed"
    - [ ] Repeat for "Half", and "Link" display option.
- [ ] Save and publish the blog post
- [ ] See each embedded item displayed

2017-02-15 21:57 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build476

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/476/

2017-02-15 21:59 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build476/profiles/openy/build/reports/behat

2017-02-16 10:29 UTC, Sanchiz commented
retest this please

2017-02-16 10:32 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build480

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/480/

2017-02-16 10:34 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build480/profiles/openy/build/reports/behat

2017-02-16 10:40 UTC, alexschedrov requested changes

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/config/install/image.style.full.yml
> +langcode: en
According to naming convention, image style should have prefix of entity `image.style.media_full.yml` and label "Media full".

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/config/install/image.style.half.yml
> +langcode: en
According to naming convention, image style should have prefix of entity `image.style.media_half.yml` and label "Media half".

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/config/install/image.style.full.yml
> +langcode: en
Image style should live in `openy_media_image`, because it's being used only there.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/config/install/image.style.half.yml
> +langcode: en
Image style should live in `openy_media_image`, because it's being used only there.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.features.yml
> +excluded:
Since image styles should live in `openy_media_image`, this should be removed.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/src/Plugin/Field/FieldFormatter/ImageLinkFormatter.php
> +class ImageLinkFormatter extends ImageFormatterBase implements ContainerFactoryPluginInterface {
This class should live in `openy_media_image`, because it's being used only there.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/src/Plugin/Field/FieldFormatter/VideoLinkFormatter.php
> +class VideoLinkFormatter extends FormatterBase implements ContainerFactoryPluginInterface {
This class should live in `openy_media_video`, because it's being used only there.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/src/Plugin/Field/FieldFormatter/FileLinkFormatter.php
> +class FileLinkFormatter extends FileFormatterBase {
This class should live in `openy_media_document`, because it's being used only there.

2017-02-16 10:40 UTC, Sanchiz commented on modules/openy_features/openy_media/src/Plugin/Field/FieldFormatter/FileIframeFormatter.php
> +class FileIframeFormatter extends FileFormatterBase {
This class should live in `openy_media_document`, because it's being used only there.

2017-02-16 10:45 UTC, Sanchiz commented
1. Instead of file name we should display Media name for all bundles.
![image](https://cloud.githubusercontent.com/assets/1316234/23018041/3f2f8788-f445-11e6-9951-92001491e68d.png)
2. For Video bundle make sure field label is hidden
![image](https://cloud.githubusercontent.com/assets/1316234/23018214/d5f0c5ce-f445-11e6-8dd4-fdbf8986a732.png)

2017-02-16 14:23 UTC, Kerby70 commented
@Sanchiz Thank you for all of the great feedback, those changes have been made in the latest commit.

2017-02-16 14:24 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build483

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/483/

2017-02-16 14:27 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build483/profiles/openy/build/reports/behat

2017-02-16 14:54 UTC, alexschedrov approved these changes
Approved.

2017-02-16 14:55 UTC, merged