[OYPD-259] Alerts implementation.
ymcatwincities/openy pull request #159
Opened 2017-02-17 16:03 UTC by Kerby70

Jira https://propeople-us.atlassian.net/browse/OYPD-259
D.o https://www.drupal.org/node/2853585

Note: Some styles still need to be addressed within the theme.
Steps to review:
- [ ] Go to /node/add
- [ ] Add Alert "Global"
  - [ ] Fill required fields
    - [ ] Select one placement location
  - [ ] Leave Reference empty (for global message)
- [ ] Go to homepage
- [ ] See alert with message with the appropriate background color (Font colors are still being overridden by the theme)
  - [ ] See it is only in the selected location
- [ ] Repeat with the other location to see only in that selected location.
- [ ] Add Alert "Local"
  - [ ] Fill required fields
    - [ ] Select both placement locations
  - [ ] For Reference select OpenY (the homepage)
- [ ] Go to homepage
- [ ] In header & footer see alert with message with the appropriate background color (Font colors are still being overridden by the theme)
- [ ] Go to /blog
- [ ] See the first "Global" Alert but not the "Local" Alert referencing Alert
- [ ] Click the x on the right
- [ ] See alert has disappeared
- [ ] Refresh page
- [ ] See alert is still not visible (a cookie value has been set per alert/position)

2017-02-17 16:05 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/494/

**Build Log**
*last 25 lines*

 ```
[...truncated 252 lines...]
stdout: You are about to create a /var/www/build494/sites/default/settings.php file and CREATE the 'drupal494' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=4    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-17 16:41 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build495

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/495/

2017-02-17 16:43 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build495/profiles/openy/build/reports/behat

2017-02-20 10:35 UTC, Sanchiz commented
retest this please

2017-02-20 10:38 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build502

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/502/

2017-02-20 10:41 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build502/profiles/openy/build/reports/behat

2017-02-20 10:48 UTC, alexschedrov requested changes

2017-02-20 10:48 UTC, Sanchiz commented on modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.field.node.alert.field_alert_belongs.yml
> +    - node.type.session
Can we get rid of these dependencies and put wildcard?

2017-02-20 10:48 UTC, Sanchiz commented on modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.field.node.alert.field_alert_belongs.yml
> +      session: session
Let's set empty to support all bundles, even when they are created.

2017-02-20 10:53 UTC, Sanchiz commented
1. There's typo in documentation for placement link. It should support only 1 value. Please fix and update documentation.
![image](https://cloud.githubusercontent.com/assets/1316234/23122005/3ad3f998-f76b-11e6-9edd-9242437be12d.png)

2. Please clean up alert full page display. Right now it looks a bit cluttered and renders referenced entity.
![image](https://cloud.githubusercontent.com/assets/1316234/23122118/9537f60a-f76b-11e6-8b0f-c552e75efbdf.png)

2017-02-20 19:26 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build527

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/527/

2017-02-20 19:28 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build527/profiles/openy/build/reports/behat

2017-02-20 19:38 UTC, Kerby70 commented
All changes in latest commit.

The cleaned up default display:
![image](https://cloud.githubusercontent.com/assets/5031409/23139334/e864dd3a-f779-11e6-884c-e12c3d2d0cd8.png)

2017-02-21 08:35 UTC, Sanchiz commented
retest this please

2017-02-21 08:38 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build534

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/534/

2017-02-21 08:41 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build534/profiles/openy/build/reports/behat

2017-02-21 08:46 UTC, alexschedrov requested changes

2017-02-21 08:46 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--full.html.twig
> +    <li>Rendered on {{ content.field_alert_belongs }}</li>
Should be translatable.

2017-02-21 08:46 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--full.html.twig
> +    <li>Rendered on all pages</li>
Should be translatable.

2017-02-21 08:46 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--full.html.twig
> +    <li>Displayed in the header.</li>
Should be translatable.

2017-02-21 08:46 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--full.html.twig
> +    <li>Displayed in the footer.</li>
Should be translatable.

2017-02-21 08:50 UTC, Sanchiz commented
# A few alerts in the same region

When there are a few alerts in the region, they should have pager + slider on mobile.

Current OpenY version:
![image](https://cloud.githubusercontent.com/assets/1316234/23157277/2ee00eac-f823-11e6-9913-55e2bdf5a88f.png)


YGS version:
![image](https://cloud.githubusercontent.com/assets/1316234/23157288/379b7eb4-f823-11e6-912f-456722ed0609.png)


The same in footer(on YGS it displays only latest alert, but in distribution should display all with sliders).

2017-02-21 16:30 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/545/

**Build Log**
*last 25 lines*

 ```
[...truncated 238 lines...]
stdout: You are about to create a /var/www/build545/sites/default/settings.php file and CREATE the 'drupal545' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-21 17:03 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build547

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/547/

2017-02-21 17:06 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build547/profiles/openy/build/reports/behat

2017-02-22 13:04 UTC, Sanchiz commented
retest this please

2017-02-22 13:07 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build558

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/558/

2017-02-22 13:10 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build558/profiles/openy/build/reports/behat

2017-02-22 15:30 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build559

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/559/

2017-02-22 15:33 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build559/profiles/openy/build/reports/behat

2017-02-23 09:05 UTC, Sanchiz commented
retest this please

2017-02-23 09:09 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build566

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/566/

2017-02-23 09:12 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build566/profiles/openy/build/reports/behat

2017-02-23 15:43 UTC, alexschedrov approved these changes
Approved, but we have to write code to support upgrade path.

2017-02-23 15:43 UTC, merged