[1605] - Banner extends: ability add to banner video instead of image.
ymcatwincities/openy pull request #1606
Opened 2019-05-29 08:18 UTC by Fant0m771

Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

Added some theming for Open Y Rose, please check in "Open Y Rose" theme for now.
- [ ] Go to banner edit.
- [ ] Check "Add video insted of image".
- [ ] Insert video.
- [ ] Save the node.

2019-05-29 08:20 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2019-06-03 13:13 UTC, podarok requested changes
Needs small love @Fant0m771 

@paige-kiecker this one is a feature/enhancement. Should we tag it into point release or wait for the 2.2?

2019-06-03 13:13 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/field.storage.paragraph.field_prgf_video.yml
> +persist_with_no_fields: false
set everywhere to `true` please

2019-06-03 13:13 UTC, podarok commented on themes/openy_themes/openy_rose/scss/modules/_paragraphs.scss
> +      &.video {
Is it possible to add this style to all OpenY themes?
Would be cool to keep sass and generated css in module and include it globally as it is already done for some other modules https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/scss/modules.scss
And included by every theme automatically for compiling

2019-06-03 13:13 UTC, podarok commented
Retry Deepcode

2019-06-03 14:43 UTC, podarok commented
@Fant0m771 hey
Could you record a short screncast video for the feature? @paige-kiecker wants to know how it works before approving it for the OpenY release
Thank you in advance

2019-10-11 12:10 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2019-11-19 16:07 UTC, podarok commented
closing because of no input on this one
Open if there is a need

2019-12-13 08:01 UTC, podarok commented
Closing as old 
Feel free to pick up in case if the feature is needed

2019-12-13 08:01 UTC, closed without merging