[OYPD-220]
ymcatwincities/openy pull request #162
Opened 2017-02-20 01:29 UTC by david-hernandez

Updates for membership form.

- [ ] Creating landing page.
- [ ] Add membership calculator paragraph.
- [ ] Check the display through the three steps of the form.

![screen shot 2017-02-19 at 8 16 56 pm](https://cloud.githubusercontent.com/assets/1504038/23108932/0d547558-f6e2-11e6-9488-0da80a28c6ca.png)
![screen shot 2017-02-19 at 8 17 43 pm](https://cloud.githubusercontent.com/assets/1504038/23108931/0d541d60-f6e2-11e6-8d3a-d73bd968d4e2.png)
![screen shot 2017-02-19 at 8 17 56 pm](https://cloud.githubusercontent.com/assets/1504038/23108933/0d5555d6-f6e2-11e6-9636-ec1a6b6be03b.png)
![screen shot 2017-02-19 at 8 18 09 pm](https://cloud.githubusercontent.com/assets/1504038/23108930/0d5170a6-f6e2-11e6-92ec-a38175f558aa.png)

2017-02-20 01:31 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/499/

**Build Log**
*last 25 lines*

 ```
[...truncated 248 lines...]
stdout: You are about to create a /var/www/build499/sites/default/settings.php file and CREATE the 'drupal499' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=4    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-20 01:31 UTC, david-hernandez commented
I want to make sure this generally works. One thing that needs to be fixed is making the membership type boxes are equal height. I didn't do that yet because that is not straight forward. I have get access to the fieldset in order to add the bootstrap equal height classes, but a suggestion for that does not exist. A custom one would need to be made.

2017-02-20 12:32 UTC, Sanchiz commented
```
01:30:32 TASK: [Installing drupal] ***************************************************** 
01:31:23 failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush -y si openy --db-url=mysql://root:root@127.0.0.1:/drupal499 --account-name=admin --account-pass=openy --uri=http://openy-dev.ffwua.com/build499", "delta": "0:00:51.614685", "end": "2017-02-20 01:31:23.734824", "rc": 1, "start": "2017-02-20 01:30:32.120139", "warnings": []}
01:31:23 stderr: Starting Drupal installation. This takes a while. Consider using the [ok]
01:31:23 --notify global option.
01:31:23 Drupal\Core\Config\UnmetDependenciesException: Configuration objects [error]
01:31:23 (core.entity_view_display.paragraph.membership_info.preview) provided
01:31:23 by openy_loc_branch have unmet dependencies in
01:31:23 /var/www/build499/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:84
01:31:23 Stack trace:
01:31:23 #0
01:31:23 /var/www/build499/core/lib/Drupal/Core/Config/ConfigInstaller.php(460):
01:31:23 Drupal\Core\Config\UnmetDependenciesException::create('openy_loc_branc...',
01:31:23 Array)
01:31:23 #1
01:31:23 /var/www/build499/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
01:31:23 Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module',
01:31:23 'openy_loc_branc...')
```

2017-02-20 12:47 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/508/

**Build Log**
*last 25 lines*

 ```
[...truncated 248 lines...]
stdout: You are about to create a /var/www/build508/sites/default/settings.php file and CREATE the 'drupal508' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=4    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-20 12:57 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/509/

**Build Log**
*last 25 lines*

 ```
[...truncated 248 lines...]
stdout: You are about to create a /var/www/build509/sites/default/settings.php file and CREATE the 'drupal509' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=12   changed=4    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-20 13:46 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build514

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/514/

2017-02-20 13:48 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build514/profiles/openy/build/reports/behat

2017-02-20 16:19 UTC, alexschedrov requested changes

2017-02-20 16:19 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/custom/openy-calc-form-summary.html.twig
> +      <div>{{ result.membership }}</div>
According to task spec we should render "Calculator summary view mode" here.

2017-02-20 16:19 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/form/form-element-membership-type.html.twig
> +      <h3>{{ data.title }}</h3>
According to task spec we should render "Calculator preview view mode" here for membership type.

2017-02-20 16:19 UTC, Sanchiz commented on modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.features.yml
> +excluded:
Can we get rid of this? I don't see `core.entity_view_display.paragraph.membership_info.preview` in the configs for some reasons.

2017-02-20 16:19 UTC, Sanchiz commented on modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.features.yml
> +  - core.entity_view_display.paragraph.membership_info.default
Can we get rid of this? I don't see `core.entity_view_display.paragraph.membership_info.default` in the configs.

2017-02-20 16:19 UTC, Sanchiz commented on modules/openy_features/openy_prgf/openy_prgf.features.yml
> +  - core.entity_view_mode.paragraph.preview
Can we get rid of this? We should have this preview mode in configs.

2017-02-20 16:23 UTC, Sanchiz commented
1. Please remove prices from this screen
![image](https://cloud.githubusercontent.com/assets/1316234/23133316/5611abe6-f799-11e6-9d52-7ae390d1dd48.png)
2. Please remove description from this screen ![image](https://cloud.githubusercontent.com/assets/1316234/23133387/86518786-f799-11e6-9735-58139f0607ec.png)

3. Center button
![image](https://cloud.githubusercontent.com/assets/1316234/23133404/9ba34642-f799-11e6-844a-4f14b132ec24.png)

2017-02-20 17:13 UTC, david-hernandez commented
In the last commit I didn't center the button. Can that be left until the completion button has an actual link and functions? Right now it is just a single div. I would have to force a width on it to center it or add some messy CSS that will probably get removed later. Once it has an actual link, meaning a div with another tag, it will be easy to center.

2017-02-20 17:14 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build525

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/525/

2017-02-20 17:17 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build525/profiles/openy/build/reports/behat

2017-02-21 08:54 UTC, Sanchiz commented
retest this please

2017-02-21 08:57 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build535

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/535/

2017-02-21 09:00 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build535/profiles/openy/build/reports/behat

2017-02-21 09:09 UTC, alexschedrov approved these changes
Approved. Treated as MVP, but needs some polishing.

2017-02-21 09:10 UTC, merged