[OYPD-228] Custom logo can't be set for footer.
ymcatwincities/openy pull request #165
Opened 2017-02-20 13:22 UTC by Kerby70

Jira https://propeople-us.atlassian.net/browse/OYPD-228
D.o https://www.drupal.org/node/2854173

Steps to review:
- [ ] Go to /demo/admin/appearance/settings/openy_rose
- [ ] Add an image to the Footer Logo field
- [ ] Submit and see message "Footer Logo saved."
- [ ] Go to homepage
- [ ] See new image as footer logo.

2017-02-20 13:25 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>6</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build513/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build513

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/513/

2017-02-20 13:28 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build513/profiles/openy/build/reports/behat

2017-02-20 13:35 UTC, ddrozdik requested changes

2017-02-20 13:35 UTC, ddrozdik commented on themes/openy_themes/openy_rose/openy_rose.theme
> +function openy_rose_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id = NULL) {
Please add comments to this function.

2017-02-20 13:35 UTC, ddrozdik commented on themes/openy_themes/openy_rose/openy_rose.theme
> +function openy_rose_preprocess_page(&$variables) {
Please add comments to this function.

2017-02-20 13:36 UTC, ddrozdik commented
Also please fix sniffer issues

2017-02-20 13:40 UTC, ddrozdik commented
- I suggest to move this field into the fieldset named "Logo image".
- svg is not allowed, I think we should allow upload svg. 

Questions:
- Are we going to have default logo image in the footer?

2017-02-20 13:58 UTC, Sanchiz commented
@ddrozdik yes, we should be able to upload SVG.
Here's an example of settings form on YGTC https://github.com/propeoplemd/ymca/blob/master/docroot/themes/custom/ymca/ymca.theme#L1460

2017-02-20 14:42 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>13</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build516/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build516

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/516/

2017-02-20 14:45 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build516/profiles/openy/build/reports/behat

2017-02-20 15:00 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>12</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build517/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build517

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/517/

2017-02-20 15:03 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build517/profiles/openy/build/reports/behat

2017-02-20 15:16 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build520

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/520/

2017-02-20 15:18 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build520/profiles/openy/build/reports/behat

2017-02-20 15:31 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build521

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/521/

2017-02-20 15:31 UTC, Sanchiz commented
1. Please display default logo from theme when there's no logo specified.

2017-02-20 15:33 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build521/profiles/openy/build/reports/behat

2017-02-20 15:37 UTC, Kerby70 commented
@ddrozdik I have addressed each of the issues. @Sanchiz answered the default logo question above.

Thank you both.

2017-02-20 16:25 UTC, alexschedrov requested changes
Default footer logo should be displayed

2017-02-20 16:59 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build524

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/524/

2017-02-20 17:02 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build524/profiles/openy/build/reports/behat

2017-02-21 08:47 UTC, ddrozdik requested changes

2017-02-21 08:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/openy_rose.theme
> + * @param array $variables
No need to list params in comments for hooks.

2017-02-21 08:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/openy_rose.theme
> + * @param array $variables
No need to list params in comments for hooks.

2017-02-21 08:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/openy_rose.theme
> + * @param array $variables
and same issue below ...

2017-02-21 08:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/page/page.html.twig
> +          <a href="{{ base }}" class="footer__brand brand" title="{{ "YMCA"|t }}" {{ background_image|raw }}></a>
If variable `footer_logo` is undefined then `background_image ` is undefined as well. You need to check this before using variable.

2017-02-21 19:29 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build550

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/550/

2017-02-21 19:32 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build550/profiles/openy/build/reports/behat

2017-02-22 12:40 UTC, ddrozdik approved these changes

2017-02-22 12:41 UTC, ddrozdik commented
retest this please

2017-02-22 12:44 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build555

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/555/

2017-02-22 12:47 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build555/profiles/openy/build/reports/behat

2017-02-22 12:53 UTC, alexschedrov approved these changes

2017-02-22 12:53 UTC, merged