[OYPD-274] Camp section logos.
ymcatwincities/openy pull request #175
Opened 2017-02-22 21:46 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-02-22 21:49 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build560/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build560

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/560/

2017-02-22 21:52 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build560/profiles/openy/build/reports/behat

2017-02-22 21:57 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build561

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/561/

2017-02-22 21:59 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build561/profiles/openy/build/reports/behat

2017-02-23 07:40 UTC, AlexNetman commented
retest this please

2017-02-23 07:44 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build563

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/563/

2017-02-23 07:47 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build563/profiles/openy/build/reports/behat

2017-02-23 10:24 UTC, podarok requested changes
Needs some love

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +class CampHelper {
why not trait?

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +    if ($node->bundle() != 'landing_page') {
this looks pretty weird, if we are talking about universal code.
At like 25 i see check for field exists. Could be safe to remove check for CT and rely on field availability only?

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +      if ($value = $node->field_location->referencedEntities()) {
Add comment here what is going on with this reset

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +        ->condition('type', 'camp')
can we avoid of adding CTs to the conditions? field level could be enough, I guess

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +        $camp = Node::load(reset($entity_ids));
Can we use DI pattern and pass storage to work with? Because this code looks hacky

2017-02-23 10:24 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/src/CampMenuService.php
> +        $camp = CampHelper::getLandingPageCampNode($node);
This should be passed as DI service or added as a trait

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +    '#open' => TRUE,
Could we add descriptions everywhere?

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +    'openy_rose_footer_logo',
This looks like a config. Is it possible to save/get this from config somehow and get rid of hardcoded list of values?
Also it is possible to get list of image fields dynamically. BTW, this looks like a follow-up tasks, not the do it now.

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +      $file = File::load(reset($fid_array));
I hate this. Nothing need to change atm. Just waiting for the Drupal 9 and removal of hooks

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +    $camp = CampHelper::getLandingPageCampNode($node);
Should be a service!!!

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +  if ($camp == NULL) {
This instruction means CampHelper is not perfect

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/openy_rose.theme
> +      if (!empty($value)) {
```php
if (empty($value)) {
  continue;
}

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig
> +      <a href="{{ base }}" title="Home" rel="home">
all texts on template level should be translatable. ```Home``` as well

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig
> +        <img src="{{ camp_section_image }}" alt="Home">
all texts on template level should be translatable.

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig
> +      <a href="/" title="Home" rel="home">
all texts on template level should be translatable.

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig
> +      <a href="/" title="Home" rel="home">
possible issue with drupal installed into folder. Is it possible to pass ```base_path``` here? Or just check on QA level on a build

2017-02-23 10:24 UTC, podarok commented on themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig
> +        <img src="{{ camp_section_image }}" alt="Home">
all texts on template level should be translatable.

2017-02-23 13:29 UTC, Kerby70 commented on modules/openy_features/openy_location/modules/openy_loc_camp/src/CampHelper.php
> +    if ($node->bundle() != 'landing_page') {
The instructions on the ticket specifically cover Camp CT, and Landing page CT.

2017-02-23 16:04 UTC, AlexNetman commented
I was expecting same logo file to be displayed in Header and Footer.
Not sure if we really need separate fields for Header and footer logos.

2017-02-23 20:40 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>5</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build575/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build575

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/575/

2017-02-23 20:43 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build575/profiles/openy/build/reports/behat

2017-02-23 20:46 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build576

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/576/

2017-02-23 20:49 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build576/profiles/openy/build/reports/behat

2017-02-24 15:04 UTC, Sanchiz commented
@AlexNetman because different color schema can be setup for footer and header. Let's image following use case:
Black header
White footer


It means that in header we should have white icon and in footer black.

2017-02-24 15:31 UTC, podarok approved these changes

2017-02-24 15:31 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.module
> +  if (!($node = \Drupal::request()->attributes->get('node')) || !($camp_service = \Drupal::service('openy_loc_camp.camp_service'))) {
No need to do that atm, but as a follow-up - It is better not to use service word in service machine names )

2017-02-24 15:34 UTC, Sanchiz commented
retest this please

2017-02-24 15:37 UTC, Kerby70 commented on modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.module
> +  if (!($node = \Drupal::request()->attributes->get('node')) || !($camp_service = \Drupal::service('openy_loc_camp.camp_service'))) {
Got it, don't need to be redundant.

2017-02-24 15:37 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build583

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/583/

2017-02-24 15:40 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build583/profiles/openy/build/reports/behat

2017-02-24 15:44 UTC, Sanchiz commented
1. Should go to homepage
![image](https://cloud.githubusercontent.com/assets/1316234/23309815/d6e11f82-fab8-11e6-8599-609405209c53.png)

2. Should go to homepage
![image](https://cloud.githubusercontent.com/assets/1316234/23309824/df83ec78-fab8-11e6-885f-7f116bf733f2.png)

2017-02-24 16:14 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build584

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/584/

2017-02-24 16:17 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build584/profiles/openy/build/reports/behat

2017-02-24 16:20 UTC, AlexNetman commented
Link is fixed - rechecked there
http://openy-dev.ffwua.com/build584/camps/camp-colman

2017-02-24 16:22 UTC, merged