[OYPD-279] Updating membership calculator styling
ymcatwincities/openy pull request #176
Opened 2017-02-22 23:31 UTC by david-hernandez

- [ ] Add the membership calculator paragraph to a page.
- [ ] View the page and go through each step of the form.
- [ ] Verify styling changes.

I did the following:
- remove 13 from the header
- changed the header links from a tags to divs.
- made membership types equal height
- added a highlight to the button when membership is selected (I experimented with highlighting different parts of the membership box and the whole box, but none looked good. The problem is the image and text are already full width without and padding. If I add padding it will disrupt the existing look.)
- made the map and image on the summary the same size and the columns equal height just in case
- made the size of the membership type name on the summary the same size as on the first step
- made the next and complete registration buttons purple so they are more prominent, and to be UX consistent with colors uses to show progression. (purple for everything active or selected)

The only thing I didn't do was adjust the header chevron on phone size. I wanted to get these changed looked at first. For the header I may have to do something different other than just keep shrinking. The header was not designed well to allow each piece to move from the others, like stacking.

![screen shot 2017-02-22 at 6 12 04 pm](https://cloud.githubusercontent.com/assets/1504038/23237644/489dd8e2-f92c-11e6-8d1d-80b6e93aabe3.png)

![screen shot 2017-02-22 at 6 12 21 pm](https://cloud.githubusercontent.com/assets/1504038/23237651/4d06df1e-f92c-11e6-881d-54c7abea471c.png)

![screen shot 2017-02-22 at 6 12 40 pm](https://cloud.githubusercontent.com/assets/1504038/23237656/52b2b0dc-f92c-11e6-8517-1505db7050b4.png)

2017-02-22 23:34 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build562

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/562/

2017-02-22 23:37 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build562/profiles/openy/build/reports/behat

2017-02-23 07:41 UTC, AlexNetman commented
retest this please

2017-02-23 07:47 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build564

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/564/

2017-02-23 07:50 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build564/profiles/openy/build/reports/behat

2017-02-23 08:54 UTC, alexschedrov requested changes

2017-02-23 08:54 UTC, Sanchiz commented on themes/openy_themes/openy_rose/openy_rose.theme
> -  }
Why this has been removed?

2017-02-23 08:56 UTC, Sanchiz commented
1. Let's output Branch name in the leftside area
![image](https://cloud.githubusercontent.com/assets/1316234/23251579/90674c1e-f9b6-11e6-9295-8ea7ad162f90.png)

2017-02-23 13:22 UTC, david-hernandez commented on themes/openy_themes/openy_rose/openy_rose.theme
> -  }
Sorry, that was a mistake. Added back.

2017-02-23 13:25 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build572

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/572/

2017-02-23 13:28 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build572/profiles/openy/build/reports/behat

2017-02-23 13:39 UTC, david-hernandez commented
The last commit adds the title to the location summary.

![screen shot 2017-02-23 at 8 38 25 am](https://cloud.githubusercontent.com/assets/1504038/23261289/a0bcc566-f9a3-11e6-97b9-89d304c6813a.png)

2017-02-23 13:42 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build573

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/573/

2017-02-23 13:45 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build573/profiles/openy/build/reports/behat

2017-02-23 16:57 UTC, david-hernandez commented
Updated the mobile chevron style to stack on mobile.

![screen shot 2017-02-23 at 11 54 43 am](https://cloud.githubusercontent.com/assets/1504038/23269616/2e8e211c-f9bf-11e6-955d-0a9778b414de.png)

2017-02-23 16:59 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build574

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/574/

2017-02-23 17:03 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build574/profiles/openy/build/reports/behat

2017-02-23 17:11 UTC, alexschedrov approved these changes
Approved.

2017-02-23 17:11 UTC, merged