[OYPD-281] Demo camps and their landing pages
ymcatwincities/openy pull request #177
Opened 2017-02-23 08:06 UTC by hamrant

Jira - https://propeople-us.atlassian.net/browse/OYPD-281
drupal.org issue https://www.drupal.org/node/2855182

Steps for review:
- [ ]  login as admin
- [ ]  go to /admin/content?status=All&type=camp&title=&langcode=All
- [ ]  check created camps
- [ ]  go to /admin/content?status=All&type=landing_page&title=&langcode=All
- [ ]  check langing pages for camps
- [ ]  profit

2017-02-23 08:10 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build565

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/565/

2017-02-23 08:12 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build565/profiles/openy/build/reports/behat

2017-02-23 08:47 UTC, Sanchiz commented
![image](https://cloud.githubusercontent.com/assets/1316234/23251297/76028c86-f9b5-11e6-99d5-936dfe4c56d5.png)

2017-02-23 09:04 UTC, alexschedrov requested changes
Fixed above.

2017-02-23 11:40 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build569

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/569/

2017-02-23 11:43 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build569/profiles/openy/build/reports/behat

2017-02-23 13:13 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build571

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/571/

2017-02-23 13:16 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build571/profiles/openy/build/reports/behat

2017-02-23 15:50 UTC, alexschedrov requested changes

2017-02-23 15:50 UTC, Sanchiz commented on modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing.yml
> +      alias: '/lp-camp-page-1'
Let's set better alias and for all pages below.
/[camp-alias]/about

2017-02-23 15:50 UTC, Sanchiz commented on modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.lp_paragraph_simple.yml
> +        <h4>Do you love Camp Colman? Or maybe you have never been here before
Let's add more text here and below. You can take some examples from Seattle.

2017-02-23 15:51 UTC, Sanchiz commented
1. We should support upgrade path.
In profile enable this module and run migration in case if migration hasn't be triggered during installation

2017-02-24 08:30 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build577

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/577/

2017-02-24 08:32 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build577/profiles/openy/build/reports/behat

2017-02-24 10:27 UTC, alexschedrov requested changes

2017-02-24 10:27 UTC, Sanchiz commented on openy.install
> +  \Drupal::service('module_installer')->install([
We should do that only in case if `openy_migrate` has been enabled.

2017-02-24 10:27 UTC, Sanchiz commented on openy.install
> +  $importer = \Drupal::service('openy_migrate.importer');
We should do that only in case if `openy_migrate` has been enabled.

2017-02-24 11:22 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build578

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/578/

2017-02-24 11:25 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build578/profiles/openy/build/reports/behat

2017-02-24 12:02 UTC, alexschedrov approved these changes
Approved.

2017-02-24 12:02 UTC, merged