[RGTC-590] Backport Activity Finder
ymcatwincities/openy pull request #1802
Opened 2019-11-15 13:54 UTC by svicervlad

## Steps for review

- [ ] Login as admin
- [ ] Create a landing page with paragraph Activity Finder Search
- [ ] You should see, what  Activity Finder works fine with new features
![Selection_093](https://user-images.githubusercontent.com/26228931/68948236-1d01e480-07c0-11ea-97b0-d50665108562.png)

2019-11-15 13:56 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2019-11-15 13:56 UTC, podarok commented
ok to test

2019-11-15 14:05 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1919/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1919/

2019-11-15 14:05 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1919/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1919/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1919/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1919/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1919/blogWCAG2AAhtmlcs.txt

2019-11-15 15:10 UTC, podarok commented
retest this please

2019-11-15 15:15 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1920/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1920/

2019-11-15 15:16 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1920/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1920/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1920/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1920/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1920/blogWCAG2AAhtmlcs.txt

2019-11-18 13:18 UTC, podarok commented
retest this please

2019-11-18 13:19 UTC, podarok commented
@svicervlad  - could you please gather a list of fixes and enhancements, collected in this PR?
We should have it for Open Y release notes. Thank you.

2019-11-18 13:24 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1921/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1921/

2019-11-18 13:25 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1921/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1921/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1921/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1921/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1921/blogWCAG2AAhtmlcs.txt

2019-11-19 08:35 UTC, jediandrey commented on modules/custom/openy_activity_finder/css/activity_finder.css
> +  .landing-content {
Possible regressions, it's very common css rule, use something specific or find workaround

2020-02-03 14:22 UTC, podarok requested changes
Needs fix

2020-02-03 14:23 UTC, podarok commented
@svicervlad @danylevskyi could you also extend a bit
`You should see, what Activity Finder works fine with new features`
?
This is not clear what are new features

2020-06-04 15:29 UTC, bjwilkins commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-06-05 12:38 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-12-22 10:56 UTC, podarok commented
This is done in a different scope
Now Activity Finder is in a decoupled repository https://github.com/ymcatwincities/openy_activity_finder

2020-12-22 10:56 UTC, closed without merging