Egym iwatch
ymcatwincities/openy pull request #1836
Opened 2019-12-06 15:55 UTC by retif

2019-12-06 15:56 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2019-12-09 11:23 UTC, podarok commented
ok to test

2019-12-09 11:24 UTC, podarok commented
@paige-kiecker Looks like I missed something
Should we have this in OpenY?

2019-12-09 11:28 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1943/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1943/

2019-12-09 11:28 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1943/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1943/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1943/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1943/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1943/blogWCAG2AAhtmlcs.txt

2019-12-09 11:32 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1943/

2019-12-09 11:59 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build1943/

2019-12-09 13:25 UTC, podarok commented
@retif and @anpolimus 
IS there any way for you to improve steps for review
It is not obvious how to test this code
We used to have a best practice for step by step review.
Appreciate attention to details from your end

2019-12-09 15:29 UTC, anpolimus commented
Hi, @podarok .
Steps for review are next.
1. Go to extensions and enable this module.
2. Once module would be enabled You will see status message with a link to just generated landing page.
3. Click to this link and check that landing page exist and equal to wireframes.

2019-12-09 16:17 UTC, podarok requested changes
Small fixes to get this merged, please

2019-12-09 16:17 UTC, podarok commented on modules/openy_features/openy_egym_iwatch/dist/main.js
> +//# sourceMappingURL=css/openy_egym_iwatch.css.map
could you compile without sourcemap, please?

2019-12-09 16:17 UTC, podarok commented on modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.libraries.yml
> +      dist/css/openy_egym_iwatch.css: {}
add `minified: true` please

2019-12-09 16:17 UTC, podarok commented on modules/openy_features/openy_egym_iwatch/webpack.common.js
> +        sourceMap: true,
let's have `false` for prod

2019-12-09 16:28 UTC, anpolimus commented
@podarok here is little demo: https://www.loom.com/share/b79b602af8bc482aa01daef5e2cf1921

2019-12-09 16:31 UTC, anpolimus commented on modules/openy_features/openy_egym_iwatch/webpack.common.js
> +        sourceMap: true,
done

2019-12-09 16:31 UTC, anpolimus commented on modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.libraries.yml
> +      dist/css/openy_egym_iwatch.css: {}
done

2019-12-09 16:32 UTC, anpolimus commented on modules/openy_features/openy_egym_iwatch/dist/main.js
> +//# sourceMappingURL=css/openy_egym_iwatch.css.map
Let us recompile css in prod mode

2019-12-09 16:55 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1946/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1946/

2019-12-09 16:55 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1946/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1946/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1946/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1946/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1946/blogWCAG2AAhtmlcs.txt

2019-12-09 16:59 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1946/

2019-12-09 17:21 UTC, anpolimus commented
@podarok we made all requested fixes

2019-12-09 17:28 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build1946/

2019-12-09 17:29 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1947/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1947/

2019-12-09 17:29 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1947/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1947/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1947/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1947/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1947/blogWCAG2AAhtmlcs.txt

2019-12-09 17:33 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1947/

2019-12-09 18:00 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build1947/

2019-12-16 10:41 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1966/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1966/

2019-12-16 10:42 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1966/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1966/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1966/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1966/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1966/blogWCAG2AAhtmlcs.txt

2019-12-16 10:44 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1966/

2019-12-17 11:02 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1969/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1969/

2019-12-17 11:03 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1969/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1969/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1969/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1969/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1969/blogWCAG2AAhtmlcs.txt

2019-12-17 11:06 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1969/

2019-12-17 11:34 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build1969/

2020-01-09 15:20 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build1990/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/1990/

2020-01-09 15:20 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build1990/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build1990/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build1990/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build1990/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build1990/blogWCAG2AAhtmlcs.txt

2020-01-09 15:23 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build1990/

2020-01-09 15:50 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build1990/

2020-02-07 13:57 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2052/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2052/

2020-02-07 14:03 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2053/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2053/

2020-02-07 14:06 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2054/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2054/

2020-02-07 14:12 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2053/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2053/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2053/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2053/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2053/blogWCAG2AAhtmlcs.txt

2020-02-07 14:12 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2054/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2054/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2054/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2054/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2054/blogWCAG2AAhtmlcs.txt

2020-02-07 14:24 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2052/

2020-02-07 14:33 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2053/

2020-02-07 14:34 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2054/

2020-02-07 14:53 UTC, podarok commented
![image](https://user-images.githubusercontent.com/563412/74039258-320aa000-49ca-11ea-9a40-7b142a23bd4e.png)
![image](https://user-images.githubusercontent.com/563412/74039322-4b135100-49ca-11ea-9fd9-812c729a8db0.png)

2020-02-07 14:54 UTC, merged