Update styling for alerts
ymcatwincities/openy pull request #185
Opened 2017-02-27 22:44 UTC by david-hernandez

- [ ] Create several nodes of alert content type.
- [ ] Set different colors for alerts and place them in both header and footer.
- [ ] Check that alert styling is correct and slider works with multiple alerts.

![screen shot 2017-02-27 at 5 40 28 pm](https://cloud.githubusercontent.com/assets/1504038/23383407/49ac0b3c-fd14-11e6-8918-b8e5609889db.png)
![screen shot 2017-02-27 at 5 40 24 pm](https://cloud.githubusercontent.com/assets/1504038/23383409/49b09350-fd14-11e6-841e-2f5850565bf3.png)
![screen shot 2017-02-27 at 5 40 19 pm](https://cloud.githubusercontent.com/assets/1504038/23383410/49b3b5da-fd14-11e6-97dc-a769769b400e.png)
![screen shot 2017-02-27 at 5 40 01 pm](https://cloud.githubusercontent.com/assets/1504038/23383408/49b07906-fd14-11e6-9805-07d0b30ac236.png)

There is an issue with the CTA link color. It can't be easily overridden to use the selected text color. It is a link inside a field and the default theme a tag color will override.

2017-02-27 22:49 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build606 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build606 |
| Installation process | http://install.openy-dev.ffwua.com/build606/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/606/

2017-02-27 22:52 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build606/profiles/openy/build/reports/behat

2017-02-28 08:53 UTC, Sanchiz commented
retest this please

2017-02-28 08:57 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build608 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build608 |
| Installation process | http://install.openy-dev.ffwua.com/build608/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/608/

2017-02-28 09:00 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build608/profiles/openy/build/reports/behat

2017-02-28 10:05 UTC, Sanchiz commented
retest this please

2017-02-28 10:09 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build609 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build609 |
| Installation process | http://install.openy-dev.ffwua.com/build609/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/609/

2017-02-28 10:12 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build609/profiles/openy/build/reports/behat

2017-02-28 10:18 UTC, Sanchiz commented
Text and button link should have same color to keep consisntency.
![image](https://cloud.githubusercontent.com/assets/1316234/23401347/07b28868-fdb0-11e6-9685-823b5d4af4cc.png)

2017-02-28 17:16 UTC, david-hernandez commented
Had to basically hard code this. I don't think it is possible to pass the color variables from the node to the filed template, so I printed it directly. Other solutions seemed equally messy or more.

Made the border the same color. I left the hover as something generic because otherwise there would have to be even more code to try to account for it, and make things messier.

![screen shot 2017-02-28 at 12 12 45 pm](https://cloud.githubusercontent.com/assets/1504038/23416118/8c02838a-fdaf-11e6-8b91-5fb9bedd2038.png)


![screen shot 2017-02-28 at 12 12 54 pm](https://cloud.githubusercontent.com/assets/1504038/23416130/8f89020e-fdaf-11e6-958f-09f1ea63b29d.png)

2017-02-28 17:18 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build616 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build616 |
| Installation process | http://install.openy-dev.ffwua.com/build616/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/616/

2017-02-28 17:21 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build616/profiles/openy/build/reports/behat

2017-03-01 09:02 UTC, alexschedrov requested changes

2017-03-01 09:02 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--node-alert-footer.html.twig
> +          <a href="{{ content.field_alert_link.0['#url'] }}" style="color: {{ text_color }}; border-color: {{ text_color}}">{{ content.field_alert_link.0['#title'] }}</a>
Can we set those variable at the top of template? If we even see `content.field_alert_link.0['#url']` or something like this, this should be declared as a variable at the beginning of template.

2017-03-01 09:03 UTC, alexschedrov requested changes

2017-03-01 09:03 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--node-alert-header.html.twig
> +          <a href="{{ content.field_alert_link.0['#url'] }}" style="color: {{ text_color }}; border-color: {{ text_color}}">{{ content.field_alert_link.0['#title'] }}</a>
Title and URL should be defined as variables in `set` directive.

2017-03-01 09:03 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/node/node--alert--node-alert-footer.html.twig
> +          <a href="{{ content.field_alert_link.0['#url'] }}" style="color: {{ text_color }}; border-color: {{ text_color}}">{{ content.field_alert_link.0['#title'] }}</a>
Title and URL should be defined as variables in `set` directive.

2017-03-01 13:41 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build629 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build629 |
| Installation process | http://install.openy-dev.ffwua.com/build629/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/629/

2017-03-01 13:44 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build629/profiles/openy/build/reports/behat

2017-03-01 15:30 UTC, alexschedrov approved these changes
Approved.

2017-03-01 15:30 UTC, merged