[OYPD-308] Upgrade path tools
ymcatwincities/openy pull request #188
Opened 2017-02-28 13:36 UTC by hamrant

Jira - https://propeople-us.atlassian.net/browse/OYPD-308
Drupal.org issue - https://www.drupal.org/node/2856609

Also please review this patch - https://www.drupal.org/node/2856366

**Steps for review:**
- [ ] login as admin
- [ ] go to /admin/structure/views/view/images_library
- [ ] add any filter or sort creteria (this help with detect that was updated only part of config)
- [ ] set Pager to full (this config we will restore)
- [ ] go to /devel/php (install this module if not exist)
- [ ] execute this code:
```
$config = drupal_get_path('module', 'openy_media_image') . '/config/install/views.view.images_library.yml';
$config_importer = \Drupal::service('config_import.param_updater');
$config_importer->update($config, 'views.view.images_library', 'display.default.display_options.pager');
```
- [ ] return to /admin/structure/views/view/images_library
- [ ] check that filter or sort creteria is the same and pager was restored to "mini"
- [ ] profit

2017-02-28 13:40 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/611/

**Build Log**
*last 25 lines*

 ```
[...truncated 608 lines...]
Error: Class &#039;Drupal\config_import\Drush\Command&#039; not found in config_import_drush_command() (line 24 of /var/www/build611/profiles/openy/modules/contrib/confi/config_import.drush.inc).

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=20   changed=12   unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-28 13:45 UTC, hamrant commented
test this please

2017-02-28 13:48 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/612/

**Build Log**
*last 25 lines*

 ```
[...truncated 609 lines...]
Error: Class &#039;Drupal\config_import\Drush\Command&#039; not found in config_import_drush_command() (line 24 of /var/www/build612/profiles/openy/modules/contrib/confi/config_import.drush.inc).

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=20   changed=12   unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-28 14:29 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/613/

**Build Log**
*last 25 lines*

 ```
[...truncated 609 lines...]
Error: Class &#039;Drupal\config_import\Drush\Command&#039; not found in config_import_drush_command() (line 24 of /var/www/build613/profiles/openy/modules/contrib/confi/config_import.drush.inc).

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=20   changed=12   unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-02-28 16:12 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/615/

**Build Log**
*last 25 lines*

 ```
[...truncated 609 lines...]
Error: Class &#039;Drupal\config_import\Drush\Command&#039; not found in config_import_drush_command() (line 24 of /var/www/build615/profiles/openy/modules/contrib/confi/config_import.drush.inc).

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=20   changed=12   unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-01 09:53 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build627 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build627 |
| Installation process | http://install.openy-dev.ffwua.com/build627/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/627/

2017-03-01 09:55 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build627/profiles/openy/build/reports/behat

2017-03-01 10:02 UTC, podarok requested changes
Needs some love

2017-03-01 10:02 UTC, podarok commented on composer.json
> +                "11963348 - Drush attempts to call hooks for disabled confi module": "https://www.drupal.org/files/issues/confi-drush-call-hooks-from-disabled-2856910.patch"
No need to add a patch. There is a release already, use it, please

2017-03-01 10:02 UTC, podarok commented on composer.json
> +        "drupal/confi": "1.x-dev",
use stable tags only, please

2017-03-01 10:02 UTC, podarok commented on drupal-org.make
> +projects[confi][patch][] = "https://www.drupal.org/files/issues/confi-drush-call-hooks-from-disabled-2856910.patch"
we have a full control over confi module, no need to maintain patches

2017-03-01 10:02 UTC, podarok commented on openy.install
> +    return;
Early return pattern makes sense only if amount of code more than 1 line )))
```php
if (!\Drupal::service('module_handler')->moduleExists('config_import')) {
  // Enable module.
  \Drupal::service('module_installer')->install(['config_import']);
}
```
But in this case I believe no need to check for module installed at all
Drupal has that check, so just enable it and let the core makes its job

2017-03-01 10:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build628 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build628 |
| Installation process | http://install.openy-dev.ffwua.com/build628/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/628/

2017-03-01 10:18 UTC, podarok approved these changes
Code looks good

2017-03-01 10:20 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build628/profiles/openy/build/reports/behat

2017-03-01 14:23 UTC, Sanchiz commented on composer.json
> +                "11963348 - Drush attempts to call hooks for disabled confi module": "https://www.drupal.org/files/issues/confi-drush-call-hooks-from-disabled-2856910.patch"
This is a patch for Drush issue.

2017-03-01 14:27 UTC, merged