Myy
ymcatwincities/openy pull request #1887
Opened 2020-01-30 12:39 UTC by anpolimus

Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2020-01-30 12:41 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-01-31 17:16 UTC, podarok requested changes
needs fix

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/myy_personify.info.yml
> + - personify
TODO: remove dependencies once we have other connectors.

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserData.php
> +class PersonifyUserData {
PLease, add an interface with methods for future implementations

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +      //return '2015228900';
remove debug, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +   * @return int|mixed
Add description, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +      return 0;
can we have FALSE instead of 0?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +   * Helper function that get's
Add description, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +      '32' => 'Andover',
TODO: add to config ( can be done after release )

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYAuthenticator/PersonifyAuthenticator.php
> +    $this->logger = $loggerChannelFactory->get('personify_authenticator');
TODO post release: move to services

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYAuthenticator/PersonifyAuthenticator.php
> +    exit();
looks weird. Is this correct?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYAuthenticator/PersonifyAuthenticator.php
> +    exit();
looks weird, is this correct?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYAuthenticator/PersonifyAuthenticator.php
> +    return new TrustedRedirectResponse('/');
can we use `<front>` ?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYDataChildcare/PersonifyDataChildcare.php
> +    //$start_date_string = '2019-12-01';
remove debug, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/PersonifyUserHelper.php
> +class PersonifyUserHelper {
Could you add an Interface?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYDataOrders/PersonifyDataOrders.php
> +    $request = \Drupal::service('request_stack')->getCurrentRequest();
move to DI, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYDataProfile/PersonifyDataProfile.php
> +    // TODO: Implement getProfileAvatar() method.
could you collect all TODO items to TODO.md file within a module?
Can be done after release, non blocking

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/myy_personify/src/Plugin/MyYDataProfile/PersonifyDataProfile.php
> +    $personifyID = '2052259627';
could you remove debug?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/config.rb
> +css_dir = "css"
TODO migrate to yarn/npm for consistency across the distribution, post release

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/js/personify.childcare.js
> +        minDate: '-2Y',
set as var to reuse below, please
non blocking

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/js/personify.childcare.js
> +        minDate: '-2Y',
use var

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/ChildcarePaymentHistoryRequest.php
> +class ChildcarePaymentHistoryRequest {
should this also have an interface for future CRMs?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Controller/PersonifyController.php
> +    \Drupal::service('ymca_personify_pdf_generator')->generatePDF($settings);
move to DI, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Controller/PersonifyController.php
> +    $data = \Drupal::service('ymca_personify_childcare_request')->personifyRequest($parameters);
move to DI, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Form/ChildcarePaymentHistoryForm.php
> +      'start_date' => '2014-01-01',
class const, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Form/ChildcarePaymentHistoryForm.php
> +    $data = \Drupal::service('ymca_personify_childcare_request')->personifyRequest($parameters);
DI?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Form/ChildcarePaymentHistoryForm.php
> +   * Build results.
a bit more description, please )))

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/Form/ChildcarePaymentHistoryForm.php
> +    $data = \Drupal::service('ymca_personify_childcare_request')->personifyRequest($parameters);
DI, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/PersonifyApi.php
> +class PersonifyApi implements PersonifyApiInterface {
should this be CRMApiInterface?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/src/PersonifyApiInterface.php
> +interface PersonifyApiInterface {
CRMApiInterface?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/templates/ymca-childcare-payment-history--pdf--body.html.twig
> +      <p>{{ 'YMCA of the Greater Twin Cities'|t }}</p>
ensure we have no YGTC related names everywhere. Keep this as config in Admin UI. Blocker for release!!!

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/templates/ymca-childcare-payment-history--pdf--footer.html.twig
> +  {{ 'Have questions about this statement? http://www.ymcamn.org/contact_us or call 612-230-9622.'|t }}
ensure we have no YGTC related names. Keep this as a config in Admin UI. Blocker for release!!!

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/modules/ymca_personify/templates/ymca-childcare-payment-history--pdf--footer.html.twig
> +  {{ 'Have questions about this statement? http://www.ymcamn.org/contact_us or call 612-230-9622.'|t }}
same for phones!!!!

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Childcare.vue
> +                <!--<a href="#" class="cancel"><strong>Cancel all</strong></a>-->
remove debug, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Childcare.vue
> +            baseUrl: 'http://openy-demo.docksal/'
definitely should be more generic and not absolute

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/ChildcareVisits.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative urls, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Filters.vue
> +        //component.updateQuery();
remove debug, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Filters.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative url, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Filters.vue
> +      component.uid = typeof window.drupalSettings.myy !== 'undefined' ? window.drupalSettings.myy.uid : '';
is UID secure? Can we use session here?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/GuestPasses.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative url. please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Membership.vue
> +            <!--<a href="#" class="details"><strong>Details</strong></a>-->
remove debug code, please. Or make it as a TODO if needed in the future

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Membership.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative url, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/MobileMenu.vue
> +          <nuxt-link to="/myy/calendar">calendar</nuxt-link>
remove debug or create TODO if needed, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/MyyHeader.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative url, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/MyyHeader.vue
> +      console.log(this.$store.state);
remove console.log everywhere or use devtools debug feed for not impacting prod, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/MyyHeader.vue
> +        Vue.cookie.delete('Drupal.visitor.personify_authorized');
could you ensure we are setting cookies for specific url paths, not globally?
this cookie will break reverse proxy caching if set globally across all site pages.

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +          <div class="row">
todo or remove, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +              <!--<i>Automatic Payments: Visa 1234</i>-->
remove?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +    <!-- Uncomment once we need pager -->
mark as TODO, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +            <div class="page-of">Page 1 of 5</div>
definitely debug...

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +        var start = typeof this.$route.query.start == 'undefined' ? '2018-01-01' : this.$route.query.start,
const? date should be dynamic

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +            end = typeof this.$route.query.end == 'undefined' ? '2021-01-01' : this.$route.query.end,
what will happen post 2021? should we remove const?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/OrdersReceiptsResults.vue
> +      //component.$parent.$on('runAjaxRequest', component.runAjaxRequest);
remove debug, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/PendingPayments.vue
> +            <span class="price">$129.00/mo</span>
cosnt looks like wrong. let's fix. Should be dynamic

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/PendingPayments.vue
> +            <i>Automatic Payments: Visa 1234</i>
is language correct?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/PendingPayments.vue
> +            <p class="red"><strong>Payment due: 12/1/18</strong></p>
looks like wrong

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/SidebarMenu.vue
> +        <nuxt-link to="/myy/calendar">calendar</nuxt-link>
TODO or remove, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/Visits.vue
> +            baseUrl: 'http://openy-demo.docksal/',
use relative urls, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/VisitsResults.vue
> +            start = typeof this.$route.query.start == 'undefined' ? '2018-01-01' : this.$route.query.start,
const? should be dynamic

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/components/VisitsResults.vue
> +            end = typeof this.$route.query.end == 'undefined' ? '2019-12-12' : this.$route.query.end,
const? should be dynamic

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/dist/200.html
> +  <script type="text/javascript" src="/_nuxt/runtime.js"></script><script type="text/javascript" src="/_nuxt/2.vendors.app.js"></script><script type="text/javascript" src="/_nuxt/0.app.js"></script><
I bet we can remove everything but JS from dist folder for security reasons in production script. Let's keep main repo clean

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/layouts/default.vue
> +  font-family: "Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
should we have these files in repo?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/nuxt-dist/components/nuxt-build-indicator.vue
> +<template>
is this needed in repo?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/nuxt-dist/loading.html
> +#nuxt-loading {
looks like whole nust-dist is not needed. If yes - let's remove it from repo to keep it clean

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/package.json
> +  "private": true,
is it private?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/pages/myy/dashboard.vue
> +      // @todo Only for dev purposes, remove before launch.
let's remove then )

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/openy_myy_app/pages/myy/index.vue
> +    //if (store.state.isLoggedIn) {
let's remove debug code, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Controller/MyYAuthenticatorController.php
> +        '#markup' => 'error'
can we extend markup a bit to be human-friendly?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Form/SettingsForm.php
> +    $config = \Drupal::service('config.factory')->getEditable('openy_myy.settings');
DI?

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYChildcareScheduled.php
> +    return new ResourceResponse($response);
this is cached. Are we sure we need a cache here?
If not - search for MOdifiedResourceResponse, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYChildcareScheduled.php
> +    return new ResourceResponse($response);
Or add user tag to response

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYChildcareSessionCancel.php
> +    return new ResourceResponse($response);
same here. Let's ensure we are not caching somebody else's response

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYChildcareSessionsAdd.php
> +    return new ResourceResponse($response);
same here

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYProfileDataOrders.php
> +    return new ResourceResponse($response);
same here

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYProfileFamilyList.php
> +    $result->addCacheableDependency($response);
yep, like here

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYProfileMembershipInfo.php
> +    return new ResourceResponse($response);
seems like we need this everywhere

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYProfileVisitsStat.php
> +    return new ResourceResponse($response);
same here, let's add user tag

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYVisitsDetails.php
> +    return new ResourceResponse($response);
same here

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_myy/src/Plugin/rest/resource/MyYVisitsOverview.php
> +    return new ResourceResponse($response);
same here, please

2020-01-31 17:16 UTC, podarok commented on modules/custom/openy_repeat/src/RepeatManager.php
> +          $date_from = new \DateTime($date['from'], new \DateTimeZone($user_time_zone));
this is not secure... @danylevskyi can we ask Vlad to check this particular change does nothing wrong to Activity FInder and New Schedules

2020-01-31 17:16 UTC, podarok commented on modules/custom/personify/src/Form/PersonifySettingsForm.php
> +    $config = \Drupal::service('config.factory')->getEditable('personify.settings');
DI?

2020-01-31 17:16 UTC, podarok commented on modules/custom/personify/src/PersonifyClient.php
> +      <DateTo>2020-01-01</DateTo>
hardcoded values? Let's remove, please

2020-01-31 17:17 UTC, closed without merging