[OYS-84]: Open Y Google Search search results page must be always cre…
ymcatwincities/openy pull request #1923
Opened 2020-02-20 14:02 UTC by AleksandrPrykhodkoDev

Steps for review

- [ ] check code changes
- [ ] check alias exists or not (/search)
- [ ] If exists: disable pathauto when creating a landing page, Drupal will create alias automatically 
- [ ] if doesn’t exist: current logic - disable pathauto and use /search alias for the landing

2020-02-20 14:02 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-02-20 20:09 UTC, dchubar-fj requested changes

2020-02-20 20:09 UTC, dchubar-fj commented on modules/custom/openy_search/openy_google_search/openy_google_search.install
> +  $alias_exists = \Drupal::service('path.alias_storage')->aliasExists($alias, 'en');
Please don't use hardcoded language see your PR https://github.com/ymcatwincities/openy/pull/1921

2020-02-20 20:23 UTC, AleksandrPrykhodkoDev commented on modules/custom/openy_search/openy_google_search/openy_google_search.install
> +  $alias_exists = \Drupal::service('path.alias_storage')->aliasExists($alias, 'en');
Fixed

2020-02-21 15:13 UTC, dchubar-fj submitted a review, later dismissed

2020-02-24 11:28 UTC, podarok commented
@AleksandrPrykhodkoDev please fix conflict and verify with @AndreyMaximov why PR DO NOT MERGE still exists.
Thank you

2020-02-24 11:29 UTC, podarok submitted a review, later dismissed
I see this is a fixed. @AndreyMaximov your approval needed to unblock PR's labels in GitHub

2020-02-25 13:09 UTC, AndreyMaximov commented
ok to test

2020-02-25 13:16 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2074/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2074/

2020-02-25 13:27 UTC, AndreyMaximov commented
@podarok the PR still needs work, the label is correct

2020-02-25 13:43 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2074/

2020-02-26 15:46 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2077/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2077/

2020-02-26 16:14 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2077/

2020-02-26 20:26 UTC, dchubar-fj requested changes

2020-02-26 20:26 UTC, dchubar-fj commented on modules/custom/openy_search/src/Config/OpenySearchOverrides.php
> -          'search_page_alias' => 'search',
We should not completely remove the overriding of `search_page_alias` config. We should replace hardcoded `search` alias with correct alias from the search results landing node.

2020-02-27 10:13 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2079/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2079/

2020-02-27 10:22 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2079/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2079/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2079/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2079/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2079/blogWCAG2AAhtmlcs.txt

2020-02-27 10:41 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2079/

2020-02-27 11:10 UTC, afi13 approved these changes

2020-02-27 11:10 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2081/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2081/

2020-02-27 11:36 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2081/

2020-02-27 12:27 UTC, closed without merging

2020-02-27 12:28 UTC, AndreyMaximov commented
@podarok We decided to incorporate these changes in Search API related PR.