mNew membership
ymcatwincities/openy pull request #1933
Opened 2020-03-04 21:07 UTC by anpolimus

Original Issue, this PR is going to fix: REPLACE WITH A LINK TO ISSUE ( publicly available )

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2020-03-04 21:13 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2085/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2085/

2020-03-04 21:14 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2085/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2085/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2085/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2085/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2085/blogWCAG2AAhtmlcs.txt

2020-03-05 17:19 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2087/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2087/

2020-03-05 17:47 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2087/

2020-03-06 12:00 UTC, podarok requested changes
Great
Let's make this even better

Please, see comments

2020-03-06 12:00 UTC, podarok commented on modules/custom/openy_analytics/src/AnalyticsCron.php
> +    $php_version = phpversion();
It would be cool to have this outside of the current scope, this is unrelated to membership change and probably already in 8.x-2.x

2020-03-06 12:00 UTC, podarok commented on modules/custom/paragraph_skins/composer.json
> +    "homepage": "https://www.drupal.org/project/paragraph_skins",
no such project url, could we make this file clear?
I guess we can make this as a dedicated https://github.com/ymcatwincities/paragraph_skins GitHub repo, if acceptable - do so and include it in composer.json only for this project, please

I've created https://packagist.org/packages/openy/paragraph_skins and it is ready to go once code pushed and tagged release

2020-03-06 12:00 UTC, podarok commented on modules/custom/paragraph_skins/paragraph_skins.info.yml
> +package: 'Paragraphs'
let's push to https://github.com/ymcatwincities/paragraph_skins and set version string

2020-03-06 12:00 UTC, podarok commented on modules/custom/paragraph_skins/paragraph_skins.module
> +    $element['subform']['skin']['widget']['#options']['_none'] = "Default";
let's wrap to `t()` to be able to override it via translation or string alter subsystems

2020-03-06 12:00 UTC, podarok commented on modules/custom/paragraph_skins/paragraph_skins.paragraph_skins.yml
> +  - name: rounded-image
can we add empty lines for better reading?
Or organize in array with keys

2020-03-06 12:00 UTC, podarok commented on modules/custom/paragraph_skins/src/SkinManager.php
> +    'paragraph_type' => '',
can we have meaningful default, not empty values?

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_block/modules/openy_block_modal/openy_block_modal.info.yml
> +name: Open Y Modal Block
same here https://packagist.org/packages/openy/openy_block_modal
https://github.com/ymcatwincities/openy_block_modal
Let's make our life easier and add new modules as composer pieces...
Thank you

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_block/modules/openy_block_modal/openy_block_modal.libraries.yml
> +      css/modal-block.css: {}
minified? If so - add a tag

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_1c/openy_prgf_1c.module
> +function openy_prgf_1c_paragraph_skins(array &$data) {
add dockblock, please

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.module
> +function openy_prgf_featured_highlights_paragraph_skins(array &$data) {
add dockblock, please

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_sidebar_menu/config/install/field.storage.paragraph.field_prgf_sidebar_menu_ref.yml
> +persist_with_no_fields: false
`true`, everywhere, please
This is important for not killing data accidentally

2020-03-06 12:00 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_sidebar_menu/openy_prgf_sidebar_menu.info.yml
> +name: 'Open Y Sidebar Menu'
same, please https://packagist.org/packages/openy/openy_prgf_sidebar_menu
https://github.com/ymcatwincities/openy_prgf_sidebar_menu

2020-03-06 12:00 UTC, podarok commented on themes/openy_themes/openy_carnation/templates/field/field--paragraph--1c.html.twig
> +        <div class="item">
`item` is pretty generic class, could cause regressions for 1C , right?

2020-03-06 12:00 UTC, podarok commented on themes/openy_themes/openy_carnation/templates/field/field.html.twig
> +      <div class="item">
same here

2020-03-06 12:00 UTC, podarok commented on themes/openy_themes/openy_carnation/templates/node/node--landing-page--full.html.twig
> +{% if content.field_content|render|trim is not empty %}
shouldn't this be `isEmpty()` ?

2020-03-06 12:00 UTC, podarok commented on themes/openy_themes/openy_lily/templates/node/include/node--landing-page--two-columns-left.html.twig
> +{% if content.field_content|render|trim is not empty %}
shouldn't this be `isEmpty()` ?

2020-03-06 12:00 UTC, podarok commented on themes/openy_themes/openy_lily/templates/node/include/node--landing-page--two-columns-left.html.twig
> +{% if content.field_content|render|trim is not empty %}
Could you provide template's dockblock, please?

2020-03-17 12:21 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2113/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2113/

2020-03-17 14:38 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2113/

2020-03-25 10:47 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2135/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2135/

2020-03-25 10:48 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2135/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2135/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2135/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2135/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2135/blogWCAG2AAhtmlcs.txt

2020-03-25 11:14 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2135/

2020-03-25 12:31 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2136/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2136/

2020-03-25 12:31 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2136/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2136/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2136/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2136/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2136/blogWCAG2AAhtmlcs.txt

2020-03-25 12:57 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2136/

2020-04-09 16:15 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2169/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2169/

2020-04-09 16:15 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2169/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2169/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2169/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2169/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2169/blogWCAG2AAhtmlcs.txt

2020-04-09 16:42 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2169/

2020-05-06 11:57 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2195/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2195/

2020-05-06 11:58 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2195/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2195/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2195/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2195/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2195/blogWCAG2AAhtmlcs.txt

2020-05-06 12:26 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2195/

2020-06-04 15:29 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-07-30 09:47 UTC, closed without merging