Contacts block as paragraph.
ymcatwincities/openy pull request #1936
Opened 2020-03-06 19:33 UTC by anpolimus

In this issue, we've fixed: https://github.com/ymcatwincities/openy/issues/1781
Branch address info was hard-coded across all themes.
We made it a separate paragraph which could be added anywhere at page.

## Steps for review

- [ ] Open Branch page
- [ ] Expect branch contact info block
- [ ] Check that Branch contacts info could be moved across the page.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2020-03-06 19:34 UTC, anpolimus commented
@podarok it is not finished yet. We have a small bug with gallery migration at the branch demo content.
But you could check code in general for now.

2020-03-06 19:38 UTC, podarok submitted a review, later dismissed
Code looks good. Let's do some QA next week to get merged.
Thank you

2020-03-06 19:40 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2094/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2094/

2020-03-06 19:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2094/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2094/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2094/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2094/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2094/blogWCAG2AAhtmlcs.txt

2020-03-06 20:08 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2094/

2020-03-09 13:10 UTC, anpolimus commented
retest this please

2020-03-09 13:14 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2095/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2095/

2020-03-09 13:16 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2096/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2096/

2020-03-09 13:29 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2096/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2096/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2096/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2096/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2096/blogWCAG2AAhtmlcs.txt

2020-03-09 13:44 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2095/

2020-03-09 13:47 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2096/

2020-03-09 18:25 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2097/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2097/

2020-03-09 18:52 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2097/

2020-03-10 14:42 UTC, anpolimus commented
retest this please

2020-03-10 14:49 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2100/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2100/

2020-03-10 14:49 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2100/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2100/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2100/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2100/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2100/blogWCAG2AAhtmlcs.txt

2020-03-10 15:09 UTC, podarok requested changes
Small things
Thank you. looks good code wise

2020-03-10 15:09 UTC, podarok commented on themes/openy_themes/openy_lily/css/style.css.map
> +{
let's avoid map compilation. This is prod

2020-03-10 15:17 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2100/

2020-03-10 15:25 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2101/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2101/

2020-03-10 15:25 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2101/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2101/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2101/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2101/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2101/blogWCAG2AAhtmlcs.txt

2020-03-10 15:52 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2101/

2020-03-10 16:04 UTC, merged

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
> +            {{ link('Back to All Locations', 'internal:/locations' ) }}
The URL should not be hardcoded.

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
> +{{ drupal_breadcrumb() }}
Other `node--full` templates do not have breadcrumbs and local tasks in this place. If we add them here for the program page it makes sense to do the same thing in other node templates. What do you think?

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
> +{{ drupal_breadcrumb() }}
But in general, I don't like the way we add breadcrumbs and local tasks. Looks like this is only Carnation related problem.

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
> +            {{ link('Back to All Locations', 'internal:/locations' ) }}
will be an issue for those who use another URL

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
> +            {{ link('Back to All Locations', 'internal:/locations' ) }}
for camps here should be another link

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/block/block-branch-contacts-info.html.twig
> +          <br/><a href="tel:{{ fax }}">{{ fax }}</a> (fax)
formatting is needed

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/block/block-branch-contacts-info.html.twig
> +          <br/><a href="tel:{{ fax }}">{{ fax }}</a> (fax)
(fax) text is not translated

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/block/block-branch-contacts-info.html.twig
> +  <blockquote class="hidden-sm hidden-md hidden-lg mobile">
is there a way to leverage HTML structure from the desktop instead of duplicating it for mobile?

2020-03-10 17:11 UTC, ddrozdik commented on themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
> +                  <a href="tel:{{ phone }}">{{ phone }}</a>
seems fax is missing here. Please check.

2020-03-10 17:17 UTC, anpolimus commented on themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
> +            {{ link('Back to All Locations', 'internal:/locations' ) }}
@ddrozdik what it should be?

2020-03-11 09:27 UTC, anpolimus commented
retest this please

2020-03-11 09:53 UTC, retif commented on themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
> +{{ drupal_breadcrumb() }}
> Other node--full templates do not have breadcrumbs and local tasks in this place.

They have it too, but through `{% include '@openy_carnation/node/include/header-default.html.twig' %}`

This is indeed related only to Carnation. The reason is that on Carnation we need to put breadcrumbs between field_header_content and field_contend fields of the node.

2020-03-12 15:11 UTC, podarok commented
@anpolimus ensure this review addressed by your team, please