[INOYI-1]: Remove deprecated entity.query service from Drupal\openy_r…
ymcatwincities/openy pull request #1950
Opened 2020-03-18 10:03 UTC by AleksandrPrykhodkoDev

Original source:
https://github.com/ymcatwincities/openy/issues/1421

## Steps for review

- [ ] Check code changes
- [ ] Check Schedules paragraph after refactoring

2020-03-18 10:05 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-03-18 13:14 UTC, dchubar-fj commented on modules/custom/openy_repeat/src/RepeatManager.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager, LoggerChannelFactoryInterface $logger_factory, ConfigFactoryInterface $configFactory) {
@AleksandrPrykhodkoDev you have removed the entity query dependency from the constructor, but I don't see where did you update the service definition for the class?

2020-03-18 21:52 UTC, dchubar-fj requested changes

2020-03-18 21:52 UTC, dchubar-fj commented on modules/custom/openy_session_instance/src/SessionInstanceManager.php
> +  public function __construct(EntityTypeManagerInterface $entity_type_manager, LoggerChannelFactoryInterface $logger_factory, ConfigFactoryInterface $configFactory) {
Usage of `$this->entityQuery` should be replaced with `$this->entityTypeManager` as well. The class is broken now.

2020-03-19 15:20 UTC, podarok submitted a review, later dismissed

2020-03-19 15:22 UTC, podarok commented
ok to test

2020-03-19 15:28 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2123/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2123/

2020-03-19 15:28 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2123/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2123/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2123/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2123/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2123/blogWCAG2AAhtmlcs.txt

2020-03-19 15:31 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2123/

2020-03-23 08:20 UTC, dchubar-fj requested changes

2020-03-23 08:20 UTC, dchubar-fj commented on modules/custom/openy_repeat/src/RepeatManager.php
> +  public static function create(ContainerInterface $container) {
@AleksandrPrykhodkoDev this service is defined in the YML file, so why do you use this approach here? It doesn't work, the service is broken now. Please define all dependencies in `openy_session_instance.services.yml` and update the original `SessionInstanceManager.php` service for that.

2020-03-23 08:56 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2124/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2124/

2020-03-23 08:59 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2124/

2020-03-23 09:23 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2124/

2020-03-23 09:25 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2125/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2125/

2020-03-23 09:25 UTC, bjwilkins commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2125/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2125/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2125/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2125/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2125/blogWCAG2AAhtmlcs.txt

2020-03-23 09:28 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2126/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2126/

2020-03-23 09:28 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2125/

2020-03-23 09:31 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build2126/

2020-03-23 09:51 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2125/

2020-03-23 09:53 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2126/

2020-04-14 15:07 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2175/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2175/

2020-04-14 15:35 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2175/

2020-05-20 08:35 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2214/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2214/

2020-05-20 08:35 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2214/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2214/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2214/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2214/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2214/blogWCAG2AAhtmlcs.txt

2020-05-20 08:49 UTC, podarok approved these changes

2020-05-20 08:50 UTC, merged

2020-05-20 09:00 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2214/