GroupExScheduleFetcher cache not validated correctly #1928
ymcatwincities/openy pull request #1971
Opened 2020-03-27 10:23 UTC by rahulusagility

Original Issue, this PR is going to fix: https://github.com/ymcatwincities/openy/issues/1928

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 8.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2020-03-27 10:24 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-04-06 10:22 UTC, podarok requested changes
Let's remove commented code, please

2020-04-06 10:22 UTC, podarok commented on modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
> +    // }
we can't keep commented code, as per Drupal code quality requirements. 
If we need to have code disable - let's introduce settings/option in Admin UI
If code would be never used - let's just remove it

2020-04-06 16:20 UTC, mattshoaf commented
Hi everyone, I presented commented out code in the related issue as a workaround for the Y site that we work with to give a clue as to where this was breaking. I think that if we dig into the `$this->schedule` array in the if conditional, we can find the appropriate parameter to check, something like `if($this->schedule['params'] == $submitted_form_params)`

My opinion: I would rather find a fix for this, if we remove caching completely, there would be a lot of other code to depreciate besides just these lines. Also, it would be ideal to fix this so that we don't have to ping the GroupEx servers for identical queries.

2020-06-04 15:29 UTC, bjwilkins commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-06-05 12:35 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-06-05 12:35 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-11-17 16:13 UTC, podarok commented
I'm going to close this because of low demand
This PR is just an example of a workaround.

2020-11-17 16:13 UTC, closed without merging