[INOYI-4]: Hide Drupal themes from the list of available themes on th…
ymcatwincities/openy pull request #1972
Opened 2020-03-27 15:40 UTC by AleksandrPrykhodkoDev

Original source: https://github.com/ymcatwincities/openy/issues/1763

## Steps for review

- [ ] Visit page `admin/appearance`
- [ ] Drupal themes hidden

<img width="1422" alt="Снимок экрана 2020-03-27 в 17 33 13" src="https://user-images.githubusercontent.com/18702600/77773248-00b96280-7052-11ea-8c86-142e68c4a6ce.png">

2020-03-27 15:42 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-03-30 14:30 UTC, podarok requested changes

2020-03-30 14:30 UTC, podarok commented on modules/custom/openy_system/openy_system.module
> +      if ($theme->origin === 'core' || $theme->info['name'] === 'Open Y Admin') {
can we have a security setting instead of disabling list for everyone?
As Administrator - would be nice to have ability to use any themes

2020-03-31 11:47 UTC, AleksandrPrykhodkoDev commented
@podarok fixed

2020-03-31 11:49 UTC, podarok requested changes
A small thing to get merged

2020-03-31 11:49 UTC, podarok commented on modules/custom/openy_system/openy_system.permissions.yml
> +  title: 'Use all Drupal themes'
Let's add hook_update_N as well

2020-03-31 12:48 UTC, AleksandrPrykhodkoDev commented
@podarok done, check please

2020-04-01 14:36 UTC, dchubar-fj approved these changes

2020-04-01 19:09 UTC, ddrozdik approved these changes

2020-04-06 10:20 UTC, podarok approved these changes

2020-04-06 10:20 UTC, merged