Activity Finder: fix possible negative values come from Daxko when no…
ymcatwincities/openy pull request #1999
Opened 2020-04-23 08:18 UTC by jediandrey

Daxko returns "-1" in some cases for "Spots Available", the PR fixes this issue, we don't need to show negative values, they mean there are no registration limits.

before https://take.ms/p6xLp
after https://take.ms/TlTLL
daxko session https://take.ms/qZoGm

2020-04-23 08:27 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2183/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2183/

2020-04-23 08:27 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2183/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2183/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2183/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2183/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2183/blogWCAG2AAhtmlcs.txt

2020-04-23 08:52 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2183/

2020-04-23 10:23 UTC, podarok approved these changes

2020-04-23 12:41 UTC, AndreyMaximov requested changes
@podarok take a look please http://openy.cibox.tools:8080/job/INSTALL_PATH_BUILD/345/consoleFull

2020-04-24 12:45 UTC, podarok approved these changes

2020-04-24 12:58 UTC, merged