[OYPD-310] Camp menu links, default home link to camp.
ymcatwincities/openy pull request #201
Opened 2017-03-01 19:26 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-03-01 19:30 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build634/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build634 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build634 |
| Installation process | http://install.openy-dev.ffwua.com/build634/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/634/

2017-03-01 19:34 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build634/profiles/openy/build/reports/behat

2017-03-02 09:44 UTC, alexschedrov requested changes

2017-03-02 09:44 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/src/Plugin/Block/CampMenu.php
> +        'title' => 'Home',
Should be translatable.

2017-03-02 09:52 UTC, Sanchiz commented
retest this please

2017-03-02 09:56 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build638/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build638 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build638 |
| Installation process | http://install.openy-dev.ffwua.com/build638/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/638/

2017-03-02 09:59 UTC, Sanchiz commented
1. Please fix code sniffer.

2017-03-02 10:00 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build638/profiles/openy/build/reports/behat

2017-03-02 21:02 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build647 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build647 |
| Installation process | http://install.openy-dev.ffwua.com/build647/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/647/

2017-03-02 21:05 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build647/profiles/openy/build/reports/behat

2017-03-03 08:55 UTC, Sanchiz commented
retest this please

2017-03-03 09:01 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build649 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build649 |
| Installation process | http://install.openy-dev.ffwua.com/build649/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/649/

2017-03-03 09:01 UTC, alexschedrov approved these changes
Approved.

2017-03-03 09:04 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build649/profiles/openy/build/reports/behat

2017-03-03 09:04 UTC, merged