Branch Amenities: Closed Amenities
ymcatwincities/openy pull request #2015
Opened 2020-05-18 16:29 UTC by vitalii-stepaniuk

This PR adds Closed Amenities field to Branch content type, displays amenities in two columns (Open and Closed amenities, if closed amenities exist), and adds a paragraph Branch Amenities that shows amenities with green check (open) and red cross (closed) icons.

## Steps for review

- [ ] Run updates.
- [ ] Edit any branch and add closed amenities inside Branch Amenities fielder.
- [ ] Add Branch Amenities paragraph to the node.

2020-05-18 16:31 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-05-18 21:06 UTC, anpolimus requested changes

2020-05-18 21:06 UTC, anpolimus commented on modules/custom/openy_ckeditor/openy_ckeditor.module
> +    ->getStorage('taxonomy_term')
TaxonomyTerm::loadMultiple

2020-05-19 06:19 UTC, vitalii-stepaniuk commented on modules/custom/openy_ckeditor/openy_ckeditor.module
> +    ->getStorage('taxonomy_term')
Fixed

2020-05-19 10:30 UTC, AndreyMaximov commented
ok to test

2020-05-19 10:39 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2206/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2206/

2020-05-19 10:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2206/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2206/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2206/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2206/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2206/blogWCAG2AAhtmlcs.txt

2020-05-19 11:06 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2206/

2020-05-19 12:14 UTC, podarok requested changes
Small changes, please

2020-05-19 12:14 UTC, podarok commented on modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/paragraphs.paragraphs_type.branch_amenities.yml
> +  default_config_hash: c4A5enOspH2lSRkObw2PzbZcD-ldXLpBO91Nk0F6Qas
it looks wrong. Hash should not be included in configs

2020-05-19 12:14 UTC, podarok commented on modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/field.storage.paragraph.field_amenities_block.yml
> +  default_config_hash: n4KePQPN8a6yMnGHTR-lYrOMBMOUQXhNQ89Q80fLjjg
it looks wrong. Hash should not be included in configs

2020-05-19 12:14 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.default.yml
> +  default_config_hash: mRQJNhp4t6OSJSFQmOqvzFti_RolSTMMSKpRgcezXNE
it looks wrong. Hash should not be included in configs

2020-05-19 12:14 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_amenities_closed.yml
> +description: ''
can we have a business description everywhere?

2020-05-19 12:14 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.storage.node.field_location_amenities_closed.yml
> +persist_with_no_fields: false
always true, please

2020-05-19 12:14 UTC, podarok commented on themes/openy_themes/openy_carnation/src/scss/paragraphs/_amenities.scss
> +  color: #4f4f4f;
can we use global _variables where all colors stored?

2020-05-19 12:14 UTC, podarok commented on themes/openy_themes/openy_carnation/src/scss/paragraphs/_amenities.scss
> +      color: #dc3545;
same here, global colors, please

2020-05-19 13:17 UTC, vitalii-stepaniuk commented
@podarok The issues you've listed above are fixed now. Could you please review the PR again?
Thanks!

2020-05-19 13:20 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2207/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2207/

2020-05-19 13:20 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2207/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2207/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2207/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2207/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2207/blogWCAG2AAhtmlcs.txt

2020-05-19 13:46 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2207/

2020-05-19 16:27 UTC, podarok submitted a review, later dismissed

2020-05-19 16:29 UTC, podarok commented
@vitalii-stepaniuk fix conflicts and this one ready to be merged

2020-05-19 17:05 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2212/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2212/

2020-05-19 17:07 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2212/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2212/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2212/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2212/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2212/blogWCAG2AAhtmlcs.txt

2020-05-19 17:32 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2212/

2020-05-20 06:57 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build2213/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/2213/

2020-05-20 06:58 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://openy.cibox.tools/build2213/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://openy.cibox.tools/build2213/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://openy.cibox.tools/build2213/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://openy.cibox.tools/build2213/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://openy.cibox.tools/build2213/blogWCAG2AAhtmlcs.txt

2020-05-20 07:23 UTC, gundevel commented
Open Y Complete profile installed at http://openy.cibox.tools/build2213/

2020-05-20 08:26 UTC, merged