YOPN-520: Ping Pong
ymcatwincities/openy pull request #2017
Opened 2020-05-20 10:22 UTC by vitalii-stepaniuk

Adding Ping Pong paragraph

2020-05-20 10:25 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-05-20 10:49 UTC, anpolimus requested changes
TODO: Styling exist only for Carnation.
Please, add Rose and Lily

2020-05-20 10:49 UTC, anpolimus commented on themes/openy_themes/openy_carnation/src/scss/paragraphs/_ping-pong.scss
> +      background-color:#faf5ff;
Please, reuse varible here.

2020-05-20 10:49 UTC, anpolimus commented on themes/openy_themes/openy_carnation/src/scss/paragraphs/_ping-pong.scss
> +      background-color: #12619e;
var

2020-06-04 15:29 UTC, bjwilkins commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-06-05 12:35 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2020-12-22 10:56 UTC, podarok commented
Outdated and we decided to go with [Paragraph Skins](https://github.com/ymcatwincities/paragraph_skins) when there is a need for current components alteration

2020-12-22 10:56 UTC, closed without merging