[OYPD-281] Add some Simple Content to Camp page. Add blog posts related to Camp pages.
ymcatwincities/openy pull request #219
Opened 2017-03-08 19:28 UTC by Kerby70

Jira https://propeople-us.atlassian.net/browse/OYPD-281?focusedCommentId=82500&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-82500
D.o 

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-03-08 19:33 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build709 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build709 |
| Installation process | http://install.openy-dev.ffwua.com/build709/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/709/

2017-03-08 19:36 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build709/profiles/openy/build/reports/behat

2017-03-09 11:05 UTC, Sanchiz commented
retest this please

2017-03-09 11:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build710 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build710 |
| Installation process | http://install.openy-dev.ffwua.com/build710/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/710/

2017-03-09 11:14 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build710/profiles/openy/build/reports/behat

2017-03-09 11:16 UTC, alexschedrov requested changes

2017-03-09 11:16 UTC, Sanchiz commented on modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.node_blog_camp.yml
> +        <ul class="ms-rteStyle-Normal"><li>
Let's remove class.

2017-03-09 11:16 UTC, Sanchiz commented
For some reason some blog posts no longer have images
![image](https://cloud.githubusercontent.com/assets/1316234/23748037/9b39bc98-04ca-11e7-90e5-8b5f357dcebc.png)

2017-03-09 13:26 UTC, Kerby70 commented
Those are new blog posts, content from random pages on seattleymca.org, I did not realize the importance of the style photo card.

2017-03-09 15:50 UTC, Sanchiz commented
@Kerby70 let's just change style to some that doesn't require image.

2017-03-09 20:05 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/716/

**Build Log**
*last 25 lines*

 ```
[...truncated 281 lines...]
stdout: You are about to create a /var/www/build716/sites/default/settings.php file and DROP all tables in your 'drupal716' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-09 20:15 UTC, Kerby70 commented
retest this please

2017-03-09 20:18 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/718/

**Build Log**
*last 25 lines*

 ```
[...truncated 272 lines...]
stdout: You are about to create a /var/www/build718/sites/default/settings.php file and DROP all tables in your 'drupal718' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=5    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-10 00:51 UTC, Kerby70 commented
retest this please

2017-03-10 00:54 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/721/

**Build Log**
*last 25 lines*

 ```
[...truncated 281 lines...]
stdout: You are about to create a /var/www/build721/sites/default/settings.php file and DROP all tables in your 'drupal721' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-10 01:24 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build722 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build722 |
| Installation process | http://install.openy-dev.ffwua.com/build722/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/722/

2017-03-10 01:28 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build722/profiles/openy/build/reports/behat

2017-03-10 09:18 UTC, Sanchiz commented
@Kerby70 
1. Let's fix tests for blog posts. There's another task to move away from using demo content in behat tests.

2. Test for paragraph should be fixed in terms of https://propeople-us.atlassian.net/browse/OYPD-334

2017-03-10 13:57 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build725 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build725 |
| Installation process | http://install.openy-dev.ffwua.com/build725/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/725/

2017-03-10 14:01 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build725/profiles/openy/build/reports/behat

2017-03-10 14:49 UTC, alexschedrov approved these changes
Approved.

2017-03-10 14:49 UTC, merged