[OYPD-289] Add membership demo content & demo join page.
ymcatwincities/openy pull request #222
Opened 2017-03-09 19:45 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-03-09 19:51 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build714/build_reports/Drupalsniff.txt
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build714 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build714 |
| Installation process | http://install.openy-dev.ffwua.com/build714/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/714/

2017-03-09 19:54 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build714/profiles/openy/build/reports/behat

2017-03-09 19:58 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build715 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build715 |
| Installation process | http://install.openy-dev.ffwua.com/build715/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/715/

2017-03-09 20:02 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build715/profiles/openy/build/reports/behat

2017-03-10 01:43 UTC, Kerby70 commented
retest this please

2017-03-10 01:49 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build723 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build723 |
| Installation process | http://install.openy-dev.ffwua.com/build723/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/723/

2017-03-10 01:52 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build723/profiles/openy/build/reports/behat

2017-03-10 09:20 UTC, alexschedrov requested changes

2017-03-10 09:20 UTC, Sanchiz commented on modules/openy_features/openy_demo_content/modules/openy_demo_nmbrshp/config/install/migrate_plus.migration.node_membership.yml
> +        <p>Monthly Rate: $120</p>
Please remove `Join Fee` and `Monthly Rate` from all descriptions.

2017-03-10 14:41 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build728 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build728 |
| Installation process | http://install.openy-dev.ffwua.com/build728/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/728/

2017-03-10 14:44 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build728/profiles/openy/build/reports/behat

2017-03-10 14:59 UTC, AlexNetman commented
Why I don't see Alerts on the latest build?

2017-03-10 15:02 UTC, Sanchiz commented
@AlexNetman because it hasn't been merged with master yet.

2017-03-10 15:08 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build731 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build731 |
| Installation process | http://install.openy-dev.ffwua.com/build731/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/731/

2017-03-10 15:12 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build731/profiles/openy/build/reports/behat

2017-03-10 15:14 UTC, alexschedrov approved these changes
Approved.

2017-03-10 15:14 UTC, merged