Extend taxonomy page
ymcatwincities/openy pull request #229
Opened 2017-03-13 18:11 UTC by podarok

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

### Steps for review
- [ ] Go to any taxonomy page
- [ ] Edit it
- [ ] Ensure you are able to add Paragraphs to this page at the top of the taxonomy listing

2017-03-13 18:12 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/736/

**Build Log**
*last 25 lines*

 ```
[...truncated 194 lines...]
TASK: [Enable stage file proxy] *********************************************** 
skipping: [localhost]

TASK: [Set configuration for stage file proxy] ******************************** 
skipping: [localhost]

TASK: [Updates listing] ******************************************************* 
skipping: [localhost]

TASK: [Droping drupal database] *********************************************** 
ok: [localhost]

TASK: [Creating drupal database] ********************************************** 
changed: [localhost]

TASK: [Remove settings.php] *************************************************** 
ok: [localhost]

TASK: [Build project from drupal-org.make] ************************************ 
changed: [localhost]

TASK: [Installing drupal] ***************************************************** 
Build was aborted
Aborted by anonymous
```

2017-03-13 18:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build737 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build737 |
| Installation process | http://install.openy-dev.ffwua.com/build737/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/737/

2017-03-13 18:21 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build737/profiles/openy/build/reports/behat

2017-03-13 18:32 UTC, AlexNetman commented
Please add description for the newly added field.
![image](https://cloud.githubusercontent.com/assets/4558228/23869435/fac10664-0833-11e7-926d-c09ea5ccfb7e.png)
Like 
"This paragraph will appear in the header of each taxonomy term page."

And restrict available paragraphs only to those that suppose to be in header area. Check example in Header area of Landing page at /node/add/landing_page .
![image](https://cloud.githubusercontent.com/assets/4558228/23869553/66c35650-0834-11e7-81db-ddf5becd6702.png)

2017-03-13 18:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build738 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build738 |
| Installation process | http://install.openy-dev.ffwua.com/build738/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/738/

2017-03-13 18:50 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build738/profiles/openy/build/reports/behat

2017-03-13 18:54 UTC, podarok commented
@AlexNetman done

2017-03-13 18:55 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/739/

**Build Log**
*last 25 lines*

 ```
[...truncated 270 lines...]
stdout: You are about to create a /var/www/build739/sites/default/settings.php file and DROP all tables in your 'drupal739' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-13 19:05 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build740 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build740 |
| Installation process | http://install.openy-dev.ffwua.com/build740/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/740/

2017-03-13 19:09 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build740/profiles/openy/build/reports/behat

2017-03-14 08:27 UTC, alexschedrov requested changes

2017-03-14 08:27 UTC, Sanchiz commented on modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
> +    'field.storage.taxonomy_term.field_taxonomy_content'
I think storage sjould live in `openy_taxonomy` module, because it can be reused by other taxonomy pages.

2017-03-14 08:31 UTC, podarok commented on modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
> +    'field.storage.taxonomy_term.field_taxonomy_content'
@Sanchiz is it possible to make it in follow-up at a time of need to reuse?

2017-03-14 11:21 UTC, alexschedrov approved these changes
Approved.

2017-03-14 11:21 UTC, merged