[OYPD-338] Add permission 'Access admin structure page' and replace the structure page route permission control.
ymcatwincities/openy pull request #231
Opened 2017-03-14 12:26 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-03-14 12:31 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build742 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build742 |
| Installation process | http://install.openy-dev.ffwua.com/build742/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/742/

2017-03-14 12:34 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build742/profiles/openy/build/reports/behat

2017-03-14 13:45 UTC, alexschedrov requested changes

2017-03-14 13:45 UTC, Sanchiz commented on modules/openy_features/openy_user/config/install/user.role.editor.yml
> +  163: 'access structure page'
Upgrade path.

2017-03-14 14:15 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/743/

**Build Log**
*last 25 lines*

 ```
[...truncated 225 lines...]
stdout: You are about to create a /var/www/build743/sites/default/settings.php file and DROP all tables in your 'drupal743' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-15 13:33 UTC, AlexNetman commented
retest this please

2017-03-15 13:36 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/748/

**Build Log**
*last 25 lines*

 ```
[...truncated 225 lines...]
stdout: You are about to create a /var/www/build748/sites/default/settings.php file and DROP all tables in your 'drupal748' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-15 20:26 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/749/

**Build Log**
*last 25 lines*

 ```
[...truncated 233 lines...]
stdout: You are about to create a /var/www/build749/sites/default/settings.php file and DROP all tables in your 'drupal749' database. Do you want to continue? (y/n): y

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/reinstall.retry

localhost                  : ok=14   changed=6    unreachable=0    failed=1   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:227)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:200)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
ERROR: Ansible playbook execution failed
```

2017-03-15 20:34 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build750 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build750 |
| Installation process | http://install.openy-dev.ffwua.com/build750/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/750/

2017-03-16 10:11 UTC, Sanchiz commented
retest this please

2017-03-16 10:16 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build752 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build752 |
| Installation process | http://install.openy-dev.ffwua.com/build752/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/752/

2017-03-16 10:17 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build752/profiles/openy/build/reports/behat

2017-03-16 10:41 UTC, Sanchiz commented
retest this please

2017-03-16 10:48 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build755 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build755 |
| Installation process | http://install.openy-dev.ffwua.com/build755/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/755/

2017-03-16 10:52 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build755/profiles/contrib/openy/build/reports/behat

2017-03-16 11:25 UTC, alexschedrov approved these changes
Approved.

2017-03-16 11:26 UTC, merged