[MAINTAIN-12] Small Banner paragraph should be responsive in Rose theme
ymcatwincities/openy pull request #2436
Opened 2021-04-12 12:21 UTC by aleevas

Original Issue, this PR is going to fix: [MAINTAIN-12](https://openy.atlassian.net/browse/MAINTAIN-12)

This one should add ability to Small Banner paragraph to be responsive with big amount of text.
Now if you want to add a much more text than banner height can store -> the banner increazing the height of block. And an image placed by center of Y axe.
![MAINTAIN-12SmallBannerWithBigTextRose](https://user-images.githubusercontent.com/744406/114393431-ac244f00-9ba2-11eb-9f16-039f6f865699.png)
![MAINTAIN-12SmallBannerWithBigTextRoseTablet](https://user-images.githubusercontent.com/744406/114393435-ad557c00-9ba2-11eb-837f-7184ea1302c7.png)
![MAINTAIN-12SmallBannerWithBigTextRoseMobile](https://user-images.githubusercontent.com/744406/114393439-af1f3f80-9ba2-11eb-9401-c660d772f71a.png)

## Steps for review

- [ ] Log as admin
- [ ] go to edit home page
- [ ] add a new Small Banner block with long title and description
- [ ] verify that you can see all text in this banner
- [ ] verify on different type of screens

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2021-04-12 12:22 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2021-04-12 12:32 UTC, podarok commented
ok to test

2021-04-12 12:37 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3135/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3135/

2021-04-12 12:39 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3135/

2021-04-12 13:22 UTC, podarok commented
Looks good
![image](https://user-images.githubusercontent.com/563412/114401142-5011f880-9bab-11eb-9445-b3c4efb0ab05.png)

2021-04-12 13:23 UTC, podarok approved these changes

2021-04-12 15:44 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3136/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3136/

2021-04-12 15:47 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3136/

2021-04-12 16:59 UTC, hamrant requested changes
On some screen sizes text not visible:

![Screenshot from 2021-04-12 19-24-33](https://user-images.githubusercontent.com/13733670/114432705-a5f59900-9bc9-11eb-9b41-28a0aa8b0813.png)

2021-04-12 16:59 UTC, hamrant commented on themes/openy_themes/openy_rose/scripts/openy_rose.js
> +          fontSize: '22px',
Let's try to use relative sizes, for example, `vw` - https://css-tricks.com/almanac/properties/f/font-size/

2021-04-12 17:00 UTC, hamrant commented
@aleevas anyway, now it looks better:

![Screenshot from 2021-04-12 19-19-16](https://user-images.githubusercontent.com/13733670/114432824-c58cc180-9bc9-11eb-9c3d-0dfaf8dc0d0e.png)

![Screenshot from 2021-04-12 19-24-12](https://user-images.githubusercontent.com/13733670/114432839-c9204880-9bc9-11eb-944e-8ff3d9fe8547.png)

2021-04-13 10:02 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3137/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3137/

2021-04-13 10:05 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3137/

2021-04-13 12:38 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3138/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3138/

2021-04-13 12:40 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3138/

2021-04-13 12:53 UTC, hamrant approved these changes
Looks ok to me

![Screenshot from 2021-04-13 15-50-29](https://user-images.githubusercontent.com/13733670/114555299-3981a500-9c70-11eb-8292-7a2990405d51.png)

![Screenshot from 2021-04-13 15-51-08](https://user-images.githubusercontent.com/13733670/114555325-40a8b300-9c70-11eb-8d02-c97e93c6c27a.png)

![Screenshot from 2021-04-13 15-50-46](https://user-images.githubusercontent.com/13733670/114555357-47cfc100-9c70-11eb-99b1-492ab603c054.png)

On window resize text can be too small, but I think this not critical

2021-04-13 14:20 UTC, podarok approved these changes

2021-04-13 14:26 UTC, merged