Fix for Locations Filter
ymcatwincities/openy pull request #2447
Opened 2021-04-30 12:45 UTC by podarok

Original Issue, this PR is going to fix: #2445 

Make sure these boxes are checked before asking for review of your pull request - thank you!

If there is a new feature or this is a bug fix - use 9.x-2.x branch. We'll tag for release if the bug is critical asap or tag for release next bug fix release until critical issue arrived.

## Steps for review

- [ ] Please provide steps for review here.
- [ ] Please provide steps for review here.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2021-04-30 12:49 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3170/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3170/

2021-04-30 12:51 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3170/

2021-04-30 13:09 UTC, podarok commented
Tested on build
![image](https://user-images.githubusercontent.com/563412/116699591-6bb03800-a9ce-11eb-8e1a-1a42dbf2f862.png)

2021-04-30 13:18 UTC, hamrant requested changes

2021-04-30 13:18 UTC, hamrant commented on modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
> +    $branches_list = $this->getBranchesList();
Looks like `$branches_list` variable not used in the function

2021-04-30 13:23 UTC, froboy commented
Thanks @podarok

2021-04-30 15:01 UTC, froboy approved these changes
Apart from @hamrant's comment this looks good.

2021-04-30 15:12 UTC, podarok commented on modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
> +    $branches_list = $this->getBranchesList();
removed a line, nice catch

2021-04-30 15:15 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3171/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3171/

2021-04-30 15:18 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3171/

2021-05-05 08:12 UTC, hamrant approved these changes

2021-05-05 08:18 UTC, merged