Unlimited programs should be opened for users
ymcatwincities/openy pull request #2514
Opened 2021-07-08 15:23 UTC by dchubar-fj

**Problem/Motivation**
Classes with an unlimited number of spots are displayed as completely filled in Activity Finder with the Daxko back-end. The root of the problem is that Open Y doesn't check the `limited` flag in the Daxko response. Daxko back-end relies on the `available` field in the response:
```
         "availability":{
            "limited":true,
            "full":false,
            "max":20,
            "taken":0,
            "available":20,
            "has_waiting_list":false
         },
```
But unlimited classes don't have the `available` field:
```
         "availability":{
            "limited":false,
            "full":false,
            "taken":0,
            "has_waiting_list":true,
            "waiting_list_count":0,
            "show_waiting_list_count":false
         },
```

As result, unlimited classes are not available for registration in the Activity Finder, because the Register button is disabled
![Screenshot from 2021-07-08 18-12-46](https://user-images.githubusercontent.com/58946680/124947301-61d33280-e018-11eb-988d-93cb8faefe35.png)
But they are open for registration in Daxko
![Screenshot from 2021-07-08 18-14-16](https://user-images.githubusercontent.com/58946680/124947415-7a434d00-e018-11eb-84ac-757a93dfb47e.png)

## Steps for review

- [ ] Find a class with unlimited spots in the Activity Finder with the Daxko back-end
- [ ] Check program details
- [ ] Verify the register button is not disabled

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer. See [Code of Conduct](https://github.com/ymcatwincities/openy/wiki/Open-Y-Code-of-Conduct-and-Best-Practices).
- [ ] Try to use Conventional commit messages accordingly to the standard https://www.conventionalcommits.org/en/v1.0.0/#specification
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/9.x-2.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/9.x-2.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/9.x-2.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2021-07-08 15:24 UTC, podarok requested changes

2021-07-08 15:24 UTC, podarok commented on modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
> +        $spots_available = 100;
let's keep this as a constant of the current class, please

2021-07-08 15:25 UTC, podarok commented
@dchubar-fj could you put your description in module's readme.md?
Thank you

2021-07-08 15:28 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3277/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3277/

2021-07-08 15:30 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3277/

2021-07-09 08:10 UTC, podarok approved these changes
Code looks good
Let's improve readme a bit @dchubar-fj

2021-07-09 08:11 UTC, gundevel commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3278/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3278/

2021-07-09 08:13 UTC, gundevel commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3278/

2021-07-12 09:05 UTC, merged