[MAINTAIN-87] Add close icon to mobile menu.
ymcatwincities/openy pull request #2567
Opened 2021-10-07 14:10 UTC by manachynskyi

https://openy.atlassian.net/browse/MAINTAIN-87, this PR is going to fix missed Hamburger close icon on Carnation (on mobile)

Before: https://i.imgur.com/9OHzvoQ.png
After:    https://i.imgur.com/nAGHVcF.png

## Steps for review
- [ ] Visit any page on carnation
- [ ] Open mobile menu https://i.imgur.com/gJdBMbu.png
- [ ] Make sure close icon present https://i.imgur.com/nAGHVcF.png

2021-10-07 14:10 UTC, bjwilkins commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2021-10-07 14:11 UTC, podarok commented
ok to test

2021-10-07 14:11 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2021-10-07 14:12 UTC, podarok requested changes

2021-10-07 14:12 UTC, podarok commented on themes/openy_themes/scss/modules.scss
> -@import "../../../modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert";
why this is removed?
Let's avoid removing this, please

2021-10-07 14:16 UTC, podarok commented on themes/openy_themes/scss/modules.scss
> -@import "../../../modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert";
@manachynskyi

2021-10-07 14:18 UTC, bjwilkins commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3500/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3500/

2021-10-07 14:20 UTC, manachynskyi commented on themes/openy_themes/scss/modules.scss
> -@import "../../../modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert";
We don't have `openy_features` directory, and scss can't be compiled. We delete it here https://github.com/ymcatwincities/openy/pull/2479

2021-10-07 14:20 UTC, bjwilkins commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3500/

2021-10-07 14:26 UTC, manachynskyi commented on themes/openy_themes/scss/modules.scss
> -@import "../../../modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert";
Should we import files from `docroot/modules/contrib/openy_features/...`?

2021-10-07 14:41 UTC, manachynskyi commented on themes/openy_themes/scss/modules.scss
> -@import "../../../modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert";
@podarok Fixed

2021-10-07 14:44 UTC, bjwilkins commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3501/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3501/

2021-10-07 14:46 UTC, bjwilkins commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3501/

2021-10-07 15:01 UTC, hamrant commented on themes/openy_themes/scss/modules.scss
> +@import "../../../../../../modules/contrib/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq";
Maybe better to move these files into the carnation theme? Or in case they used in rose and lily, refactor to module library and include from the template?

2021-10-07 15:07 UTC, manachynskyi commented on themes/openy_themes/scss/modules.scss
> +@import "../../../../../../modules/contrib/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq";
These files are used in all themes. Maybe we should remove them from the theme import and import somewhere inside modules?

2021-10-07 16:23 UTC, hamrant commented on themes/openy_themes/scss/modules.scss
> +@import "../../../../../../modules/contrib/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq";
I believe that we should not have files outside of themes that can be used in import.

@podarok what do you think?

2021-10-12 06:42 UTC, podarok commented on themes/openy_themes/scss/modules.scss
> +@import "../../../../../../modules/contrib/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq";
ATM we have no clear understanding how to accomplish this scss common files for 3 themes. I guess it should be base theme ( not perfect ) or composer/npm package we should have added as dependency from every theme.
So let's keep them right now until we got final vision @hamrant

2021-10-12 06:42 UTC, podarok commented
@manachynskyi solve conflicts, please. Ready to merge afterwards

2021-10-12 08:26 UTC, manachynskyi commented
We should use 
@import "**../../../**../../../modules/contrib/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq";
because path that we have now used from theme in docroot, but we should compile from profile theme

2021-10-12 08:27 UTC, bjwilkins commented
Build comment file: 
--------------

Check Open Y Installation Wizard at http://install.openy.cibox.tools/build3503/install.php

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/3503/

2021-10-12 08:28 UTC, bjwilkins commented
Open Y Upgrade Path site check installed at http://upgrade.openy.cibox.tools/build3503/

2021-10-12 09:35 UTC, hamrant approved these changes

2021-10-12 11:16 UTC, merged