[OYPD-252] Update menu tests ensure removal after test run.
ymcatwincities/openy pull request #278
Opened 2017-03-31 19:07 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-03-31 19:12 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build875 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build875 |
| Installation process | http://install.openy-dev.ffwua.com/build875/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/875/

2017-03-31 19:16 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build875/profiles/contrib/openy/build/reports/behat

2017-03-31 21:22 UTC, AlexNetman commented
1) With this changes we don't attaching images to menu items anymore.
This case with menu-image upload and display need to be tested through UI - as it is customized functionality.

2) Also all menu items are created through Drupal API were some validations are not triggered. And bugs could be missed. 
Let's keep couple of tests that use UI for menu iteractions. Creation should be done under Editor role.

And for API tests it's not required to log in. Just go to home page and verify if you can see menu items created through API.

2017-04-03 10:12 UTC, Sanchiz commented
@AlexNetman 
1.  I agree. We should attach image.
2. You have a point here, but we are not testing Drupal Back-end UI.
What we can do:
- Save link through Drupal API like John does
- Make sure we see links in header/footer
- Go to Drupal UI and re-save link to make sure everything.

I'm not sure if 3rd step will be valuable in our case.

2017-04-03 19:13 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build878 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build878 |
| Installation process | http://install.openy-dev.ffwua.com/build878/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/878/

2017-04-03 19:16 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build878/profiles/contrib/openy/build/reports/behat

2017-04-03 19:18 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build879 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build879 |
| Installation process | http://install.openy-dev.ffwua.com/build879/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/879/

2017-04-03 19:22 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build879/profiles/contrib/openy/build/reports/behat

2017-04-04 08:41 UTC, Sanchiz commented
retest this please

2017-04-04 08:44 UTC, alexschedrov requested changes

2017-04-04 08:44 UTC, Sanchiz commented on tests/features/bootstrap/OpenyDrupalContext.php
> +  public function iCreateMenu_link_content(TableNode $table) {
Can we adjust method name to have CamelStyle? E.g. `iCreateMenuLinkContent`

2017-04-04 08:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build885 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build885 |
| Installation process | http://install.openy-dev.ffwua.com/build885/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/885/

2017-04-04 08:50 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build885/profiles/contrib/openy/build/reports/behat

2017-04-04 12:24 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build887 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build887 |
| Installation process | http://install.openy-dev.ffwua.com/build887/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/887/

2017-04-04 12:27 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build887/profiles/contrib/openy/build/reports/behat

2017-04-04 15:11 UTC, alexschedrov approved these changes
Approved & merged.

2017-04-04 15:11 UTC, merged

2017-04-07 20:51 UTC, AlexNetman reviewed
Needs some improvements. Otherwise feature is not covered.

2017-04-07 20:51 UTC, AlexNetman commented on tests/features/menus_and_blocks/menus.feature
> +    And I should see an "ul.nav.dropdown-menu .menu-item-behat-childcare .section-icon" element
This is "always true". No matter if we have image or not.
![image](https://cloud.githubusercontent.com/assets/4558228/24818787/862e2c6c-1bea-11e7-8d5b-ca84c25d32a4.png)
So what we can do to test this:
1) Run this scenarios through Selenium. And evaluate some custom js that checking if image is there.
2) Make a screenshot of this element "ul.nav.dropdown-menu .menu-item-behat-childcare" . And compare with expected one.

2017-04-07 20:51 UTC, AlexNetman commented on tests/features/menus_and_blocks/menus.feature
> -  Scenario: Create footer menu left item and check
Let's keep at least this scenario as it is checking permissions for Editor. If he is able to access menu section. And attach files to menus.  
If we don't make deletion of items based on names. At least we can delete it just as last item in the list at /admin/structure/menu/manage/footer-menu-left

2017-04-12 20:19 UTC, Kerby70 commented on tests/features/menus_and_blocks/menus.feature
> +    And I should see an "ul.nav.dropdown-menu .menu-item-behat-childcare .section-icon" element
I will revisit this, I am not familiar with either method described.

2017-04-13 12:21 UTC, Kerby70 commented on tests/features/menus_and_blocks/menus.feature
> -  Scenario: Create footer menu left item and check
The problem with having the test step remove items is, if it fails before that step it will remain in the database.

2017-04-13 14:50 UTC, Kerby70 commented on tests/features/menus_and_blocks/menus.feature
> -  Scenario: Create footer menu left item and check
@AlexNetman 
Assuming I can get the other portion to validate the image, or perhaps without that. Do you think editing a machine created menu entries as Editor, to add an image, would validate what we are trying to prove here?