[OYPD-24] Custom Forms & [OYPD-25] Form Submission Response Storage
ymcatwincities/openy pull request #286
Opened 2017-04-07 20:39 UTC by dave-the-brave

Installs Webform module as part of the installation process, along with Captcha and Recaptcha. Adds Paragraph to select a webform. Adds a demo form if selected as demo content.

To review:

- [ ] Create new build & run install process. Enter recaptcha information on 3rd party services page to enable Recaptcha on webforms by default, or leave empty to enable image captcha by default.
- [ ] Choose Demo Webform during installation to install a demo feature containing a demo webform
- [ ] Ensure relevant modules are installed, and that a Webform paragraph is available for use.
- [ ]  Test creating webform and submitting one or more webforms to check data submission/storage

2017-04-07 20:39 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-04-07 21:14 UTC, ygerasimov commented
o+k to test

2017-04-10 07:08 UTC, Sanchiz commented
ok to test

2017-04-10 07:13 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build908 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build908 |
| Installation process | http://install.openy-dev.ffwua.com/build908/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/908/

2017-04-10 07:20 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build908/profiles/contrib/openy/build/reports/behat

2017-04-14 09:14 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/947/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #286 of commit bf2058224bcd60d7cfc12c5072b701e964ffca54.
GitHub pull request #286 of commit bf2058224bcd60d7cfc12c5072b701e964ffca54.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7241691745020988573.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git43205421821579553.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse bf2058224bcd60d7cfc12c5072b701e964ffca54^{commit} # timeout=10
 > git branch -a --contains bf2058224bcd60d7cfc12c5072b701e964ffca54 # timeout=10
 > git rev-parse remotes/origin/pr/286/head^{commit} # timeout=10
Checking out Revision bf2058224bcd60d7cfc12c5072b701e964ffca54 (origin/pr/286/head)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f bf2058224bcd60d7cfc12c5072b701e964ffca54
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson2980502575076295878.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory2604990090292608037.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=947 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory2030526308702781502.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=947 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build947/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal947 -e drupal_folder=/var/www/build947 -e site_url=http://openy-dev.ffwua.com/build947 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [localhost] => (item={'status': True, 'name': '$config["system.file"]["path.temporary"]', 'value': [...]

2017-04-14 09:27 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build948 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build948 |
| Installation process | http://install.openy-dev.ffwua.com/build948/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/948/

2017-04-14 09:35 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build948/profiles/contrib/openy/build/reports/behat

2017-04-18 20:18 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build968 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build968 |
| Installation process | http://install.openy-dev.ffwua.com/build968/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/968/

2017-04-18 20:25 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build968/profiles/contrib/openy/build/reports/behat

2017-04-28 19:11 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1048 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1048 |
| Installation process | http://install.openy-dev.ffwua.com/build1048/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1048/

2017-04-28 19:19 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build1048/profiles/contrib/openy/build/reports/behat

2017-04-28 20:12 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1051 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1051 |
| Installation process | http://install.openy-dev.ffwua.com/build1051/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1051/

2017-04-28 20:19 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build1051/profiles/contrib/openy/build/reports/behat

2017-04-28 20:32 UTC, ygerasimov commented
retest this please

2017-04-28 20:41 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1053 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1053 |
| Installation process | http://install.openy-dev.ffwua.com/build1053/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1053/

2017-04-28 20:48 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build1053/profiles/contrib/openy/build/reports/behat

2017-04-28 20:58 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--webform--default.html.twig
> +</article>
Seems this template has been copied over, but wasn't adjusted for new paragraph.

2017-04-28 20:58 UTC, alexschedrov requested changes

2017-04-28 20:58 UTC, Sanchiz commented on themes/openy_themes/openy_rose/color/color.inc
> +      'title' => t('Endeavour'),
Please revert back.

2017-04-28 20:58 UTC, Sanchiz commented on themes/openy_themes/openy_rose/color/color.inc
> +      'title' => t('Lochmara (default)'),
Please revert back.

2017-04-28 21:28 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1056 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1056 |
| Installation process | http://install.openy-dev.ffwua.com/build1056/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1056/

2017-04-28 21:34 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build1056/profiles/contrib/openy/build/reports/behat

2017-04-28 23:10 UTC, dave-the-brave commented
@Sanchiz I have made these changes

> On Apr 28, 2017, at 1:58 PM, Alexander Schedrov <notifications@github.com> wrote:
> 
> @Sanchiz requested changes on this pull request.
> 
> In themes/openy_themes/openy_rose/color/color.inc <https://github.com/ymcatwincities/openy/pull/286#discussion_r114018435>:
> 
> > @@ -75,7 +75,7 @@ $info = array(
>        ),
>      ),
>      'endeavour' => array(
> -      'title' => t('Endeavor Blue'),
> +      'title' => t('Endeavour'),
> Please revert back.
> 
> In themes/openy_themes/openy_rose/color/color.inc <https://github.com/ymcatwincities/openy/pull/286#discussion_r114018444>:
> 
> > @@ -41,7 +41,7 @@ $info = array(
>    // Pre-defined color schemes.
>    'schemes' => array(
>      'default' => array(
> -      'title' => t('Blue sky (default)'),
> +      'title' => t('Lochmara (default)'),
> Please revert back.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ymcatwincities/openy/pull/286#pullrequestreview-35460204>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ADN83fyyMWG_ct4gnA9pMJFn-5a9YDjrks5r0lLvgaJpZM4M3XZp>.
>

2017-04-28 23:16 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build1057 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1057 |
| Installation process | http://install.openy-dev.ffwua.com/build1057/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1057/

2017-04-28 23:23 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build1057/profiles/contrib/openy/build/reports/behat

2017-05-08 14:55 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1116 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1116 |
| Installation process | http://install.openy-dev.ffwua.com/build1116/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1116/

2017-05-08 15:03 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1116/profiles/contrib/openy/build/reports/behat

2017-05-08 15:05 UTC, ygerasimov commented
I was able to add webform as a paragraph https://monosnap.com/file/NOwnLU6luF3MwQQyLogAO47EejWxEL.

Also I can see my submission https://monosnap.com/file/6ugyw6tehoQTwCpAZ5pnN0khIG7Vhk

2017-05-09 13:42 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1133 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1133 |
| Installation process | http://install.openy-dev.ffwua.com/build1133/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1133/

2017-05-09 13:51 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1133/profiles/contrib/openy/build/reports/behat

2017-05-10 14:40 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1142 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1142 |
| Installation process | http://install.openy-dev.ffwua.com/build1142/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1142/

2017-05-10 14:54 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1142/profiles/contrib/openy/build/reports/behat

2017-05-11 14:26 UTC, alexschedrov submitted a review, later dismissed

2017-05-11 14:26 UTC, Sanchiz commented on modules/openy_features/openy_prgf/config/install/core.entity_form_display.paragraph.webform.default.yml
> +langcode: en
All configs that are related to new paragraph should live in separate submodule. See this as example https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_prgf/modules

2017-05-11 14:26 UTC, Sanchiz commented on modules/openy_features/openy_prgf/openy_prgf.install
> +}
This update should live in paragraph module. See this as example https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_prgf/modules

2017-05-11 14:26 UTC, Sanchiz commented on modules/openy_features/openy_webform_demo/config/install/webform.webform.demo_form.yml
> +langcode: en
This form should be treated as demo content. It should live in appropriate submodule(https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_demo_content/modules) and should be enabled during installation.

2017-05-11 14:26 UTC, Sanchiz commented on openy.install
> +  \Drupal::service('module_installer')->install(['webform', 'webform_ui', 'captcha', 'image_captcha', 'recaptcha']);
+ new module with paragraph.

2017-05-11 14:27 UTC, Sanchiz commented
retest this please

2017-05-11 14:38 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1159 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1159 |
| Installation process | http://install.openy-dev.ffwua.com/build1159/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1159/

2017-05-11 14:49 UTC, Sanchiz commented
1. Webform is not available on upgrade path environment
![image](https://cloud.githubusercontent.com/assets/1316234/25955531/333fdc4c-3672-11e7-82e5-8574b0f7ad42.png)

2017-05-11 15:00 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1159/profiles/contrib/openy/build/reports/behat

2017-05-17 14:32 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1208 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1208 |
| Installation process | http://install.openy-dev.ffwua.com/build1208/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1208/

2017-05-17 14:49 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1208/profiles/contrib/openy/build/reports/behat

2017-05-17 16:05 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1211 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1211 |
| Installation process | http://install.openy-dev.ffwua.com/build1211/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1211/

2017-05-17 16:18 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1212 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1212 |
| Installation process | http://install.openy-dev.ffwua.com/build1212/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1212/

2017-05-17 18:47 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1211/profiles/contrib/openy/build/reports/behat

2017-05-17 18:48 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1212/profiles/contrib/openy/build/reports/behat

2017-05-17 20:36 UTC, ygerasimov commented
retest this please

2017-05-18 14:37 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1218 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1218 |
| Installation process | http://install.openy-dev.ffwua.com/build1218/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1218/

2017-05-18 14:59 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1218/profiles/contrib/openy/build/reports/behat

2017-05-18 16:36 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1223 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1223 |
| Installation process | http://install.openy-dev.ffwua.com/build1223/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1223/

2017-05-18 16:49 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1223/profiles/contrib/openy/build/reports/behat

2017-05-19 10:43 UTC, Sanchiz commented
retest this please

2017-05-19 10:54 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1228 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1228 |
| Installation process | http://install.openy-dev.ffwua.com/build1228/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1228/

2017-05-19 11:05 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1228/profiles/contrib/openy/build/reports/behat

2017-05-19 12:00 UTC, alexschedrov requested changes

2017-05-19 12:00 UTC, Sanchiz commented on docs/Content structure/Paragraphs/Webform.md
> +| Embedded Webform | field\_webform_webform | No |Embedded webform entityreference (select). Single value. |
Let's rename to "field_prgf_webform" to follow naming convention.

2017-05-19 12:06 UTC, Sanchiz commented
1. I think field label is supposed to be hidden
![image](https://cloud.githubusercontent.com/assets/1316234/26246802/b1936ee2-3ca3-11e7-9485-4f5793def468.png)

![image](https://cloud.githubusercontent.com/assets/1316234/26246809/b5f4988a-3ca3-11e7-8917-66a60ca95cc1.png)

2. Can we adjust spacing to have it match to elements above?
![image](https://cloud.githubusercontent.com/assets/1316234/26246822/c1f2e6b4-3ca3-11e7-801b-0621640c0cde.png)

3. According to naming conventiong this field should have name "field_prgf_webform"
![image](https://cloud.githubusercontent.com/assets/1316234/26246849/d4d3acc8-3ca3-11e7-9998-2be9dac6e7a1.png)

2017-05-19 12:22 UTC, Sanchiz commented
@ygerasimov what do you think about having reCaptcha as captcha by default?

2017-05-19 15:47 UTC, dave-the-brave commented
Recaptcha is default if the user adds their Recaptcha details during installation. 

> On May 19, 2017, at 5:22 AM, Alexander Schedrov <notifications@github.com> wrote:
> 
> @ygerasimov <https://github.com/ygerasimov> what do you think about having reCaptcha as captcha by default?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ymcatwincities/openy/pull/286#issuecomment-302688492>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ADN83a2RHnkrUuvHtkC7zKnILuBx4CtVks5r7YmPgaJpZM4M3XZp>.
>

2017-05-19 23:04 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1241 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1241 |
| Installation process | http://install.openy-dev.ffwua.com/build1241/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1241/

2017-05-19 23:14 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1242 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1242 |
| Installation process | http://install.openy-dev.ffwua.com/build1242/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1242/

2017-05-19 23:14 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1241/profiles/contrib/openy/build/reports/behat

2017-05-19 23:21 UTC, dave-the-brave commented
Please retest

2017-05-19 23:24 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1242/profiles/contrib/openy/build/reports/behat

2017-05-19 23:26 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1243 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1243 |
| Installation process | http://install.openy-dev.ffwua.com/build1243/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1243/

2017-05-19 23:36 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1243/profiles/contrib/openy/build/reports/behat

2017-05-24 13:12 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1259 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1259 |
| Installation process | http://install.openy-dev.ffwua.com/build1259/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1259/

2017-05-24 13:26 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1259/profiles/contrib/openy/build/reports/behat

2017-05-24 14:07 UTC, alexschedrov approved these changes
Approved.

2017-05-24 14:08 UTC, alexschedrov requested changes

2017-05-24 14:08 UTC, Sanchiz commented on composer.json
> +        "drupal/recaptcha": "^2.2"
Comma is missed at the end of the line. Please add comma and re-generate `composer.lock`.

2017-05-24 15:04 UTC, alexschedrov approved these changes
Approved.

2017-05-24 15:04 UTC, merged

2017-05-24 15:13 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1262 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1262 |
| Installation process | http://install.openy-dev.ffwua.com/build1262/install.php |

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1263/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #286 of commit 6015c48d222612457a0d0e09b129eb3e59c6b87b automatically merged.
GitHub pull request #286 of commit 6015c48d222612457a0d0e09b129eb3e59c6b87b automatically merged.
GitHub pull request #286 of commit 6015c48d222612457a0d0e09b129eb3e59c6b87b automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1257759462427679093.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git7190102485337262581.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/286/merge^{commit} # timeout=10
FATAL: Command "git rev-parse origin/pr/286/merge^{commit}" returned status code 128:
stdout: origin/pr/286/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/286/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse origin/pr/286/merge^{commit}" returned status code 128:
stdout: origin/pr/286/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/286/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1576)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1233)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1245)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:607)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:85)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:934)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1044)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

2017-05-24 15:13 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-05-24 15:13 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-05-24 15:13 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.