[OYPD-XXX] Embedded GroupEx Pro Schedule
ymcatwincities/openy pull request #290
Opened 2017-04-11 15:09 UTC by duozersk

Jira issue: https://propeople-us.atlassian.net/browse/YLI-141

Upgrade path needs work?

Steps to review:
- [ ] login as admin
- [ ] go to edit some landing page, like ```/join```
- [ ] verify you can add "Embedded GroupEx Pro Schedule" paragraph to the "CONTENT AREA" - add it there
- [ ] verify you don't have this paragraph in "HEADER AREA" and "BOTTOM AREA"
- [ ] save the landing page
- [ ] view it and verify you see the added paragraph like on the screen shot below:
![screen shot 2017-04-11 at 18 06 19](https://cloud.githubusercontent.com/assets/2128648/24916116/ec9052e2-1ee1-11e7-85b5-5c96b4e6b5ee.png)

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-04-11 15:14 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build915 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build915 |
| Installation process | http://install.openy-dev.ffwua.com/build915/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/915/

2017-04-11 15:19 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build915/profiles/contrib/openy/build/reports/behat

2017-04-11 15:42 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build916 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build916 |
| Installation process | http://install.openy-dev.ffwua.com/build916/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/916/

2017-04-11 15:48 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build917 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build917 |
| Installation process | http://install.openy-dev.ffwua.com/build917/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/917/

2017-04-11 15:49 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build916/profiles/contrib/openy/build/reports/behat

2017-04-11 15:54 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build917/profiles/contrib/openy/build/reports/behat

2017-04-11 16:27 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy-dev.ffwua.com/build919 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build919 |
| Installation process | http://install.openy-dev.ffwua.com/build919/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/919/

2017-04-11 16:31 UTC, ddrozdik requested changes

2017-04-11 16:31 UTC, ddrozdik commented on modules/custom/embedded_groupexpro_schedule/src/Plugin/Block/EmbeddedGroupExProScheduleBlock.php
> +      $config['account'] = 611;
We should not have account here or should use not related to YMCA, maybe demo content. Let's review account 1

2017-04-11 16:33 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build919/profiles/contrib/openy/build/reports/behat

2017-04-11 16:34 UTC, ddrozdik commented on modules/custom/embedded_groupexpro_schedule/src/Plugin/Block/EmbeddedGroupExProScheduleBlock.php
> +      $config['account'] = 611;
Or we should provide a field, which will allow overriding account

2017-04-12 09:42 UTC, duozersk commented on modules/custom/embedded_groupexpro_schedule/src/Plugin/Block/EmbeddedGroupExProScheduleBlock.php
> +      $config['account'] = 611;
We do have the block configuration form with account textfield - it just doesn't save the values.

2017-05-05 13:11 UTC, Sanchiz commented
retest this please

2017-05-05 13:12 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/1104/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #290 of commit 866e341cda78ea3238dc7b6fdca579feb33c3662.
GitHub pull request #290 of commit 866e341cda78ea3238dc7b6fdca579feb33c3662.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5434677729207330292.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5917696106948764398.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse 866e341cda78ea3238dc7b6fdca579feb33c3662^{commit} # timeout=10
 > git branch -a --contains 866e341cda78ea3238dc7b6fdca579feb33c3662 # timeout=10
 > git rev-parse remotes/origin/pr/290/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/290/merge^{commit} # timeout=10
Checking out Revision 866e341cda78ea3238dc7b6fdca579feb33c3662 (origin/pr/290/head, origin/pr/290/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 866e341cda78ea3238dc7b6fdca579feb33c3662
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/hudson4755570605843439946.sh
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm
+ git pull
Already up-to-date.
[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory2339208789665781313.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1104 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace/vm/cibox/jobs/build.yml -i /tmp/inventory7433660780944904354.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace -e build_number=1104 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace] $ ansible-playbook /var/www/build1104/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1104 -e drupal_folder=/var/www/build1104 -e site_url=http://openy-dev.ffwua.com/build1104 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["install_profile"]', 'value': u'openy'})
skipping: [localhost] => (item={'status': True, 'name': '$settings["file_public_path"]', 'value': u'sites/default/files'})
skipping: [ [...]

2017-05-12 09:05 UTC, Sanchiz commented
Work is continued in #290.

2017-05-12 09:05 UTC, closed without merging