[OYPD-408] Anonymous should not see Session, Alert, Activity, or Memb…
ymcatwincities/openy pull request #351
Opened 2017-05-11 12:52 UTC by Kerby70

…ership pages; and should only see Branch pages that are not coming soon.

Make sure these boxes are checked before asking for review of your pull request - thank you!

- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes.
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there.
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

2017-05-11 13:02 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1155 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1155 |
| Installation process | http://install.openy-dev.ffwua.com/build1155/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1155/

2017-05-11 13:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1155/profiles/contrib/openy/build/reports/behat

2017-05-11 13:20 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1156 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1156 |
| Installation process | http://install.openy-dev.ffwua.com/build1156/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1156/

2017-05-11 13:34 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1157 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1157 |
| Installation process | http://install.openy-dev.ffwua.com/build1157/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1157/

2017-05-11 13:34 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1156/profiles/contrib/openy/build/reports/behat

2017-05-11 13:46 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1157/profiles/contrib/openy/build/reports/behat

2017-05-12 06:15 UTC, ivan-berezhnov commented
retest this please

2017-05-12 06:24 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1163 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1163 |
| Installation process | http://install.openy-dev.ffwua.com/build1163/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1163/

2017-05-12 06:34 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1163/profiles/contrib/openy/build/reports/behat

2017-05-12 08:44 UTC, alexschedrov requested changes

2017-05-12 08:44 UTC, Sanchiz commented on composer.json
> +        "drupal/rabbit_hole": "1.x-dev"
In drush-make file we have `1.0-beta3`, but here `1.x-dev`.

2017-05-12 08:44 UTC, Sanchiz commented on openy.info.yml
> +  - rh_node
We should explicitly enable those modules in hook_update in `openy.install`.

2017-05-12 08:54 UTC, Sanchiz commented
1. This functionality doesn't work on upgrade path environment.
Prlbably because rh_node module is not enabled.
![image](https://cloud.githubusercontent.com/assets/1316234/25990798/b4ab81a4-3709-11e7-8517-979dfa854402.png)

<img width="1251" alt="screen shot 2017-05-12 at 11 54 31 am" src="https://cloud.githubusercontent.com/assets/1316234/25990817/cb9c5c8a-3709-11e7-9631-b60ea2c04f9f.png">

2017-05-12 13:01 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1168 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1168 |
| Installation process | http://install.openy-dev.ffwua.com/build1168/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1168/

2017-05-12 13:18 UTC, bjwilkins commented
Behat test results file URL: http://ci.openymca.org/build1168/profiles/contrib/openy/build/reports/behat

2017-05-12 13:21 UTC, alexschedrov approved these changes
Approved.

2017-05-12 13:22 UTC, merged