[OYPD-410-354] Add some basic styles for the 404 and 403 pages.
ymcatwincities/openy pull request #368
Opened 2017-05-16 22:09 UTC by ivan-berezhnov

Issue #354 
Drupal.org issue: 

Steps
- [ ] go to [sitename]/about1111
- [ ] vefify 404 page have style as here https://cloud.githubusercontent.com/assets/1316234/26104495/c5e865aa-3a46-11e7-9d31-b65184def5a0.png

2017-05-16 22:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1196 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1196 |
| Installation process | http://install.openy-dev.ffwua.com/build1196/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1196/

2017-05-16 22:26 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1196/profiles/contrib/openy/build/reports/behat

2017-05-17 08:55 UTC, Sanchiz commented
retest this please

2017-05-17 09:00 UTC, alexschedrov requested changes

2017-05-17 09:00 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/page/page--403.html.twig
> +        <h1>403 Access Denied</h1>
Should be translatable.

2017-05-17 09:00 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/page/page--403.html.twig
> +        <p>You are not authorized to access this page.</p>
Should be translatable.

2017-05-17 09:00 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/page/page--404.html.twig
> +        <h1>404 Page not found</h1>
Should be translatable.

2017-05-17 09:00 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/page/page--404.html.twig
> +        <p>Oops! The page that you're looking for was not found.</p>
Should be translatable.

2017-05-17 09:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1199 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1199 |
| Installation process | http://install.openy-dev.ffwua.com/build1199/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1199/

2017-05-17 09:24 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1199/profiles/contrib/openy/build/reports/behat

2017-05-17 09:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1200 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1200 |
| Installation process | http://install.openy-dev.ffwua.com/build1200/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1200/

2017-05-17 09:59 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1200/profiles/contrib/openy/build/reports/behat

2017-05-17 12:25 UTC, alexschedrov approved these changes
Approved.

2017-05-17 12:25 UTC, merged