[Minor-Fix][337] Admin menu in header template.
ymcatwincities/openy pull request #391
Opened 2017-05-23 16:09 UTC by ivan-berezhnov

Issue #337 
Drupal.org issue: 

Steps:
- [ ] log in as admin
- [ ] go to page [sitename]/header.html
- [ ] verify you don't see admin menu
- [ ] go to page [sitename]/footer.html
- [ ] verify you don't see admin menu
- [ ] go to front page or any page 
- [ ] verify you can see admin menu

2017-05-23 16:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1249 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1249 |
| Installation process | http://install.openy-dev.ffwua.com/build1249/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1249/

2017-05-23 16:25 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1249/profiles/contrib/openy/build/reports/behat

2017-05-24 10:17 UTC, Sanchiz commented
retest this please

2017-05-24 10:31 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1255 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1255 |
| Installation process | http://install.openy-dev.ffwua.com/build1255/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1255/

2017-05-24 10:38 UTC, alexschedrov requested changes

2017-05-24 10:38 UTC, Sanchiz commented on modules/custom/openy_hf/openy_hf.module
> +    unset($variables['page_top']['toolbar']);
Let's wrap into `if` condition. We can't garantee that this element will be always available.
```php
if (isset($variables['page_top']['toolbar'])) {
  unset($variables['page_top']['toolbar']);
}
```

2017-05-24 10:43 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1255/profiles/contrib/openy/build/reports/behat

2017-05-24 12:06 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1258 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1258 |
| Installation process | http://install.openy-dev.ffwua.com/build1258/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1258/

2017-05-24 12:13 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1258/profiles/contrib/openy/build/reports/behat

2017-05-24 13:09 UTC, alexschedrov approved these changes
Approved.

2017-05-24 13:09 UTC, merged