[MInor-Fix][366] Add textfield to the "Small Banner”.
ymcatwincities/openy pull request #393
Opened 2017-05-23 20:52 UTC by ivan-berezhnov

Issue #366 
Drupal.org issue:

Steps:
- [ ] log in as admin
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

2017-05-23 20:59 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1252 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1252 |
| Installation process | http://install.openy-dev.ffwua.com/build1252/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1252/

2017-05-23 21:06 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1252/profiles/contrib/openy/build/reports/behat

2017-05-31 07:25 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1311 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1311 |
| Installation process | http://install.openy-dev.ffwua.com/build1311/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1311/

2017-05-31 07:36 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1311/profiles/contrib/openy/build/reports/behat

2017-05-31 09:22 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1314 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1314 |
| Installation process | http://install.openy-dev.ffwua.com/build1314/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1314/

2017-05-31 09:34 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1314/profiles/contrib/openy/build/reports/behat

2017-05-31 10:03 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1315 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1315 |
| Installation process | http://install.openy-dev.ffwua.com/build1315/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1315/

2017-05-31 10:15 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1315/profiles/contrib/openy/build/reports/behat

2017-05-31 10:29 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1316 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1316 |
| Installation process | http://install.openy-dev.ffwua.com/build1316/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1316/

2017-06-01 08:30 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1327 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1327 |
| Installation process | http://install.openy-dev.ffwua.com/build1327/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1327/

2017-06-01 08:39 UTC, ddrozdik approved these changes

2017-06-01 08:42 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1327/profiles/contrib/openy/build/reports/behat

2017-06-01 09:38 UTC, alexschedrov requested changes

2017-06-01 09:38 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--small-banner.html.twig
> +          {% if content.field_prgf_description.0['#text'] is not empty %}
We should set variable like here https://github.com/ymcatwincities/openy/pull/393/files#diff-099c1735c766cb3803f7f2f2bca786d4R48. We should never use array properties in twig templates. If we need to do this, we should define new variables above and then use them in conditions.

2017-06-01 10:33 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1328 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1328 |
| Installation process | http://install.openy-dev.ffwua.com/build1328/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1328/

2017-06-01 10:44 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1328/profiles/contrib/openy/build/reports/behat

2017-06-02 09:59 UTC, Sanchiz commented
retest this please

2017-06-02 10:01 UTC, alexschedrov requested changes

2017-06-02 10:01 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--small-banner.html.twig
> +{% set description_text = content.field_prgf_description.0['#text'] %}
That's better, however `content.field_prgf_description.0['#text']` may be empty from the begining.

We should add condition here, when we setup description text value. `description_text` should be just like a flag, `true` or `false`.

2017-06-02 10:12 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1335 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1335 |
| Installation process | http://install.openy-dev.ffwua.com/build1335/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1335/

2017-06-02 10:23 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1335/profiles/contrib/openy/build/reports/behat

2017-06-02 13:27 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1342 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1342 |
| Installation process | http://install.openy-dev.ffwua.com/build1342/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1342/

2017-06-02 13:39 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1342/profiles/contrib/openy/build/reports/behat

2017-06-06 07:15 UTC, Sanchiz commented
retest this please

2017-06-06 07:28 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1345 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1345 |
| Installation process | http://install.openy-dev.ffwua.com/build1345/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1345/

2017-06-06 07:40 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1345/profiles/contrib/openy/build/reports/behat

2017-06-06 07:50 UTC, alexschedrov approved these changes
Approved.

2017-06-06 07:51 UTC, merged