[Minor-Fix][362] Several galleries per page.
ymcatwincities/openy pull request #399
Opened 2017-05-25 11:34 UTC by ivan-berezhnov

Issue #362
Drupal.org issue: https://www.drupal.org/node/2871505

Steps:
- [ ] login as admin
- [ ] go to any page
- [ ] add two or more galleries. to the page and to one section
- [ ] click on '<' or '>' in the second gallery
- [ ] verify slide change for the second gallery

2017-05-25 11:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1271 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1271 |
| Installation process | http://install.openy-dev.ffwua.com/build1271/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1271/

2017-05-25 12:00 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1271/profiles/contrib/openy/build/reports/behat

2017-05-25 12:03 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1272 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1272 |
| Installation process | http://install.openy-dev.ffwua.com/build1272/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1272/

2017-05-25 12:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1272/profiles/contrib/openy/build/reports/behat

2017-05-25 12:49 UTC, alexschedrov requested changes

2017-05-25 12:49 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.module
> +
Please remove empty line.

2017-05-25 12:49 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.libraries.yml
> +    - core/jquery
Please add endline.

2017-05-25 12:49 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/js/openy_prgf_gallery_alert.js
> +})(jQuery);
Please add endline.

2017-05-25 13:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1273 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1273 |
| Installation process | http://install.openy-dev.ffwua.com/build1273/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1273/

2017-05-25 13:31 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1273/profiles/contrib/openy/build/reports/behat

2017-05-25 14:11 UTC, alexschedrov requested changes

2017-05-25 14:11 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.module
> +  $variables['#attached']['library'][] = 'openy_prgf_gallery/gallery_alert';
What if node doesn't have this paragraph at all? This function will attache library to every single node. Let's find a bettew way of attaching libraries.

2017-05-29 21:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1296 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1296 |
| Installation process | http://install.openy-dev.ffwua.com/build1296/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1296/

2017-05-29 21:23 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1296/profiles/contrib/openy/build/reports/behat

2017-05-30 07:50 UTC, ivan-berezhnov commented
retest this please

2017-05-30 07:52 UTC, ivan-berezhnov commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.libraries.yml
> +    - core/jquery
Added empty end line.

2017-05-30 07:52 UTC, ivan-berezhnov commented on modules/openy_features/openy_prgf/modules/openy_prgf_gallery/js/openy_prgf_gallery_alert.js
> +})(jQuery);
Added empty end line.

2017-05-30 08:03 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1298 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1298 |
| Installation process | http://install.openy-dev.ffwua.com/build1298/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1298/

2017-05-30 08:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1298/profiles/contrib/openy/build/reports/behat

2017-05-30 12:56 UTC, alexschedrov approved these changes
Approved.

2017-05-30 12:57 UTC, merged