if there are more then 3 items in a camp menu that as the screen size gets smaller menu items disappear #196
ymcatwincities/openy pull request #447
Opened 2017-06-06 12:41 UTC by tolichka

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

1) Go to camps/camp-orkila or any other camp.
on mobile you should be able to drag camp menu to left and right.

2017-06-06 12:54 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1349 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1349 |
| Installation process | http://install.openy-dev.ffwua.com/build1349/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1349/

2017-06-06 13:06 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1349/profiles/contrib/openy/build/reports/behat

2017-06-06 14:51 UTC, alexschedrov requested changes

2017-06-06 14:51 UTC, Sanchiz commented on themes/openy_themes/openy_rose/scripts/openy_rose.js
> +  Drupal.behaviors.scrollableList = {
Default indentation in Drupal should be 2 spaces. We have 4 here.

2017-06-06 15:24 UTC, tolichka commented on themes/openy_themes/openy_rose/scripts/openy_rose.js
> +  Drupal.behaviors.scrollableList = {
Coding styles are done for all file.

2017-06-06 15:35 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1350 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1350 |
| Installation process | http://install.openy-dev.ffwua.com/build1350/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1350/

2017-06-06 15:44 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1350/profiles/contrib/openy/build/reports/behat

2017-06-07 06:39 UTC, Sanchiz commented
retest this please

2017-06-07 06:53 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1358 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1358 |
| Installation process | http://install.openy-dev.ffwua.com/build1358/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1358/

2017-06-07 06:55 UTC, alexschedrov approved these changes

2017-06-07 06:55 UTC, merged

2017-06-07 07:05 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1358/profiles/contrib/openy/build/reports/behat

2017-06-07 07:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1359 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1359 |
| Installation process | http://install.openy-dev.ffwua.com/build1359/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1359/

2017-06-07 07:28 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1359/profiles/contrib/openy/build/reports/behat