[OYPD-466] YouTube icon in the footer is not announced needs alt tesxt added.
ymcatwincities/openy pull request #449
Opened 2017-06-06 15:42 UTC by ivan-berezhnov

Issue: https://propeople-us.atlassian.net/browse/OYPD-466
Drupal.org issue:

Steps for review:
- [ ] go to any page
- [ ] scroll down and find the footer social icons
- [ ] verify youtube icon looks as a link

2017-06-06 15:56 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1351 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1351 |
| Installation process | http://install.openy-dev.ffwua.com/build1351/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1351/

2017-06-06 16:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1351/profiles/contrib/openy/build/reports/behat

2017-06-07 06:45 UTC, alexschedrov requested changes

2017-06-07 06:45 UTC, Sanchiz commented on modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration.block_content_footer.yml
> +        	<li><a class="fa fa-youtube" href="#">Youtube</a></li>
This is good catch, however we still have to add `title=""` for all those links.

2017-06-07 10:55 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1364 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1364 |
| Installation process | http://install.openy-dev.ffwua.com/build1364/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1364/

2017-06-07 11:07 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1364/profiles/contrib/openy/build/reports/behat

2017-06-07 12:15 UTC, alexschedrov approved these changes
Approved.

2017-06-07 12:15 UTC, alexschedrov approved these changes

2017-06-07 12:16 UTC, merged