[OYPD-451] Update daxko, & opney_socrates, add openy_prgf_pgm_reg & openy_programs_search with configuration.
ymcatwincities/openy pull request #470
Opened 2017-06-08 20:25 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-06-08 20:39 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1389 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1389 |
| Installation process | http://install.openy-dev.ffwua.com/build1389/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1389/

2017-06-08 20:51 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1389/profiles/contrib/openy/build/reports/behat

2017-06-09 12:25 UTC, Kerby70 commented
retest this please

2017-06-09 12:43 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1396 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1396 |
| Installation process | http://install.openy-dev.ffwua.com/build1396/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1396/

2017-06-09 12:55 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1396/profiles/contrib/openy/build/reports/behat

2017-06-09 14:34 UTC, Sanchiz commented on modules/custom/openy_programs_search/src/DataStorage.php
> +              if ((strpos($program->name, "South Lake Houston") !== FALSE)) {
Potential place to remove. It's hardcoded fr Houston.

2017-06-09 14:34 UTC, Sanchiz commented on modules/custom/openy_programs_search/src/DataStorage.php
> +      $skip_branches = [
Probably should be moved to configuration.

2017-06-09 14:35 UTC, alexschedrov requested changes

2017-06-09 14:35 UTC, Sanchiz commented on docs/Content structure/Paragraphs/Program Registration.md
> +# Program Registration
Let's call in `Program Registration (Daxko)`

2017-06-09 20:20 UTC, Kerby70 commented on modules/custom/openy_programs_search/src/DataStorage.php
> +              if ((strpos($program->name, "South Lake Houston") !== FALSE)) {
Better code comments would help :( All I know is 'South Lake Houston' was being given -10 less weight. I'm guessing the functionality could apply differently for each site, maybe needing multiple programs to have different weight adjustments. But this just subtracts 10 it doesn't pin the item to the top, it's a bit confusing.

2017-06-09 20:35 UTC, Kerby70 commented on modules/custom/openy_programs_search/config/install/openy_programs_search.settings.yml
> +get_map_categories_by_branch_path: ''
@Sanchiz Should I go ahead and set these to the assumed defaults given in the form descriptions?

2017-06-12 11:24 UTC, Sanchiz commented on modules/custom/openy_programs_search/src/DataStorage.php
> +              if ((strpos($program->name, "South Lake Houston") !== FALSE)) {
Let's keep as is and then, once we have time, we can make this as enhancement.

2017-06-12 11:25 UTC, Sanchiz commented on modules/custom/openy_programs_search/config/install/openy_programs_search.settings.yml
> +get_map_categories_by_branch_path: ''
@Kerby70 Please clarify this. I'm not sure that I quite get that.

2017-06-13 16:21 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1520 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1520 |
| Installation process | http://install.openy-dev.ffwua.com/build1520/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1520/

2017-06-13 16:30 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1520/profiles/contrib/openy/build/reports/behat

2017-06-13 18:50 UTC, Kerby70 commented
After looking at the work on the GroupExPro Schedules Block I now understand why the field was visible on the form display and this should be restored.

2017-06-15 17:34 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1588 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1588 |
| Installation process | http://install.openy-dev.ffwua.com/build1588/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1588/

2017-06-15 17:34 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1588/profiles/contrib/openy/build/reports/behat

2017-06-15 17:49 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1589 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1589 |
| Installation process | http://install.openy-dev.ffwua.com/build1589/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1589/

2017-06-15 17:50 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1589/profiles/contrib/openy/build/reports/behat

2017-06-15 18:48 UTC, Kerby70 commented
retest this please

2017-06-15 19:02 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1591 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1591 |
| Installation process | http://install.openy-dev.ffwua.com/build1591/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1591/

2017-06-15 19:03 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1591/profiles/contrib/openy/build/reports/behat

2017-06-16 13:38 UTC, Kerby70 commented
retest this please

2017-06-16 13:55 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1614 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1614 |
| Installation process | http://install.openy-dev.ffwua.com/build1614/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1614/

2017-06-16 13:58 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1614/profiles/contrib/openy/build/reports/behat

2017-06-19 06:32 UTC, Sanchiz commented
retest this please

2017-06-19 06:56 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1618 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1618 |
| Installation process | http://install.openy-dev.ffwua.com/build1618/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1618/

2017-06-19 07:10 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1618/profiles/contrib/openy/build/reports/behat

2017-06-19 07:17 UTC, Sanchiz commented
1. I'm not able to add paragraph to the page https://screencast.com/t/oj9lz4xjl8
2. Steps for review miss step where we should configure connection to Daxko.

2017-06-19 20:16 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1647 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1647 |
| Installation process | http://install.openy-dev.ffwua.com/build1647/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1647/

2017-06-19 20:29 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1647/profiles/contrib/openy/build/reports/behat

2017-06-20 07:57 UTC, Sanchiz commented
retest this please

2017-06-20 08:07 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1652 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1652 |
| Installation process | http://install.openy-dev.ffwua.com/build1652/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1652/

2017-06-20 08:20 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1652/profiles/contrib/openy/build/reports/behat

2017-06-20 09:43 UTC, Sanchiz commented
1. Update password field from textfield to password field
![image](https://user-images.githubusercontent.com/1316234/27327028-e74f9dbe-55b5-11e7-9579-004c1f762460.png)

2. Please convert to upper case
![image](https://user-images.githubusercontent.com/1316234/27327068-032c5838-55b6-11e7-877a-68c4b660cdac.png)

3. I've specified credentials for Daxko(see comment in JIRA ticket), but paragraph still doesn't work.
Could you please provide credentials in JIRA ticket that work?

2017-06-20 14:53 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1664 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1664 |
| Installation process | http://install.openy-dev.ffwua.com/build1664/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1664/

2017-06-20 14:53 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1664

2017-06-20 15:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1664/profiles/contrib/openy/build/reports/behat

2017-06-21 11:38 UTC, Sanchiz commented
retest this please

2017-06-21 11:54 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1678 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1678 |
| Installation process | http://install.openy-dev.ffwua.com/build1678/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1678/

2017-06-21 11:54 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1678

2017-06-21 12:10 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1678/profiles/contrib/openy/build/reports/behat

2017-06-22 06:38 UTC, Sanchiz commented
retest this please

2017-06-22 06:50 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1683 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1683 |
| Installation process | http://install.openy-dev.ffwua.com/build1683/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1683/

2017-06-22 06:50 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1683

2017-06-22 07:04 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1683/profiles/contrib/openy/build/reports/behat

2017-06-22 08:43 UTC, Sanchiz commented
retest this please

2017-06-22 08:55 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1690 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1690 |
| Installation process | http://install.openy-dev.ffwua.com/build1690/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1690/

2017-06-22 08:55 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1690

2017-06-22 09:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1690/profiles/contrib/openy/build/reports/behat

2017-06-22 09:42 UTC, alexschedrov approved these changes

2017-06-22 09:43 UTC, merged