Codesprint2017
ymcatwincities/openy pull request #519
Opened 2017-06-11 11:38 UTC by dimb

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-06-11 13:16 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-06-11 13:16 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-06-11 13:16 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-06-11 14:50 UTC, ddrozdik commented
ok to test

2017-06-11 15:02 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1490 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1490 |
| Installation process | http://install.openy-dev.ffwua.com/build1490/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1490/

2017-07-05 09:06 UTC, ddrozdik commented
hi @dimb. fo you have any updates???

2017-07-05 09:20 UTC, dimb commented
@ddrozdik Hi! Let me review latest local changes on this and update you about current status and what was missed from requirements in few days.

2017-07-10 09:36 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1840/

**Build Log**
*last 1000 lines*

 ```
[...truncated 2660 lines...]
 create mode 100644 docroot/core/modules/views/tests/src/Functional/Wizard/TaggedWithTest.php
 create mode 100644 docroot/core/modules/views/tests/src/Functional/Wizard/WizardTestBase.php
 create mode 100644 docroot/core/modules/views/tests/src/Kernel/Handler/AreaEmptyTest.php
 create mode 100644 docroot/core/modules/views/tests/src/Kernel/Handler/FieldNumericTest.php
 create mode 100644 docroot/core/modules/views/tests/src/Kernel/Plugin/DisplayExtenderTest.php
 create mode 100644 docroot/core/modules/views/tests/src/Kernel/Plugin/ExposedFormRenderTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/AnalyzeTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/AreaEntityUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/ArgumentValidatorTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/CachedDataUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/CustomBooleanTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DefaultViewsTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayAttachmentTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayCRUDTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayExtenderUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayFeedTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayPathTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DisplayTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/DuplicateTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/FieldUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/FilterBooleanWebTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/FilterNumericWebTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/FilterUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/GroupByTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/HandlerTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/NewViewConfigSchemaTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/OverrideDisplaysTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/QueryTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/RearrangeFieldsTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/RedirectTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/ReportFieldsTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/ReportTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/SettingsTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/StorageTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/StyleTableTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/StyleUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/TokenizeAreaUITest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/TranslatedViewTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/UnsavedPreviewTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/ViewsListTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/WizardTest.php
 delete mode 100644 docroot/core/modules/views_ui/src/Tests/XssTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/AnalyzeTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/AreaEntityUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/ArgumentValidatorTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/CachedDataUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/CustomBooleanTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DefaultViewsTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayAttachmentTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayCRUDTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayExtenderUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayFeedTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayPathTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DisplayTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/DuplicateTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/FieldUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/FilterBooleanWebTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/FilterNumericWebTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/FilterUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/GroupByTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/HandlerTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/NewViewConfigSchemaTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/OverrideDisplaysTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/QueryTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/RearrangeFieldsTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/RedirectTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/ReportFieldsTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/ReportTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/SettingsTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/StorageTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/StyleTableTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/StyleUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/TokenizeAreaUITest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/TranslatedViewTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/UITestBase.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/UnsavedPreviewTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/ViewsListTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/WizardTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/Functional/XssTest.php
 create mode 100644 docroot/core/modules/views_ui/tests/src/FunctionalJavascript/DisplayTest.php
 create mode 100644 docroot/core/tests/Drupal/FunctionalJavascriptTests/Ajax/AjaxFormPageCacheTest.php
 create mode 100644 docroot/core/tests/Drupal/FunctionalTests/Image/ToolkitSetupFormTest.php
 create mode 100644 docroot/core/tests/Drupal/FunctionalTests/Image/ToolkitTest.php
 create mode 100644 docroot/core/tests/Drupal/FunctionalTests/Image/ToolkitTestBase.php
 create mode 100644 docroot/core/tests/Drupal/Tests/Core/Block/BlockManagerTest.php
 create mode 100644 docroot/core/tests/Drupal/Tests/Core/Test/KernelTestBaseTest.php
 create mode 100644 docroot/core/tests/Drupal/Tests/EntityViewTrait.php
 create mode 100644 docroot/core/tests/Drupal/Tests/Traits/Core/GeneratePermutationsTrait.php
 create mode 100644 docroot/devops/HTML_CodeSniffer/.gitignore
 create mode 100644 docroot/devops/HTML_CodeSniffer/Auditor/HTMLCSAudit [...]

2017-07-10 09:47 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1841/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #519 of commit 2bc44c766ef4b8d295738dda4347929f8e502069 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$4.execute(CliGitAPIImpl.java:585)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:442)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1003)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Caused by: hudson.plugins.git.GitException: Command "git init /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode" returned status code 1:
stdout: 
stderr: /var/lib/jenkins/jobs/PR_BUILDER/workspace/sourcecode/.git: No space left on device

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1576)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1572)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1233)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$4.execute(CliGitAPIImpl.java:583)
	... 12 more
ERROR: null
```

2017-07-10 09:49 UTC, ddrozdik commented
retest this please

2017-07-10 09:54 UTC, ddrozdik commented
retest this please

2017-07-14 09:26 UTC, ddrozdik commented
retest this please

2017-07-14 09:38 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1866 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1866 |
| Installation process | http://install.openy-dev.ffwua.com/build1866/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1866/

2017-07-14 09:38 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1866

2017-07-14 09:39 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1866/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1866/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1866/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1866/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1866/blogWCAG2AAhtmlcs.txt

2017-07-14 09:50 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1866/profiles/contrib/openy/build/reports/behat

2017-07-14 10:32 UTC, ddrozdik requested changes
`Unable to install OpenY Node News (experimental) due to unmet dependencies: field.field.node.news.field_news_category (taxonomy.vocabulary.news_category)` - because module with content type configs does not have a module OpenY Taxonomy News Category as a dependency. As a result after installing modules. category field does not have settings and there is no way to select a category

2017-07-14 10:32 UTC, ddrozdik commented on modules/openy_features/openy_prgf/modules/openy_prgf_featured_news/openy_prgf_featured_news.info.yml
> +name: 'OpenY paragraph featured news posts (Experimental)'
Remove `(Experimental)` from module name here and in other modules.
Instead add package - `package: OpenY (Experimental)` to all modules

2017-07-14 10:32 UTC, ddrozdik commented on modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.info.yml
> +dependencies:
this module should not have a dependency to openY modules like `openy_loc_branch`, `openy_loc_camp`, `openy_txnm_color`, `openy_txnm_blog_category`

2017-07-14 10:32 UTC, ddrozdik commented on modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.install
> +<?php
No need to add install file if it is empty.

2017-07-14 10:32 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/node/node--news--full.html.twig
> +</div>
each file should have an empty line in the end

2017-07-14 11:09 UTC, ddrozdik commented
News Posts Listing - does not have a title before the filters.
this is how it looks on Blogs - https://monosnap.com/file/W7NZRnWzlOZLaeQr5Pcvwvsb4IF1KZ
this is how it looks on News - https://monosnap.com/file/so0p7bit2nT6gSgTQremZokjIxPwzc

2017-07-16 08:51 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1873 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1873 |
| Installation process | http://install.openy-dev.ffwua.com/build1873/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1873/

2017-07-16 08:51 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1873

2017-07-16 08:51 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1873/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1873/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1873/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1873/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1873/blogWCAG2AAhtmlcs.txt

2017-07-16 09:03 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1873/profiles/contrib/openy/build/reports/behat

2017-07-16 09:06 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1874 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1874 |
| Installation process | http://install.openy-dev.ffwua.com/build1874/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1874/

2017-07-16 09:06 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1874

2017-07-16 09:07 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1874/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1874/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1874/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1874/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1874/blogWCAG2AAhtmlcs.txt

2017-07-16 09:15 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1874/profiles/contrib/openy/build/reports/behat

2017-07-16 09:42 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1875 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1875 |
| Installation process | http://install.openy-dev.ffwua.com/build1875/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1875/

2017-07-16 09:42 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1875

2017-07-16 09:43 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1875/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1875/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1875/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1875/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1875/blogWCAG2AAhtmlcs.txt

2017-07-16 09:54 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1875/profiles/contrib/openy/build/reports/behat

2017-07-16 11:42 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1877 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1877 |
| Installation process | http://install.openy-dev.ffwua.com/build1877/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1877/

2017-07-16 11:42 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1877

2017-07-16 11:43 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1877/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1877/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1877/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1877/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1877/blogWCAG2AAhtmlcs.txt

2017-07-16 11:47 UTC, ddrozdik requested changes

2017-07-16 11:47 UTC, ddrozdik commented on modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.install
> +<?php
Please remove empty install file.

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/field/field--node--field-news-category.html.twig
> +            {% endif %}
please reformat this template

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/field/field--node--field-news-related--news.html.twig
> +
please remove one extra empty line

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/node/node--news--teaser.html.twig
> +
remove empty line

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--latest-news-posts-branch.html.twig
> +</div>
empty line in the end of the file is missing

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/views/views-view-unformatted--latest-news-posts--block.html.twig
> +{% extends "views-view-unformatted--listing-news-posts--block.html.twig" %}
empty line in the end of the file is missing

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/views/views-view-unformatted--latest-news-posts-branch--block.html.twig
> +{% extends "views-view-unformatted--listing-news-posts--block.html.twig" %}
empty line in the end of the file is missing

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/views/views-view-unformatted--latest-news-posts-camp--block.html.twig
> +{% extends "views-view-unformatted--listing-news-posts--block.html.twig" %}
empty line in the end of the file is missing

2017-07-16 11:47 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/views/views-view-unformatted--listing-news-posts--block.html.twig
> + </div>
empty line in the end of the file is missing

2017-07-16 11:47 UTC, ddrozdik commented on modules/openy_features/openy_prgf/modules/openy_prgf_featured_news/openy_prgf_featured_news.info.yml
> +description: 'OpenY paragraph featured news posts'
package is missing

2017-07-16 11:54 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1878 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1878 |
| Installation process | http://install.openy-dev.ffwua.com/build1878/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1878/

2017-07-16 11:54 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1878

2017-07-16 11:54 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1878/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1878/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1878/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1878/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1878/blogWCAG2AAhtmlcs.txt

2017-07-16 11:55 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1877/profiles/contrib/openy/build/reports/behat

2017-07-16 12:05 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/field/field--node--field-news-related--news.html.twig
> +'blog-related',
should be `news-related`

2017-07-16 12:05 UTC, ddrozdik commented on themes/openy_themes/openy_rose/templates/node/node--news--teaser.html.twig
> +  'blog-story'
should be `news-story`

2017-07-16 12:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1878/profiles/contrib/openy/build/reports/behat

2017-07-16 15:04 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1880 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1880 |
| Installation process | http://install.openy-dev.ffwua.com/build1880/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1880/

2017-07-16 15:04 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1880

2017-07-16 15:04 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1880/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1880/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1880/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1880/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1880/blogWCAG2AAhtmlcs.txt

2017-07-16 15:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1880/profiles/contrib/openy/build/reports/behat

2017-07-19 19:05 UTC, ddrozdik commented
retest this please

2017-07-19 19:14 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1891 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1891 |
| Installation process | http://install.openy-dev.ffwua.com/build1891/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1891/

2017-07-19 19:14 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1891

2017-07-19 19:14 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1891/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1891/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1891/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1891/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1891/blogWCAG2AAhtmlcs.txt

2017-07-19 19:23 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1891/profiles/contrib/openy/build/reports/behat

2017-07-19 19:43 UTC, ddrozdik commented
- Paragraph "Latest news posts" does not work. 
- Paragraph "Latest news posts (branch)" - title should be changed, see screenshot https://monosnap.com/file/MEOdjN4dgutyfNgvu1qxJiQ1U1E8pl
- Paragraph "Latest news posts (camp)" - title should be changed, see screenshot https://monosnap.com/file/PD6a23nm9Icp9ro6IcUsvPLQPeYUKo
Also, I found that we do not have a paragraph "News Post Listing" like "Blog Post Listing" in OpenY

2017-07-19 19:52 UTC, ddrozdik approved these changes

2017-07-19 19:52 UTC, ddrozdik commented
We will continue work in a new pull request.

2017-07-19 19:53 UTC, merged