Fix480
ymcatwincities/openy pull request #529
Opened 2017-06-11 13:15 UTC by eliasbrat

2017-06-11 13:33 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1470 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1470 |
| Installation process | http://install.openy-dev.ffwua.com/build1470/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1470/

2017-06-11 13:45 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1474 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1474 |
| Installation process | http://install.openy-dev.ffwua.com/build1474/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1474/

2017-06-12 10:55 UTC, hamrant requested changes

2017-06-12 10:55 UTC, hamrant commented on themes/openy_themes/openy_rose/templates/node/node--blog--teaser.html.twig
> +{% set color = content.field_blog_text_color['#items'].entity.field_color.value ? 'color: #' ~ content.field_blog_text_color['#items'].entity.field_color.value ~ ';' : null %}
All changes in themes/openy_themes/openy_rose/templates/node/node--blog--teaser.html.twig not related to current issue, please remove them from PR

2017-06-16 07:30 UTC, Sanchiz commented
This has been merged here #575.

2017-06-16 07:30 UTC, closed without merging