Add descriptions & placeholders to blog posts
ymcatwincities/openy pull request #556
Opened 2017-06-13 14:30 UTC by yasik78

Featured Blog Posts paragraph descriptions & placeholders #484
## Steps for review

- [ ] login as admin
- [ ] Go to /node/add/landing_page
- [ ] Add paragraf block Simple content 
- [ ] Check description for fields and compare with docs.  https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Content%20structure/Paragraphs/Featured%20Blog%20Posts.md

2017-06-13 14:30 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-06-14 07:56 UTC, Sanchiz commented
ok to test

2017-06-14 08:23 UTC, gundevel commented
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1530/

**Build Log**
*last 1000 lines*

 ```
GitHub pull request #556 of commit 6b42b308ee698b3ff2b2e690269786962f992732 automatically merged.
GitHub pull request #556 of commit 6b42b308ee698b3ff2b2e690269786962f992732 automatically merged.
GitHub pull request #556 of commit 6b42b308ee698b3ff2b2e690269786962f992732 automatically merged.
Building in workspace /var/lib/jenkins/jobs/PR_BUILDER/workspace@8
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/ymcatwincities/openy.git
 > git init /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/sourcecode # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git3102259783447826979.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/ymcatwincities/openy.git # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
No valid HEAD. Skipping the resetting
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/ymcatwincities/openy.git
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git1528914065119486361.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/ymcatwincities/openy.git +refs/pull/*:refs/remotes/origin/pr/* # timeout=5
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/556/merge^{commit} # timeout=10
 > git branch -a --contains 30edbcb97598016c876adadbebec1ef54d3bade4 # timeout=10
 > git rev-parse remotes/origin/pr/556/merge^{commit} # timeout=10
Checking out Revision 30edbcb97598016c876adadbebec1ef54d3bade4 (origin/pr/556/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 30edbcb97598016c876adadbebec1ef54d3bade4
First time build. Skipping changelog.
[workspace@8] $ /bin/sh -xe /tmp/hudson7978082977106629130.sh
+ rm -Rf /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm
+ cp -R ../vm /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm
+ cd /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm
+ git pull
Already up-to-date.
[workspace@8] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm/cibox/jobs/deploy_code.yml -i /tmp/inventory3094032667715714484.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace@8 -e build_number=1530 -e server_docroot_folder=/var/www -e deploy_type=local -e profile_source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@8/sourcecode -e source=/var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm/docroot -e profile_destination=profiles/contrib/openy -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Generate commentinfo.md file] ************ 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Make sure folder is not exist] *********** 
ok: [localhost]

TASK: [../custom/cibox-code-deploy | Sync files into docroot] ***************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Sync OpenY profile] ********************** 
changed: [localhost]

TASK: [../custom/cibox-code-deploy | Folder permissions] ********************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=6    changed=4    unreachable=0    failed=0   

[workspace@8] $ ansible-playbook /var/lib/jenkins/jobs/PR_BUILDER/workspace@8/vm/cibox/jobs/build.yml -i /tmp/inventory6535460025958737028.ini -f 5 -e workspace=/var/lib/jenkins/jobs/PR_BUILDER/workspace@8 -e build_number=1530 -e server_docroot_folder=/var/www -e build_folder_prefix=build -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Folder permissions] **************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

[workspace@8] $ ansible-playbook /var/www/build1530/reinstall.yml -f 5 -e php_env_vars=APP_ENV=dev -e mysql_user=root -e mysql_password=root -e mysql_db=drupal1530 -e drupal_folder=/var/www/build1530 -e site_url=http://openy-dev.ffwua.com/build1530 -e pp_environment=default -e run_reinstall=true -i localhost, --connection=local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Include specific variables per environment] **************************** 
ok: [localhost]

TASK: [Getting timestamp for backup] ****************************************** 
skipping: [localhost]

TASK: [Getting name for backup] *********************************************** 
skipping: [localhost]

TASK: [Creating backup folder for environment] ******************************** 
skipping: [localhost]

TASK: [Making regular backup from {{ local_backup_environment }} environment] *** 
skipping: [localhost]

TASK: [Make new backup as latest] ********************************************* 
skipping: [localhost]

TASK: [Set writable cache dir] ************************************************ 
ok: [localhost]

TASK: [Set writable tmp dir] ************************************************** 
changed: [localhost]

TASK: [Set writable backup dir] *********************************************** 
ok: [localhost]

TASK: [Set writable default dir] ********************************************** 
changed: [localhost]

TASK: [Set writable files dir] ************************************************ 
changed: [localhost]

TASK: [Set writable private dir] ********************************************** 
changed: [localhost]

TASK: [Start the MySQL service] *********************************************** 
ok: [localhost]

TASK: [Getting name for settings (WINDOWS)] *********************************** 
skipping: [localhost]

TASK: [Getting name for settings (UNIX)] ************************************** 
skipping: [localhost]

TASK: [Remove settings.php] *************************************************** 
skipping: [localhost]

TASK: [Creating settings.php] ************************************************* 
skipping: [localhost]

TASK: [Adding database variable to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add general pre-settings to settings.php] ****************************** 
skipping: [localhost]

TASK: [Add environment specific pre-settings] ********************************* 
skipping: [localhost] => (item={'status': True, 'name': '$settings["hash_salt"]', 'value': 'g1W4KZgWCeWh7Af9_gSb9D9HOiNaBdWPvQD-8x0yWpcgNpTBppaHR5VNGQBGvh2k8P8uWa1V8w'})
skipping: [localhost] => (item={'status': False, 'name': '$config_directories["staging"]', 'value': 'sites/default/config/staging'})
skipping: [localhost] => (item={'status': True, 'name': '$config_directories["sync"]', 'value': 'sites/default/config/sync'})
skipping: [localhost] => (item={'status': True, 'name': '$settings[" [...]

2017-06-14 09:57 UTC, alexschedrov requested changes

2017-06-14 09:57 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_featured_blogs/config/install/field.field.paragraph.featured_blogs.field_fblog_posts.yml
> +description: 'Multiple values. Reference field to Blog posts.�'
Weird symbol at the end.
![image](https://user-images.githubusercontent.com/1316234/27126699-06f51720-5101-11e7-8ca9-ece7f51782f0.png)

2017-06-14 11:16 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1540 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1540 |
| Installation process | http://install.openy-dev.ffwua.com/build1540/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1540/

2017-06-14 11:30 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1540/profiles/contrib/openy/build/reports/behat

2017-06-14 11:33 UTC, alexschedrov approved these changes

2017-06-14 11:33 UTC, merged