[OYPD-496] Add new theme "Seattle".
ymcatwincities/openy pull request #568
Opened 2017-06-15 11:29 UTC by ivan-berezhnov

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-06-15 11:48 UTC, alexschedrov requested changes

2017-06-15 11:48 UTC, Sanchiz commented on themes/openy_themes/openy_rose/color/color.inc
> +      'title' => t('Blue sky'),
This should be Seattle.

2017-06-15 11:48 UTC, Sanchiz commented on themes/openy_themes/openy_rose/color/color.inc
> +      'title' => t('Seattle (default)'),
This should be Blue Sky.

2017-06-15 11:53 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1581 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1581 |
| Installation process | http://install.openy-dev.ffwua.com/build1581/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1581/

2017-06-15 12:19 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1583 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1583 |
| Installation process | http://install.openy-dev.ffwua.com/build1583/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1583/

2017-06-15 12:36 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1583/profiles/contrib/openy/build/reports/behat

2017-06-15 14:15 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1585 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1585 |
| Installation process | http://install.openy-dev.ffwua.com/build1585/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1585/

2017-06-15 14:29 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1585/profiles/contrib/openy/build/reports/behat

2017-06-16 05:54 UTC, Sanchiz commented
retest this please

2017-06-16 06:19 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1596 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1596 |
| Installation process | http://install.openy-dev.ffwua.com/build1596/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1596/

2017-06-16 06:20 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1596/profiles/contrib/openy/build/reports/behat

2017-06-16 07:17 UTC, Sanchiz commented
Some colors are different. Make sure you've updated demo content to use appropriate colors.
![image](https://user-images.githubusercontent.com/1316234/27216065-cb0ac3a4-527c-11e7-853e-44f7ded43cc5.png)

2017-06-16 10:12 UTC, ivan-berezhnov commented
@Sanchiz https://github.com/ymcatwincities/openy/pull/568#issuecomment-308952692
Yeah, I saw it but I thought it fix subtask. Now I fixed it

2017-06-16 10:24 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1606 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1606 |
| Installation process | http://install.openy-dev.ffwua.com/build1606/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1606/

2017-06-16 10:25 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1606/profiles/contrib/openy/build/reports/behat

2017-06-16 10:35 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1607 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1607 |
| Installation process | http://install.openy-dev.ffwua.com/build1607/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1607/

2017-06-16 10:35 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1607/profiles/contrib/openy/build/reports/behat

2017-06-19 08:27 UTC, ivan-berezhnov commented
retest this please

2017-06-19 08:37 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1622 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1622 |
| Installation process | http://install.openy-dev.ffwua.com/build1622/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1622/

2017-06-19 08:48 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1622/profiles/contrib/openy/build/reports/behat

2017-06-19 11:21 UTC, alexschedrov approved these changes

2017-06-19 11:21 UTC, merged