[OYPD 414] GroupEx Pro API and paragraph
ymcatwincities/openy pull request #574
Opened 2017-06-15 18:33 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-06-15 18:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1590 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1590 |
| Installation process | http://install.openy-dev.ffwua.com/build1590/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1590/

2017-06-15 18:48 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1590/profiles/contrib/openy/build/reports/behat

2017-06-15 19:15 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1592 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1592 |
| Installation process | http://install.openy-dev.ffwua.com/build1592/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1592/

2017-06-15 19:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1592/profiles/contrib/openy/build/reports/behat

2017-06-16 05:55 UTC, Sanchiz commented
retest this please

2017-06-16 07:12 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1600 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1600 |
| Installation process | http://install.openy-dev.ffwua.com/build1600/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1600/

2017-06-16 07:12 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1600/profiles/contrib/openy/build/reports/behat

2017-06-16 07:58 UTC, alexschedrov requested changes

2017-06-16 07:58 UTC, Sanchiz commented on modules/custom/openy_group_schedules/config/install/openy_group_schedules.settings.yml
> +account_id: 621
This should be empty by default.

2017-06-16 07:58 UTC, Sanchiz commented on modules/custom/openy_group_schedules/templates/groupex-individual-location-links.html.twig
> +<h2>Register for Classes and Programs</h2>
I'm wondering if we should have this template here, because it's not related to Personify.

2017-06-16 07:59 UTC, Sanchiz commented
@Kerby70 
1. Please move hardcoded ID to the configuration page.
2. Please updatre steps for review to include configuration page

2017-06-16 09:23 UTC, podarok requested changes
@Sanchiz have a look at suggestions and mark follow-ups. All other would be nice to fix

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/core.entity_form_display.groupex_form_cache.groupex_form_cache.default.yml
> +      placeholder: ''
Let's have placeholders defined

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/core.entity_form_display.groupex_form_cache.groupex_form_cache.default.yml
> +      placeholder: ''
Let's have placeholders defined

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/core.entity_form_display.groupex_form_cache.groupex_form_cache.default.yml
> +      placeholder: ''
Let's have placeholders defined

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/core.entity_form_display.groupex_form_cache.groupex_form_cache.default.yml
> +      placeholder: ''
Let's have placeholders defined

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/core.entity_form_display.groupex_form_cache.groupex_form_cache.default.yml
> +      placeholder: ''
Let's have placeholders defined

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/field.field.groupex_form_cache.groupex_form_cache.field_gfc_options.yml
> +translatable: false
true

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/config/install/field.field.groupex_form_cache.groupex_form_cache.field_gfc_response.yml
> +translatable: false
true

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.links.menu.yml
> +  parent: ymca_alters.admin_config_entities
remove parent to non existent module route, Add parent from core route, please. Somewhere in Services

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.links.menu.yml
> +  parent: ymca_alters.admin_config_entities
remove parent to non existent module route, Add parent from core route, please. Somewhere in Services

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/src/GroupexFormCacheWarmer.php
> +    $this->warm();
Create follow-up to improve this part. We should have default periodicity for the cron run not often than 1h, otherwise we can kill GroupEx with DOS attack

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/openy_group_schedules.info.yml
> +  - daxko:daxko
I'm not sure we have to add daxko dependency here

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/openy_group_schedules.libraries.yml
> +  version: VERSION
let's define version? like 0.1

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/openy_group_schedules.module
> +    'max-age' => 3600,
should be moved to config

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/openy_group_schedules.module
> +    'max-age' => 3600,
should be moved to config

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/openy_group_schedules.module
> +function openy_group_schedules_ymca_sync_description_alter(&$items) {
Looks weird, we have a full control over codebase, can we put description without altering?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Controller/AllSearchResultsController.php
> +    $request = \Drupal::request();
Is it possible to pass request via Dependency Injection?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Controller/AllSearchResultsController.php
> +    $schedule = \Drupal::service('openy_group_schedules.schedule_fetcher')->getSchedule();
Is it possible to pass service via Dependency Injection?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Controller/AllSearchResultsController.php
> +    if (!$empty_results = \Drupal::service('openy_group_schedules.schedule_fetcher')->isEmpty()) {
Is it possible to pass service via Dependency Injection?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Controller/SearchResultsController.php
> +    $request = \Drupal::request();
Is it possible to pass service via Dependency Injection?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Controller/SearchResultsController.php
> +        'max-age' => 3600,
let's move this to config

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexFormBase.php
> +      'max-age' => 3600,
move to config, please

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexFormBase.php
> +      if (count($location) > 4) {
move to config, please

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
> +      if ($site_section = \Drupal::service('pagecontext.service')->getContext()) {
pass via DI?

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
> +    for ($i = 0; $i < 14; $i++) {
14 is a 2 weeks, can we make it in config, we have some requests to change this timeframe

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
> +        'max-age' => 3600,
should be in config

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/Form/GroupexSettingsForm.php
> +      '#title' => $this->t('GroupEx Account ID'),
Let's add description how to get Account ID, link to GroupEx doc would be awesome to have

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
> +    $end_date = DrupalDateTime::createFromTimestamp(REQUEST_TIME + 86400 * 14, $this->timezone);
14 should be config

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/templates/groupex-all-search-results.html.twig
> +<section id="component_160855" class="{{ interval }}-results accessible-buttons" type="ymca_twin_cities_group_ex_search_results">
In case if component_160855 name doesn't exist in css - let's remove it and make less legacy ))))

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/templates/groupex-all-search-results.html.twig
> +<!-- Disabling image logo.
Make it optional via settings or remove old code

2017-06-16 09:23 UTC, podarok commented on modules/custom/openy_group_schedules/templates/groupex-individual-location-links.html.twig
> +<h2>Register for Classes and Programs</h2>
yep, remove it

2017-06-16 09:23 UTC, podarok commented on modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.info.yml
> +  - datalayer
can we remove dependency?

2017-06-16 09:23 UTC, podarok commented on openy.install
> +  \Drupal::service('module_installer')->install([
let's foreach loop install one-by-one not all at once. Saving memory is a must have here

2017-06-16 09:24 UTC, podarok requested changes

2017-06-16 09:24 UTC, podarok commented on docs/Content structure/Paragraphs/Group Schedules.md
> +| Block | field\_prgf_block | Yes | Block reference to the view/block. Should have default value and is configurable in form display. |
modules/custom/openy_group_schedules/assets/endorsed_by_silverfit_sm.png file down below could ve removed, because not used

2017-06-16 15:54 UTC, podarok commented
incorporate https://github.com/propeoplemd/ymcahouston/pull/584/files fix as well

2017-06-19 17:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1644 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1644 |
| Installation process | http://install.openy-dev.ffwua.com/build1644/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1644/

2017-06-19 17:18 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1644/profiles/contrib/openy/build/reports/behat

2017-06-19 19:40 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1645 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1645 |
| Installation process | http://install.openy-dev.ffwua.com/build1645/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1645/

2017-06-19 19:41 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1645/profiles/contrib/openy/build/reports/behat

2017-06-20 07:58 UTC, Sanchiz commented
retest this please

2017-06-20 08:37 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1654 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1654 |
| Installation process | http://install.openy-dev.ffwua.com/build1654/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1654/

2017-06-20 08:38 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1654/profiles/contrib/openy/build/reports/behat

2017-06-20 09:51 UTC, Sanchiz commented
Needs re-roll. Let's get back to this PR once Daxko is merged.

2017-06-22 19:20 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1697 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1697 |
| Installation process | http://install.openy-dev.ffwua.com/build1697/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1697/

2017-06-22 19:20 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1697

2017-06-22 19:28 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1697/profiles/contrib/openy/build/reports/behat

2017-06-23 05:56 UTC, Sanchiz commented
retest this please

2017-06-23 06:07 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1699 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1699 |
| Installation process | http://install.openy-dev.ffwua.com/build1699/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1699/

2017-06-23 06:07 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1699

2017-06-23 06:20 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1699/profiles/contrib/openy/build/reports/behat

2017-06-23 07:10 UTC, Sanchiz commented
1. When I placed block without credentials configured, I've got fatal error. We should just display empty block or something like this.

2. Please move menu item to "Configuration -> Webservices"
![image](https://user-images.githubusercontent.com/1316234/27470304-068480e4-57fc-11e7-8f9d-2bcaa994c988.png)
![image](https://user-images.githubusercontent.com/1316234/27470328-15730bac-57fc-11e7-884b-a9dfd2a52ed5.png)

3. Please rename paragraph to "Group Schedules (GroupEx Pro)"

2017-06-23 19:54 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1713 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1713 |
| Installation process | http://install.openy-dev.ffwua.com/build1713/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1713/

2017-06-23 19:54 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1713

2017-06-23 19:54 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1713

2017-06-23 20:02 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1713/profiles/contrib/openy/build/reports/behat

2017-06-26 09:24 UTC, Sanchiz commented
retest this please

2017-06-26 09:36 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1715 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1715 |
| Installation process | http://install.openy-dev.ffwua.com/build1715/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1715/

2017-06-26 09:36 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1715

2017-06-26 09:36 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1715

2017-06-26 09:50 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1715/profiles/contrib/openy/build/reports/behat

2017-06-26 11:32 UTC, alexschedrov requested changes

2017-06-26 11:32 UTC, Sanchiz commented on modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
> -    if ($this->getRouteMatch()->getRouteName() == 'ymca_frontend.location_schedules') {
Let's leave this code here, but just comment or add FALSE in the condition.

2017-06-26 11:48 UTC, alexschedrov requested changes

2017-06-26 11:48 UTC, Sanchiz commented on modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.info.yml
> +package: YMCA
Package `OpenY`.

2017-06-26 11:48 UTC, Sanchiz commented on modules/custom/openy_group_schedules/openy_group_schedules.info.yml
> +package: OpenY
Package `OpenY`.

2017-06-26 11:48 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.info.yml
> +core: 8.x
Package `OpenY`.

2017-06-26 13:04 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1726 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1726 |
| Installation process | http://install.openy-dev.ffwua.com/build1726/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1726/

2017-06-26 13:04 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1726

2017-06-26 13:04 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1726

2017-06-26 13:46 UTC, Sanchiz commented
1. Still fatal error with component on fresh build with credentials -
 http://ci.openymca.org/build1726/node/15/edit
![image](https://user-images.githubusercontent.com/1316234/27542132-fc3b438a-5a8e-11e7-9b5f-d2d4eeca1493.png)

2.

2017-06-26 16:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1726/profiles/contrib/openy/build/reports/behat

2017-06-27 21:36 UTC, Kerby70 commented
These issues appear to be related. 
https://www.drupal.org/node/2788277
https://www.drupal.org/node/2831521
https://www.drupal.org/node/1928868

`\Drupal\Core\Field\TypedData\FieldItemDataDefinition` assumes it's property `fieldDefinition` is a `\Drupal\Core\Field\FieldDefinitionInterface` while it is not enforced. I am not sure where the fieldDefinition is being set to an array or string but have seen both. This state is not resolved by the patch in https://www.drupal.org/node/2831521, I will test https://www.drupal.org/node/1928868 in the morning.

2017-07-04 12:24 UTC, Sanchiz commented
retest this please

2017-07-04 12:27 UTC, Sanchiz commented
@Kerby70 problem with `Fatal error: Call to a member function getFieldStorageDefinition() on string in /var/www/docroot/core/lib/Drupal/Core/Field/TypedData/FieldItemDataDefinition.php on line 66` has been fixed separately in #649. However this PR still needs work.

2017-07-04 12:28 UTC, alexschedrov approved these changes

2017-07-04 12:36 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1797 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1797 |
| Installation process | http://install.openy-dev.ffwua.com/build1797/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1797/

2017-07-04 12:36 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1797

2017-07-04 12:36 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1797

2017-07-04 12:47 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1797/profiles/contrib/openy/build/reports/behat

2017-07-04 12:49 UTC, Sanchiz commented
1. When I select location, I receive error in JS console(e.g. fatal error somewhere in PHP)
https://user-images.githubusercontent.com/1316234/27830518-77acf5ea-60cf-11e7-884b-023a15907524.png

2. `groupex_form_cache` should be enabled.
https://user-images.githubusercontent.com/1316234/27830522-7b986ca2-60cf-11e7-836d-13f08285974f.png

3. Daxko credentials are not required for GroupExPro component. (I've removed this from steps for review).

2017-07-05 19:51 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1815 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1815 |
| Installation process | http://install.openy-dev.ffwua.com/build1815/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1815/

2017-07-05 19:51 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1815

2017-07-05 19:52 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1815/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1815/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1815/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1815/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1815/blogWCAG2AAhtmlcs.txt

2017-07-05 19:59 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1815/profiles/contrib/openy/build/reports/behat

2017-07-06 19:20 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1821 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1821 |
| Installation process | http://install.openy-dev.ffwua.com/build1821/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1821/

2017-07-06 19:20 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1821

2017-07-06 19:20 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1821/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1821/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1821/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1821/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1821/blogWCAG2AAhtmlcs.txt

2017-07-06 19:28 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1821/profiles/contrib/openy/build/reports/behat

2017-07-06 19:37 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1822 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1822 |
| Installation process | http://install.openy-dev.ffwua.com/build1822/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1822/

2017-07-06 19:37 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1822

2017-07-06 19:38 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1822/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1822/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1822/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1822/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1822/blogWCAG2AAhtmlcs.txt

2017-07-06 19:46 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1822/profiles/contrib/openy/build/reports/behat

2017-07-07 11:00 UTC, Sanchiz commented
retest this please

2017-07-07 11:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1825 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1825 |
| Installation process | http://install.openy-dev.ffwua.com/build1825/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1825/

2017-07-07 11:10 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1825

2017-07-07 11:11 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1825/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1825/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1825/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1825/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1825/blogWCAG2AAhtmlcs.txt

2017-07-07 11:24 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1825/profiles/contrib/openy/build/reports/behat

2017-07-07 11:59 UTC, alexschedrov approved these changes

2017-07-07 12:00 UTC, merged