[OYPD-495] Adding default green focus to links
ymcatwincities/openy pull request #584
Opened 2017-06-19 20:28 UTC by david-hernandez

Check focus of links. This won't change every link, because some places have :focus defined, but this will set the default and will work on the top nav and links like the footer menu.

![screen shot 2017-06-19 at 4 14 32 pm](https://user-images.githubusercontent.com/1504038/27304511-47e1c58a-550c-11e7-99dc-be121408286a.png)
![screen shot 2017-06-19 at 4 14 25 pm](https://user-images.githubusercontent.com/1504038/27304510-47df0de0-550c-11e7-95ed-c816f254185d.png)

2017-06-19 20:39 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1648 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1648 |
| Installation process | http://install.openy-dev.ffwua.com/build1648/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1648/

2017-06-19 20:49 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1648/profiles/contrib/openy/build/reports/behat

2017-06-20 07:58 UTC, Sanchiz commented
retest this please

2017-06-20 08:51 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1655 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1655 |
| Installation process | http://install.openy-dev.ffwua.com/build1655/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1655/

2017-06-20 09:05 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1655/profiles/contrib/openy/build/reports/behat

2017-06-20 09:50 UTC, Sanchiz commented
1. Focus for gallery arrows should be green as well
![image](https://user-images.githubusercontent.com/1316234/27327268-be3163bc-55b6-11e7-986a-c98d990a76dc.png)

2. Buttons focus should be green
![image](https://user-images.githubusercontent.com/1316234/27327302-df33ba74-55b6-11e7-857b-6b0c4477360f.png)

![image](https://user-images.githubusercontent.com/1316234/27327304-e0e0374e-55b6-11e7-94cc-f9aaddbb3904.png)

2017-06-20 09:50 UTC, alexschedrov requested changes

2017-06-20 09:50 UTC, Sanchiz commented on themes/openy_themes/openy_rose/scss/state/_state.scss
> +  outline: 5px auto #69ff00;
Let's move this color to variable.

2017-06-20 13:43 UTC, AlexNetman commented
retest this please

2017-06-20 13:57 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1662 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1662 |
| Installation process | http://install.openy-dev.ffwua.com/build1662/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1662/

2017-06-20 13:57 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1662

2017-06-20 14:13 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1662/profiles/contrib/openy/build/reports/behat

2017-06-20 14:38 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1663 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1663 |
| Installation process | http://install.openy-dev.ffwua.com/build1663/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1663/

2017-06-20 14:38 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1663

2017-06-20 14:54 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1663/profiles/contrib/openy/build/reports/behat

2017-06-20 15:06 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1665 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1665 |
| Installation process | http://install.openy-dev.ffwua.com/build1665/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1665/

2017-06-20 15:06 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1665

2017-06-20 15:12 UTC, AlexNetman commented
![image](https://user-images.githubusercontent.com/4558228/27340374-fcd672d4-55e2-11e7-993b-885d2876bc82.png)
In the latest PR shadowbox was added around light-green outline. It looks good allow us to say that we are having contrast 3:1 for all possible combinations:
![image](https://user-images.githubusercontent.com/4558228/27340347-f068f850-55e2-11e7-8009-6685b9a1e60d.png)

But that brings severe visual issues. When I click on blog title using mouse button:
I see grey shadowbox for a while
![image](https://user-images.githubusercontent.com/4558228/27340617-9dcaa6ba-55e3-11e7-9535-def1410b61ab.png)
And when I click on Logo, I see grey box over it:
![image](https://user-images.githubusercontent.com/4558228/27340702-d62747b6-55e3-11e7-826e-ab7166857df2.png)

2017-06-20 15:23 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1665/profiles/contrib/openy/build/reports/behat

2017-06-20 16:47 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1667 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1667 |
| Installation process | http://install.openy-dev.ffwua.com/build1667/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1667/

2017-06-20 16:47 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1667

2017-06-20 17:02 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1667/profiles/contrib/openy/build/reports/behat

2017-06-21 14:00 UTC, AlexNetman approved these changes

2017-06-22 06:37 UTC, alexschedrov approved these changes

2017-06-22 06:37 UTC, merged