[OYPD-514] Clean up before decoupled tests.
ymcatwincities/openy pull request #625
Opened 2017-06-26 21:47 UTC by ivan-berezhnov

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Jira issue: 
https://propeople-us.atlassian.net/browse/OYPD-514
Drupal.org issue: 

# Steps to review:
- [ ] login as admin
- [ ] go to [sitename]/admin/modules
- [ ] check all OpenY modules in one package 
- [ ] check all OpenY modules have same style for name
- [ ] go to [sitename]/docs/Development/Upgrade%20path.md#modules-version
- [ ] verify section module version removed

2017-06-26 21:56 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1732 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1732 |
| Installation process | http://install.openy-dev.ffwua.com/build1732/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1732/

2017-06-26 21:56 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1732

2017-06-26 21:56 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1732

2017-06-26 22:07 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1732/profiles/contrib/openy/build/reports/behat

2017-06-27 07:02 UTC, ivan-berezhnov commented
retest this please

2017-06-27 08:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1740 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1740 |
| Installation process | http://install.openy-dev.ffwua.com/build1740/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1740/

2017-06-27 08:10 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1740

2017-06-27 08:10 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1740

2017-06-27 08:57 UTC, alexschedrov requested changes

2017-06-27 08:57 UTC, Sanchiz commented on modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
>  type: module
Can we change name to "OpenY Hours Formatter"?

2017-06-27 08:57 UTC, Sanchiz commented on modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
>  description: Displays today\'s working hours
Let's set "Displays working hours" to remove escaping.

2017-06-27 09:46 UTC, ivan-berezhnov commented on modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
>  type: module
Yes. Changed.

2017-06-27 10:00 UTC, alexschedrov approved these changes

2017-06-27 10:13 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1746 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1746 |
| Installation process | http://install.openy-dev.ffwua.com/build1746/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1746/

2017-06-27 10:13 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1746

2017-06-27 10:13 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1746

2017-06-27 11:24 UTC, alexschedrov approved these changes

2017-06-27 11:24 UTC, merged