[GitHub#594] Change title for footer logo link.
ymcatwincities/openy pull request #659
Opened 2017-07-05 11:17 UTC by ivan-berezhnov

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

# Issues: 
Jira https://propeople-us.atlassian.net/browse/OYPD-525
GitHub https://github.com/ymcatwincities/openy/issues/594
Drupal.org issue: 

# Steps to review:
- [ ] scroll down untill you can see footer
- [ ] find logo in the footer
- [ ] verify footer logo link have title "Site-logo"

2017-07-05 11:27 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1805 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1805 |
| Installation process | http://install.openy-dev.ffwua.com/build1805/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1805/

2017-07-05 11:28 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1805

2017-07-05 11:28 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1805

2017-07-05 11:38 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1805/profiles/contrib/openy/build/reports/behat

2017-07-05 13:26 UTC, alexschedrov requested changes

2017-07-05 13:26 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/page/page--footer.html.html.twig
> +        <a href="{{ front_page }}" class="footer__brand brand" title="{{ "Site-logo"|t }}"{{ background_image|raw }}></a>
This change affects only footer for 3rd party services http://ci.openymca.org/build1805/footer.html.

We need to cover 3 other use cases:
- Footer in global template https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/page/page.html.twig#L157
- Footer on camp page https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/page/page--node--camp.html.twig#L45
- Landing page associated with Camp https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/page/page--node--landing-page--has-camp.html.twig#L45

2017-07-05 14:21 UTC, Sanchiz commented
retest this please

2017-07-05 14:39 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1810 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1810 |
| Installation process | http://install.openy-dev.ffwua.com/build1810/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1810/

2017-07-05 14:39 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1810

2017-07-05 14:39 UTC, gundevel commented
Accessibility report http://ci.openymca.org/build1810/htmlsniffers.md

2017-07-05 14:48 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1810/profiles/contrib/openy/build/reports/behat

2017-07-05 14:56 UTC, Sanchiz commented
retest this please

2017-07-05 15:05 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1811 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1811 |
| Installation process | http://install.openy-dev.ffwua.com/build1811/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1811/

2017-07-05 15:05 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1811

2017-07-05 15:06 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://drupal.192.168.56.132.xip.io/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://drupal.192.168.56.132.xip.io/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://drupal.192.168.56.132.xip.io/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://drupal.192.168.56.132.xip.io/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://drupal.192.168.56.132.xip.io/blogWCAG2AAhtmlcs.txt
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1811/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1811/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1811/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1811/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1811/blogWCAG2AAhtmlcs.txt

2017-07-05 15:09 UTC, Sanchiz commented
retest this please

2017-07-05 15:15 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1811/profiles/contrib/openy/build/reports/behat

2017-07-05 15:19 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1812 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1812 |
| Installation process | http://install.openy-dev.ffwua.com/build1812/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1812/

2017-07-05 15:19 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1812

2017-07-05 15:20 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://drupal.192.168.56.132.xip.io/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://drupal.192.168.56.132.xip.io/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://drupal.192.168.56.132.xip.io/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://drupal.192.168.56.132.xip.io/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://drupal.192.168.56.132.xip.io/blogWCAG2AAhtmlcs.txt
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1812/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1812/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1812/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1812/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1812/blogWCAG2AAhtmlcs.txt

2017-07-05 15:29 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1812/profiles/contrib/openy/build/reports/behat

2017-07-06 06:55 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1816 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1816 |
| Installation process | http://install.openy-dev.ffwua.com/build1816/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1816/

2017-07-06 06:55 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1816

2017-07-06 06:56 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1816/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1816/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1816/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1816/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1816/blogWCAG2AAhtmlcs.txt

2017-07-06 07:09 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1816/profiles/contrib/openy/build/reports/behat

2017-07-06 08:49 UTC, alexschedrov approved these changes

2017-07-06 08:49 UTC, merged