[OPYD-532] GroupExPro demo content.
ymcatwincities/openy pull request #668
Opened 2017-07-07 21:01 UTC by Kerby70

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-07-07 21:08 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1830 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1830 |
| Installation process | http://install.openy-dev.ffwua.com/build1830/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1830/

2017-07-07 21:08 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1830

2017-07-07 21:09 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1830/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1830/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1830/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1830/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1830/blogWCAG2AAhtmlcs.txt

2017-07-07 21:16 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1830/profiles/contrib/openy/build/reports/behat

2017-07-11 20:17 UTC, AlexNetman commented
retest this please

2017-07-11 20:40 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1850 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1850 |
| Installation process | http://install.openy-dev.ffwua.com/build1850/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1850/

2017-07-11 20:40 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1850

2017-07-11 20:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1850/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1850/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1850/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1850/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1850/blogWCAG2AAhtmlcs.txt

2017-07-11 20:51 UTC, AlexNetman commented
![image](https://user-images.githubusercontent.com/4558228/28090005-88ed09b6-6693-11e7-9994-15d087b0abea.png)
Like this:
![image](https://user-images.githubusercontent.com/4558228/28090064-b9d6b892-6693-11e7-8e29-9d24d57b8923.png)
That will result in displaying results for the needed branch on page load.

2017-07-11 20:51 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1850/profiles/contrib/openy/build/reports/behat

2017-07-13 14:40 UTC, Kerby70 commented
I will need to do further research to find how to set the block config in the demo content migration. It appears the data is stored in serialized format in paragraph__field_prgf_schedules_ref.field_prgf_schedules_ref_plugin_configuration the config variable that we need to set is enabled_locations. We have a MigrateProcessPlugin (openy_menu_icon) for menu icon data serialization that may point the way, we just need to ensure the other data is included & it won't be overwritten by those defaults.

2017-07-14 19:30 UTC, Kerby70 commented
We will follow-up on the branch configuration https://propeople-us.atlassian.net/browse/YGS-754

2017-07-21 14:53 UTC, david-hernandez commented
When I try this I get the "block is broken or missing" error on the schedule page. The embedded one works. This is on a completely new install.

![screen shot 2017-07-21 at 10 51 11 am](https://user-images.githubusercontent.com/1504038/28468958-aae6d6d4-6e02-11e7-9652-2eabb17e00d0.png)

![screen shot 2017-07-21 at 10 51 23 am](https://user-images.githubusercontent.com/1504038/28468962-ad44c8be-6e02-11e7-9303-e3242477730f.png)

![screen shot 2017-07-21 at 10 53 32 am](https://user-images.githubusercontent.com/1504038/28469009-dd1dabc8-6e02-11e7-96bb-76ec5ba4df5c.png)

2017-07-21 14:55 UTC, david-hernandez commented on modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/openy_demo_nlanding.install
> + * @file OpenY Demon Landing page install file.
"Demon" typo here.

2017-07-21 14:56 UTC, david-hernandez commented on modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing.yml
> +      title: 'Group Schedules(Embedded)'
Add a space here between "Schedules" and "(Embedded)"

2017-07-21 14:56 UTC, david-hernandez commented on modules/openy_features/openy_demo_content/modules/openy_demo_menu/modules/openy_demo_menu_footer/config/install/migrate_plus.migration.menu_link_footer.yml
> +      title: 'Group Schedules(Embedded)'
Add a space here between "Schedules" and "(Embedded)".

2017-07-21 19:49 UTC, Kerby70 commented on openy.profile
> +  $schedule_paragraph_tables = ['paragraph__field_prgf_schedules_ref', 'paragraph_revision__field_prgf_schedules_ref'];
The following code should handle the broken paragraphs, though this is not new to this PR. I was not able to replicate that issue today.

2017-07-21 19:57 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1905 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1905 |
| Installation process | http://install.openy-dev.ffwua.com/build1905/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1905/

2017-07-21 19:57 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1905

2017-07-21 19:58 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1905/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1905/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1905/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1905/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1905/blogWCAG2AAhtmlcs.txt

2017-07-21 20:08 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1905/profiles/contrib/openy/build/reports/behat

2017-07-24 13:18 UTC, Sanchiz commented
retest this please

2017-07-24 13:28 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1916 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1916 |
| Installation process | http://install.openy-dev.ffwua.com/build1916/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1916/

2017-07-24 13:28 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1916

2017-07-24 13:29 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1916/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1916/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1916/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1916/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1916/blogWCAG2AAhtmlcs.txt

2017-07-24 13:40 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1916/profiles/contrib/openy/build/reports/behat

2017-07-24 13:56 UTC, alexschedrov requested changes

2017-07-24 13:56 UTC, Sanchiz commented on openy.profile
> +  $schedule_paragraph_tables = ['paragraph__field_prgf_schedules_ref', 'paragraph_revision__field_prgf_schedules_ref'];
That's correct. However this is code duplication. Can we move whole foreach to separate function that will accept:
- Condition field name, e.g. `field_prgf_schedules_ref_plugin_id`
- Serialization field name, e.g. `field_prgf_schedules_ref_plugin_configuration`
- any other params that are different...
- Array with tables.

2017-07-24 15:07 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1923 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1923 |
| Installation process | http://install.openy-dev.ffwua.com/build1923/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1923/

2017-07-24 15:07 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1923

2017-07-24 15:07 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1923/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1923/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1923/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1923/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1923/blogWCAG2AAhtmlcs.txt

2017-07-24 15:17 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1923/profiles/contrib/openy/build/reports/behat

2017-07-25 06:50 UTC, Sanchiz commented
retest this please

2017-07-25 07:10 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build1926 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build1926 |
| Installation process | http://install.openy-dev.ffwua.com/build1926/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/1926/

2017-07-25 07:11 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build1926

2017-07-25 07:12 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build1926/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build1926/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build1926/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build1926/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build1926/blogWCAG2AAhtmlcs.txt

2017-07-25 07:24 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build1926/profiles/contrib/openy/build/reports/behat

2017-07-25 09:10 UTC, alexschedrov approved these changes

2017-07-25 09:14 UTC, merged