[8.x-1.x-exp-news] News docs
ymcatwincities/openy pull request #734
Opened 2017-08-02 16:22 UTC by dimb

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-08-02 16:22 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-08-02 16:22 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-08-02 16:22 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2017-08-02 19:20 UTC, ddrozdik requested changes

2017-08-02 19:20 UTC, ddrozdik commented on docs/Content structure/Paragraphs/Featured News Posts.md
> +This is a paragraph type that will be used for the featured stories.
`... for the featured news.` - please change last word

2017-08-02 19:20 UTC, ddrozdik commented on docs/Content structure/Taxonomy/News Category.md
> +This is a vocabulary that will be used for adding blog categories on the site.
`for adding *news* categories on the site.`

2017-08-02 19:21 UTC, ddrozdik commented
@dimb please fix comments ^^. Since this PR already include demo content, let's union both prs into one.

2017-08-17 10:19 UTC, ddrozdik requested changes

2017-08-17 10:19 UTC, ddrozdik commented on docs/Content structure/Content Types/News.md
> +| Title  | drupal's default  | Yes | Title of the blog item. |
`Title of the blog item.` should be `Title of the news item.`

2017-08-17 10:19 UTC, ddrozdik commented on docs/Content structure/Paragraphs/Featured News Posts.md
> +| Blog Posts | field\_fnews_posts | Yes | Multiple values. Reference field to News posts. |
`Blog Posts` should be `News Posts`

2017-08-17 10:32 UTC, ddrozdik commented
retest this please

2017-08-17 11:17 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2100 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2100 |
| Installation process | http://install.openy-dev.ffwua.com/build2100/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2100/

2017-08-17 11:17 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2100

2017-08-17 11:18 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2100/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2100/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2100/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2100/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2100/blogWCAG2AAhtmlcs.txt

2017-08-17 11:35 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2100/profiles/contrib/openy/build/reports/behat

2017-08-18 17:27 UTC, ddrozdik commented
@dimb we need to add to each views related to news "No Result behavior" and display this text `<p>There is no news yet.</p>`

2017-10-11 12:33 UTC, ddrozdik approved these changes

2017-10-11 12:34 UTC, merged