[FIX] Add amenities tip to tour and fix tips for taxonomy and menu.
ymcatwincities/openy pull request #744
Opened 2017-08-08 16:32 UTC by ivan-berezhnov

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- [ ] Please provide steps for review here.

2017-08-08 17:36 UTC, AlexNetman commented
retest this please

2017-08-09 03:56 UTC, ivan-berezhnov commented
retest this please

2017-08-09 07:21 UTC, ivan-berezhnov commented
retest this please

2017-08-09 07:38 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2066 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2066 |
| Installation process | http://install.openy-dev.ffwua.com/build2066/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2066/

2017-08-09 07:38 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2066

2017-08-09 07:40 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2066/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2066/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2066/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2066/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2066/blogWCAG2AAhtmlcs.txt

2017-08-09 07:42 UTC, alexschedrov requested changes

2017-08-09 07:42 UTC, Sanchiz commented on modules/openy_features/openy_menu/openy_menu.install
> +	openy_menu_update_8001();
It's better to copy & paste code that triggering updates in updates. The same for update above.

2017-08-09 07:42 UTC, Sanchiz commented on modules/openy_features/openy_taxonomy/openy_taxonomy.install
> +	openy_taxonomy_update_8002();
Same here. Plus you have 4 spaces, instead of 2.

2017-08-09 07:57 UTC, ivan-berezhnov commented on modules/openy_features/openy_menu/openy_menu.install
> +	openy_menu_update_8001();
Update number two has already been completed and I do not need to change it then, right?
As I understood for update number three do 
function openy_menu_update_8003() {
	openy_menu_update_8002();
}
or you mean copy code from first update?

2017-08-09 08:00 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2066/profiles/contrib/openy/build/reports/behat

2017-08-09 08:26 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2068 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2068 |
| Installation process | http://install.openy-dev.ffwua.com/build2068/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2068/

2017-08-09 08:26 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2068

2017-08-09 08:27 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2068/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2068/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2068/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2068/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2068/blogWCAG2AAhtmlcs.txt

2017-08-09 08:57 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2068/profiles/contrib/openy/build/reports/behat

2017-08-09 09:04 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2069 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2069 |
| Installation process | http://install.openy-dev.ffwua.com/build2069/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2069/

2017-08-09 09:04 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2069

2017-08-09 09:05 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2069/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2069/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2069/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2069/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2069/blogWCAG2AAhtmlcs.txt

2017-08-09 09:25 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2070 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2070 |
| Installation process | http://install.openy-dev.ffwua.com/build2070/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2070/

2017-08-09 09:25 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2070

2017-08-09 09:27 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2070/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2070/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2070/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2070/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2070/blogWCAG2AAhtmlcs.txt

2017-08-09 09:27 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2069/profiles/contrib/openy/build/reports/behat

2017-08-09 09:45 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2071 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2071 |
| Installation process | http://install.openy-dev.ffwua.com/build2071/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2071/

2017-08-09 09:45 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2071

2017-08-09 09:47 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2071/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2071/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2071/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2071/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2071/blogWCAG2AAhtmlcs.txt

2017-08-09 09:49 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2070/profiles/contrib/openy/build/reports/behat

2017-08-09 10:14 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2071/profiles/contrib/openy/build/reports/behat

2017-08-09 11:24 UTC, AlexNetman approved these changes

2017-08-09 12:59 UTC, Sanchiz commented
retest this please

2017-08-09 13:26 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2075 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2075 |
| Installation process | http://install.openy-dev.ffwua.com/build2075/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2075/

2017-08-09 13:26 UTC, gundevel commented
Decoupling report http://ci.openymca.org/build2075

2017-08-09 13:27 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2075/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2075/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2075/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2075/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2075/blogWCAG2AAhtmlcs.txt

2017-08-09 13:44 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2075/profiles/contrib/openy/build/reports/behat

2017-08-10 06:51 UTC, merged