[OYPD-135] Move vocabularies into own packages
ymcatwincities/openy pull request #81
Opened 2017-01-30 14:26 UTC by hamrant

Jira - https://propeople-us.atlassian.net/browse/OYPD-135

Steps for review:
- [ ] login as admin
- [ ] check taxonomy vocabulary color existing
- [ ] profit

2017-01-30 14:32 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build259

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/259/

2017-01-30 14:32 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build259/profiles/openy/build/reports/behat

2017-01-30 14:59 UTC, alexschedrov requested changes

2017-01-30 14:59 UTC, Sanchiz commented on modules/openy_features/openy_node/openy_node.features.yml
> +  - taxonomy.vocabulary.color
We should remove this from here, because in the installation process they will know nothing about each other.

2017-01-30 15:07 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build261

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/261/

2017-01-30 15:08 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build261/profiles/openy/build/reports/behat

2017-01-31 07:47 UTC, Sanchiz commented
retest this please

2017-01-31 07:51 UTC, alexschedrov approved these changes

2017-01-31 07:53 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build268

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/268/

2017-01-31 07:57 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build268/profiles/openy/build/reports/behat

2017-01-31 07:57 UTC, merged