[OYPD-151] Updating small banner paragraph type
ymcatwincities/openy pull request #85
Opened 2017-01-30 18:43 UTC by david-hernandez

Changes moved from https://github.com/ymcatwincities/openy/pull/64

See 64 for responses to prior comments. In this updated the space in the folder name was fixed, and the taxonomy view mode moved to the openy_node feature.

2017-01-30 18:50 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build265

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/265/

2017-01-30 18:50 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build265/profiles/openy/build/reports/behat

2017-01-30 18:56 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build266

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/266/

2017-01-30 18:56 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build266/profiles/openy/build/reports/behat

2017-01-31 08:23 UTC, Sanchiz commented
retest this please

2017-01-31 08:29 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build272

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/272/

2017-01-31 08:29 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build272/profiles/openy/build/reports/behat

2017-01-31 08:31 UTC, alexschedrov requested changes

2017-01-31 08:31 UTC, Sanchiz commented on modules/openy_features/openy_node/config/install/core.entity_view_display.taxonomy_term.color.color.yml
> +langcode: en
In his PR https://github.com/ymcatwincities/openy/pull/81 taxonomy vocabulary has been moved to separate module. This view display should be moved as well.

2017-01-31 08:31 UTC, Sanchiz commented on modules/openy_features/openy_node/config/install/core.entity_view_mode.taxonomy_term.color.yml
> +langcode: en
In his PR https://github.com/ymcatwincities/openy/pull/81 taxonomy vocabulary has been moved to separate module. This view display should be moved as well.

2017-01-31 08:31 UTC, Sanchiz commented on modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.features.yml
> +  - core.entity_view_mode.taxonomy_term.color
We don't need excluded section here, because those view modes will live in own module and won't be listed as dependencies.

2017-01-31 13:43 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build294

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/294/

2017-01-31 13:45 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build294/profiles/openy/build/reports/behat

2017-01-31 13:46 UTC, alexschedrov requested changes

2017-01-31 13:46 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/taxonomy/taxonomy-term--color.html.twig
> +  {{- content.field_color.0['#markup'] -}}
Can we also override field_color template to return pure value instead of using `#markup`?

2017-01-31 13:51 UTC, podarok commented on themes/openy_themes/openy_rose/templates/taxonomy/taxonomy-term--color.html.twig
> +  {{- content.field_color.0['#markup'] -}}
```twig
{% set color = content.field_color.0['#markup'] ? content.field_color.0['#markup'] : 'default_color' %}
```

2017-01-31 14:13 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build295

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/295/

2017-01-31 14:13 UTC, podarok approved these changes
this looks superawesome!

2017-01-31 14:15 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build295/profiles/openy/build/reports/behat

2017-01-31 14:59 UTC, alexschedrov approved these changes

2017-01-31 14:59 UTC, merged