#857: Fix the issue image is not visible in WYSIWYG.
ymcatwincities/openy pull request #858
Opened 2017-11-14 16:19 UTC by fandm

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Issue

https://github.com/ymcatwincities/openy/issues/857

## Steps for review

- [ ] Open any node with Content field.
- [ ] Add image.
- [ ] Verify the image is visible in WYSIWYG.

2017-11-14 16:29 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2368 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2368 |
| Installation process | http://install.openy-dev.ffwua.com/build2368/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2368/

2017-11-14 16:30 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2368/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2368/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2368/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2368/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2368/blogWCAG2AAhtmlcs.txt

2017-11-14 16:42 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2368/profiles/contrib/openy/build/reports/behat

2017-11-14 17:27 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2370 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2370 |
| Installation process | http://install.openy-dev.ffwua.com/build2370/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2370/

2017-11-14 17:27 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2370/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2370/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2370/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2370/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2370/blogWCAG2AAhtmlcs.txt

2017-11-14 17:39 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2370/profiles/contrib/openy/build/reports/behat

2017-11-15 09:28 UTC, Sanchiz commented
retest this please

2017-11-15 09:36 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2371 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2371 |
| Installation process | http://install.openy-dev.ffwua.com/build2371/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2371/

2017-11-15 09:37 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2371/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2371/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2371/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2371/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2371/blogWCAG2AAhtmlcs.txt

2017-11-15 09:50 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2371/profiles/contrib/openy/build/reports/behat

2017-11-15 11:08 UTC, ddrozdik requested changes

2017-11-15 11:08 UTC, ddrozdik commented on modules/custom/openy_ckeditor/openy_ckeditor.module
> +  if (isset($context['data-widget']) && $context['data-widget'] == 'drupalentity') {
please use `return early pattern` here

2017-11-15 11:21 UTC, fandm commented on modules/custom/openy_ckeditor/openy_ckeditor.module
> +  if (isset($context['data-widget']) && $context['data-widget'] == 'drupalentity') {
Done

2017-11-15 11:29 UTC, gundevel commented
Build comment file: 
--------------
===============
 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build2373 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build2373 |
| Installation process | http://install.openy-dev.ffwua.com/build2373/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER/2373/

2017-11-15 11:29 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build2373/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build2373/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build2373/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build2373/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build2373/blogWCAG2AAhtmlcs.txt

2017-11-15 11:41 UTC, gundevel commented
Behat test results file URL: http://ci.openymca.org/build2373/profiles/contrib/openy/build/reports/behat

2017-11-15 12:06 UTC, ddrozdik approved these changes

2017-11-15 12:21 UTC, merged