[OYPD-153] Update for paragrpah gallery, adds template, image style, view mode f…
ymcatwincities/openy pull request #86
Opened 2017-01-30 22:16 UTC by david-hernandez

Adds template, updates the paragraph display mode, adds a new display mode for images, and an image style.

![screen shot 2017-01-30 at 5 08 57 pm](https://cloud.githubusercontent.com/assets/1504038/22444123/a07f73ec-e70f-11e6-8a70-ee14d9fc70a6.png)

- [ ] Add a page for a type that uses paragraphs, like landing page.
- [ ] Add a paragraph of type "gallery".
- [ ] Add multiple images and save the node.
- [ ] Make sure it looks correct.

2017-01-30 22:23 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build267

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/267/

2017-01-31 08:10 UTC, Sanchiz commented
retest this please

2017-01-31 08:16 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build271

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/271/

2017-01-31 08:16 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build271/profiles/openy/build/reports/behat

2017-01-31 08:22 UTC, alexschedrov requested changes

2017-01-31 08:22 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +{{ kint(content.field_prgf_images) }}
Please remove debug code.

2017-01-31 08:23 UTC, Sanchiz commented
1. Image style or CSS stretches the image vertically. Just compare original YGS image and build.
![image](https://cloud.githubusercontent.com/assets/1316234/22457225/3d6a490e-e79f-11e6-85c6-df628adcee98.png)
![image](https://cloud.githubusercontent.com/assets/1316234/22457229/40ba28d6-e79f-11e6-9292-54a4e0d81f31.png)

2017-01-31 13:12 UTC, podarok requested changes

2017-01-31 13:12 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +        {% if content.field_prgf_images[key]['#media'].field_media_caption.0.value is not empty %}
Use set instruction with ternary operators to get values from the fields with default fallback
Using direct data in if prohibited by best practices (without defaults debugging in a future is a bit tough)
Example
```twig
{% set color = content.field_blog_color ? content.field_blog_color : 'red' %}
```

2017-01-31 13:12 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +    {% if content.field_prgf_images['#items']|length > 1 %}
Use set instruction with ternary operators to get values from the fields with default fallback
Using direct data in if prohibited by best practices (without defaults debugging in a future is a bit tough)
Example
```twig
{% set color = content.field_blog_color ? content.field_blog_color : 'red' %}
```

2017-01-31 13:12 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +  {% if content.field_prgf_headline['#field_name'] is not empty %}
Use set instruction with ternary operators (at the top of the template) to get values from the fields with default fallback
Using direct data in if prohibited by best practices (without defaults debugging in a future is a bit tough)
Example
```twig
{% set color = content.field_blog_color ? content.field_blog_color : 'red' %}
```

2017-01-31 13:12 UTC, podarok commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +{% if content.field_prgf_images['#items']|length >= 1 %}
Use set instruction with ternary operators to get values from the fields with default fallback
Using direct data in if prohibited by best practices (without defaults debugging in a future is a bit tough)
Example
```twig
{% set color = content.field_blog_color ? content.field_blog_color : 'red' %}
```

2017-01-31 17:34 UTC, david-hernandez commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +  {% if content.field_prgf_headline['#field_name'] is not empty %}
I don't understand what you are suggesting with these. There is no use for a ternary operator here. Nothing is being set. Can you clarify?

2017-01-31 22:57 UTC, david-hernandez commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +  {% if content.field_prgf_headline['#field_name'] is not empty %}
I'm removing this if. The headline field is required so there is no need for it anyway.

2017-01-31 23:03 UTC, david-hernandez commented
Something happened to the icon display mode for images. It is not a display mode that was part of this paragraph but was reused. It used to return an icon sized image using an image style. Now it returns "original image" which could be bad.

2017-01-31 23:05 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build301

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/301/

2017-01-31 23:07 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build301/profiles/openy/build/reports/behat

2017-02-01 08:42 UTC, Sanchiz commented
retest this please

2017-02-01 08:43 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +        {% if content.field_prgf_images[key]['#media'].field_media_caption.0.value is not empty %}
Let's fix this in follow up.

2017-02-01 08:43 UTC, Sanchiz commented on themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
> +    {% if content.field_prgf_images['#items']|length > 1 %}
Let's fix this in follow up.

2017-02-01 08:45 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build307

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/307/

2017-02-01 08:47 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build307/profiles/openy/build/reports/behat

2017-02-01 08:52 UTC, alexschedrov approved these changes

2017-02-01 08:52 UTC, merged