[OYPD-110] Migrate demo content while installation
ymcatwincities/openy pull request #88
Opened 2017-01-31 15:57 UTC by danylevskyi

Task: OYPD-110

### How to review

1. Install site via `reinstall.sh` and you should see `blog` and `branch` demo content.
2. Install site via browser and you should see additional installation step `Import demo content`. Select appropriate content to import.

**NOTE**, `landing` and `programs` content are not migrated (there is no migrations).

2017-01-31 16:00 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>2</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build297/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build297

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/297/

2017-01-31 16:02 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build297/profiles/openy/build/reports/behat

2017-01-31 16:07 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build298

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/298/

2017-01-31 16:09 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build298/profiles/openy/build/reports/behat

2017-02-01 08:31 UTC, alexschedrov requested changes

2017-02-01 08:31 UTC, Sanchiz commented on src/ContentImporter.php
> +    // @todo Set dependencies for "landing" and "programs".
Landing pages, programs and categories have been added in PRs #89 and #91. Let's include them here.

2017-02-01 08:31 UTC, Sanchiz commented on src/ContentImporter.php
> +  }
Should we also trigger there taxonomy terms or they will be triggered automatically?

2017-02-01 08:31 UTC, Sanchiz commented on src/ContentImporter.php
> +  public function getMap() {
We should also trigger migration for footer blocks https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_demo_content/modules/openy_demo_bfooter, but there's dependency on block configuration. So, could be tricky to resolve dependencies.

2017-02-01 08:32 UTC, Sanchiz commented
@danylevskyi it looks awesome!!! 🏆

2017-02-01 13:11 UTC, danylevskyi commented on src/ContentImporter.php
> +  }
All dependencies are handled automatically (if they specified in migrations)

2017-02-01 13:57 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build315/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build315

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/315/

2017-02-01 13:58 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build315/profiles/openy/build/reports/behat

2017-02-01 14:01 UTC, gundevel commented
Build comment file: 
--------------
===============
<strong>4</strong>  errors for CodeSniffer: Drupal standard file http://openy-dev.ffwua.com/build316/build_reports/Drupalsniff.txt
Build site installed at http://openy-dev.ffwua.com/build316

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/316/

2017-02-01 14:03 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build316/profiles/openy/build/reports/behat

2017-02-01 14:13 UTC, gundevel commented
Build comment file: 
--------------
===============
Build site installed at http://openy-dev.ffwua.com/build318

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy-dev.ffwua.com:8080/job/PR_BUILDER/318/

2017-02-01 14:14 UTC, gundevel commented
Behat test results file URL: http://openy-dev.ffwua.com/build318/profiles/openy/build/reports/behat

2017-02-01 14:28 UTC, alexschedrov approved these changes

2017-02-01 14:28 UTC, Sanchiz commented
@danylevskyi For some reason facility type vocabulary is empty.
![image](https://cloud.githubusercontent.com/assets/1316234/22510635/675f7976-e89b-11e6-9278-0f5c2a65f39f.png)

2017-02-01 16:01 UTC, merged