Daxko2 API integration
ymcatwincities/openy pull request #942
Opened 2018-02-05 20:30 UTC by ygerasimov

Module allows importing Categories (OpenY's classes) and Offerings (OpenY's sessions) into Drupal.

Depends on migrate_source_csv module. See site openy-daxko.ixm.ca for demo. Under programs you can see "Daxko ..." classes. These are the ones imported from CRM. Example http://openy-daxko.ixm.ca/programs/swimming/swim-lessons/daxko-preschool-stage-2-water-movement/class-times?location=all

2018-02-05 20:45 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build270 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build270 |
| Installation process | http://install.openy-dev.ffwua.com/build270/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/270/

2018-02-05 20:46 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build270/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build270/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build270/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build270/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build270/blogWCAG2AAhtmlcs.txt

2018-02-05 21:05 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build270/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build270/profiles/contrib/openy/build/reports/behat/screenshots

2018-02-09 13:28 UTC, AlexNetman commented
retest this please

2018-02-09 13:49 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build306 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build306 |
| Installation process | http://install.openy-dev.ffwua.com/build306/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/306/

2018-02-09 13:49 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build306/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build306/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build306/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build306/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build306/blogWCAG2AAhtmlcs.txt

2018-02-09 14:06 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build306/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build306/profiles/contrib/openy/build/reports/behat/screenshots

2018-02-09 14:51 UTC, podarok requested changes
Thanks for the code
It is not perfect, but with small tweaks should be working and a good MVP
Please, fix code review issues and automatic code linters errors

2018-02-09 14:51 UTC, podarok commented on modules/custom/openy_daxko2/src/Form/ImportForm.php
> +    db_query('UPDATE {node_field_data} SET status=1 WHERE status=13');
Is it possible to use db_update here?
We should think about the possibility to have this code working on SQLite and MSSQL. db_query makes this impossible

2018-02-09 14:51 UTC, podarok commented on modules/custom/openy_daxko2/src/Form/ImportForm.php
> +              $value = substr($value, 0, 10);
Could you make 10 as a class const to be self-explanatory?

2018-02-09 14:51 UTC, podarok commented on modules/custom/openy_daxko2/src/Form/ImportForm.php
> +//      drupal_set_message(json_encode($programsResponse));
Please, remove debug code

2018-02-09 14:51 UTC, podarok commented on modules/custom/openy_daxko2/src/Form/ImportForm.php
> +    unlink('/tmp/programs.csv');
This code won't work on 2+ webheads (any enterprise hosting with load balancing). We need to take this into consideration and make this path configurable and use by default Drupal temp folder settings.

2018-02-09 14:51 UTC, podarok commented on modules/custom/openy_daxko2/config/install/migrate_plus.migration_group.daxko.yml
> +module: null
I see an error here. Module can't be null. There is some broken dependency needs to be fixed

2018-02-09 15:25 UTC, AlexNetman commented
I have enabled module for current build.

2018-02-19 20:05 UTC, ygerasimov commented
@podarok I've adjusted the code. Meanwhile, I kept CSV files to be saved to /tmp/ folder.

Reasons behind it:

- changing to drupal's temporary directory would make life harder from migration standpoint. The path to file is hardcoded in the config. Please advise if there is a workaround (besides writing own fetcher).
- Regarding load balanced environment. Normally balancers keep opened the session. So once a session is opened user is hitting exactly same webhead. In this way, it is completely safe saving files to /tmp/ folder.

Please advise if we still need to avoid using /tmp/ folder. Then we would need to write custom migration fetcher and point it to drupal's temporary folder.

2018-02-19 20:11 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build328 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build328 |
| Installation process | http://install.openy-dev.ffwua.com/build328/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/328/

2018-02-19 20:12 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build328/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build328/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build328/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build328/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build328/blogWCAG2AAhtmlcs.txt

2018-02-19 20:23 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build329 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build329 |
| Installation process | http://install.openy-dev.ffwua.com/build329/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/329/

2018-02-19 20:24 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build329/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build329/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build329/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build329/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build329/blogWCAG2AAhtmlcs.txt

2018-02-19 20:27 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build328/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build328/profiles/contrib/openy/build/reports/behat/screenshots

2018-02-19 20:33 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build329/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build329/profiles/contrib/openy/build/reports/behat/screenshots

2018-02-22 10:21 UTC, podarok commented
@ygerasimov 
Could you please record a video about this integration and send avi(any format) to me? I'll post the video to OpenY Youtube channel after release /cc @YMCA-GTC @ymcagtc

2018-02-22 10:21 UTC, merged