Update OpenY Header according to the new design
ymcatwincities/openy pull request #982
Opened 2018-03-06 18:38 UTC by kolesnikoff

Make sure these boxes are checked before asking for review of your pull request - thank you!

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/ci-errors.png" width="200" alt="CI code sniffer errors">
- [ ] All tests are running and there are no failed tests reported by CI. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/behat.png" width="200" alt="Behat test results">
- [ ] [Documentation](https://github.com/ymcatwincities/openy/tree/8.x-1.x/docs) has been updated according to PR changes.
- [ ] [Steps for review](https://github.com/ymcatwincities/openy/pull/94#issue-204580200) have been provided according to PR changes. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/steps-for-review.png" width="200" alt="Steps for review"/>
- [ ] Make sure you've provided all necessary hook\_update\_N to [support upgrade path](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Upgrade%20path.md).
- [ ] Make sure your git email is associated with account on drupal.org, otherwise you won't get commits there. <br/><img src="https://raw.githubusercontent.com/ymcatwincities/openy/8.x-1.x/.github/assets/drupalorg-email.png" width="200" alt="drupal.org email"/>
- [ ] If you would like to get credits on drupal.org, [check documentation](https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Development/Contributing.md#drupalorg-credits).

Thank you for your contribution!

## Steps for review

- Pull the code and clear the cache. An updated header should appear on the desktop and mobile versions.

2018-03-06 18:41 UTC, kolesnikoff commented
@podarok please review.
If it is possible to set up automatically some testing environment for UAT it would be great. 
Otherwise, I'll set it up on my own.

2018-03-06 18:46 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build374 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build374 |
| Installation process | http://install.openy-dev.ffwua.com/build374/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/374/

2018-03-06 18:47 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build374/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build374/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build374/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build374/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build374/blogWCAG2AAhtmlcs.txt

2018-03-07 12:42 UTC, podarok commented
retest this please

2018-03-07 12:43 UTC, podarok commented
I guess we are fine with having builds
Or you need additional demo site to be able to use it for a long time?

2018-03-07 12:50 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build375 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build375 |
| Installation process | http://install.openy-dev.ffwua.com/build375/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/375/

2018-03-07 12:51 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build375/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build375/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build375/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build375/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build375/blogWCAG2AAhtmlcs.txt

2018-03-07 13:30 UTC, podarok requested changes
@kolesnikoff 
Looks good. Minor changes, please

2018-03-07 13:30 UTC, podarok commented on themes/openy_themes/openy_rose/css/styles.css
> +  @include breakpoint($screen-tablet) {
Please, remove debug or any code comments

2018-03-07 13:30 UTC, podarok commented on themes/openy_themes/openy_rose/css/styles.css
> +  border-bottom: 1px solid $dark-blue;
remove code comments, please

2018-03-07 13:30 UTC, podarok commented on themes/openy_themes/openy_rose/scss/modules/_menu.scss
> +  //border: 1px solid $white;
remove code comments, please

2018-03-07 13:30 UTC, podarok commented on themes/openy_themes/openy_rose/scss/modules/_menu.scss
> +        z-index: 1001;
Could you make z-index as sass variable? Just in case  for future

2018-03-07 13:30 UTC, podarok commented on themes/openy_themes/openy_rose/scss/modules/_menu.scss
> +      /*
code comments removal needed

2018-03-16 14:26 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-03-17 10:11 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build382 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build382 |
| Installation process | http://install.openy-dev.ffwua.com/build382/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/382/

2018-03-17 10:12 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build382/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build382/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build382/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build382/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build382/blogWCAG2AAhtmlcs.txt

2018-03-17 10:16 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build382/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build382/profiles/contrib/openy/build/reports/behat/screenshots

2018-03-17 11:51 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build383 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build383 |
| Installation process | http://install.openy-dev.ffwua.com/build383/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/383/

2018-03-17 11:51 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build383/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build383/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build383/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build383/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build383/blogWCAG2AAhtmlcs.txt

2018-03-17 11:55 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build383/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build383/profiles/contrib/openy/build/reports/behat/screenshots

2018-03-17 11:59 UTC, kolesnikoff commented
@podarok I've updated the code according to your feedback and restored initial OpenY colors. Please review.

2018-03-17 12:11 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build384 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build384 |
| Installation process | http://install.openy-dev.ffwua.com/build384/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.openymca.org:8080/job/PR_BUILDER_COMPOSER/384/

2018-03-17 12:11 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build384/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build384/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build384/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build384/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build384/blogWCAG2AAhtmlcs.txt

2018-03-17 12:16 UTC, gundevel commented
Behat test results file URL http://ci.openymca.org/build384/profiles/contrib/openy/build/reports/behat and failed screenshots http://ci.openymca.org/build384/profiles/contrib/openy/build/reports/behat/screenshots

2018-03-22 13:07 UTC, podarok commented
retest this please

2018-03-22 13:32 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://ci.openymca.org/build245 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build245 |
| Installation process | http://install.openy-dev.ffwua.com/build245/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/245/

2018-03-22 13:54 UTC, podarok approved these changes

2018-03-22 13:55 UTC, merged