Easy 301 Redirects from Content Editing Flow
ymcatwincities/openy pull request #990
Opened 2018-03-22 13:56 UTC by rotator

https://trello.com/c/D5wBxuBA/107-easy-301-redirects-from-content-editing-flow-score-6

Steps to review:
1. Open node edit page. Find Redirects fieldset on the right side. 
2. Add all URLs to redirect to this node and save it.
3. Go to Redirect list page "/admin/config/search/redirect?order=created&sort=desc" and check new redirects.

2018-03-22 13:59 UTC, gundevel commented
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

2018-04-05 08:23 UTC, podarok requested changes
Sorry, a lot of architecture and logic issues in the code. We can't add the code which will create a bunch of hard to resolve bugs.
Please continue work on this

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.info.yml
> +package: OpenY
Please, put the version into module info file
Start with 8.0.1 if it will have additional work or 8.1.0 to manifest stable release
If it is not stable - mark it as an experimental for now, please

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +    // Add custom submit to create redirects
fullstop, please

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +    // Set default values
fullstop, please

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +    // Set total count of redirect items for correct behavior "Add more" ajax button
fullstop, please

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +      $i++;
why not using ```for``` control structure?
Could we refactor this to use http://php.net/manual/en/control-structures.for.php ?

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +  // Delete all redirects for this node to save it from scratch later
fullstop, please

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +      $item->delete();
What happens if There are some needed redirects in place? We have multilingual sites where for the same node there are multilingual redirects. This code will remove them all.
Let's ensure the user has control over which redirects should be removed before removing them

2018-04-05 08:23 UTC, podarok commented on modules/custom/openy_redirect/openy_redirect.module
> +    ->condition('redirect_redirect__uri', '%' . $uri . '%', 'LIKE')
this means if there are URIs like ```/contact``` and ```/location/contact``` - current method loads both of them and the code above will do remove them out. Sorry, but this is not acceptable.

2018-04-05 08:25 UTC, podarok commented
ok to test

2018-04-05 08:36 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/268/

**Build Log**
*last 1000 lines*

 ```
[...truncated 426 lines...]
 > git rev-parse remotes/origin/pr/533/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/564/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/565/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/566/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/568/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/569/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/57/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/572/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/574/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/575/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/576/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/577/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/578/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/579/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/58/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/580/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/581/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/583/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/584/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/585/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/586/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/587/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/589/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/59/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/590/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/591/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/592/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/6/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/60/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/601/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/604/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/605/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/607/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/608/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/609/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/61/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/611/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/612/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/613/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/614/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/615/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/616/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/617/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/618/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/619/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/62/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/620/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/622/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/623/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/624/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/625/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/627/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/628/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/629/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/63/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/630/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/631/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/632/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/633/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/637/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/638/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/639/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/64/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/641/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/642/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/643/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/644/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/645/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/646/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/648/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/649/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/65/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/657/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/658/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/659/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/66/head^{commit} # timeout=10
 > git rev-parse  [...]

2018-04-05 08:56 UTC, podarok commented
Also, fix the reinstall, as you can see it doesn't work

2018-04-17 10:10 UTC, podarok commented
ok to test

2018-04-17 10:29 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/278/

**Build Log**
*last 1000 lines*

 ```
[...truncated 340 lines...]
 > git rev-parse remotes/origin/pr/416/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/418/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/42/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/420/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/420/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/421/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/422/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/425/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/426/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/429/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/43/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/430/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/433/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/434/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/44/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/445/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/447/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/449/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/450/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/451/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/452/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/453/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/454/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/455/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/456/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/458/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/46/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/47/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/470/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/471/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/473/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/474/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/476/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/48/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/49/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/496/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/5/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/50/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/504/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/51/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/511/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/513/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/519/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/52/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/520/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/521/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/522/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/523/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/525/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/526/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/527/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/528/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/53/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/532/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > gi [...]

2018-04-19 13:25 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/284/

**Build Log**
*last 1000 lines*

 ```
[...truncated 350 lines...]
 > git rev-parse remotes/origin/pr/421/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/422/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/425/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/426/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/429/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/43/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/430/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/433/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/434/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/44/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/445/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/447/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/449/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/450/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/451/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/452/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/453/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/454/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/455/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/456/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/458/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/46/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/47/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/470/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/471/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/473/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/474/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/476/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/48/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/49/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/496/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/5/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/50/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/504/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/51/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/511/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/513/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/519/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/52/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/520/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/521/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/522/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/523/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/525/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/526/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/527/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/528/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/53/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/532/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git [...]

2018-04-20 11:58 UTC, gundevel commented
Build comment file: 
--------------


--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/286/

**Build Log**
*last 1000 lines*

 ```
[...truncated 354 lines...]
 > git rev-parse remotes/origin/pr/425/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/426/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/429/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/43/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/430/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/432/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/433/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/434/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/44/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/445/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/446/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/447/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/449/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/45/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/450/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/451/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/452/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/453/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/454/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/455/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/456/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/458/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/46/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/464/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/465/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/47/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/470/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/471/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/473/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/474/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/476/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/48/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/486/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/487/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/488/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/489/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/49/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/490/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/491/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/493/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/494/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/496/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/497/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/5/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/50/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/504/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/506/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/51/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/511/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/513/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/519/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/52/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/520/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/521/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/522/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/523/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/525/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/526/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/527/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/528/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/529/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/53/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/530/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/531/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/532/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/533/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/534/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/535/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/536/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/537/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/538/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/539/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/54/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/540/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/543/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/544/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/545/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/546/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/547/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/548/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/549/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/55/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/550/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/551/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/552/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/553/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/554/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/556/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/557/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/559/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/56/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/560/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/head^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/562/merge^{commit} # timeout=10
 > git rev-parse remotes/origin/pr/563/head^{commit} # timeout=10
 > gi [...]

2018-04-20 13:09 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build287 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build287 |
| Installation process | http://install.openy-dev.ffwua.com/build287/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/287/

2018-04-20 13:14 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build287/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build287/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build287/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build287/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build287/blogWCAG2AAhtmlcs.txt

2018-04-20 13:25 UTC, kolesnikoff commented
@podarok, main functional issues are fixed. Please review.

2018-04-20 16:54 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build288 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build288 |
| Installation process | http://install.openy-dev.ffwua.com/build288/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/288/

2018-04-20 16:59 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build288/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build288/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build288/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build288/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build288/blogWCAG2AAhtmlcs.txt

2018-04-23 11:56 UTC, gundevel commented
Build comment file: 
--------------

 
| Environment | Link |
| ------------- | ------------- |
| Fresh OpenY installation | http://openy.cibox.tools/build289 |
| Upgraded(upgrade path) installation | http://upgrade.openy-dev.ffwua.com/build289 |
| Installation process | http://install.openy-dev.ffwua.com/build289/install.php |

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://openy.cibox.tools:8080/job/PR_BUILDER_COMPOSER/289/

2018-04-23 12:01 UTC, gundevel commented
Acessibility Sniffer: front page checking WCAG2AA http://ci.openymca.org/build289/frontWCAG2AAhtmlcs.txt
Acessibility Sniffer: join page checking WCAG2AA http://ci.openymca.org/build289/joinWCAG2AAhtmlcs.txt
Acessibility Sniffer: locations page checking WCAG2AA http://ci.openymca.org/build289/locationsWCAG2AAhtmlcs.txt
Acessibility Sniffer: schedules page checking WCAG2AA http://ci.openymca.org/build289/schedulesWCAG2AAhtmlcs.txt
Acessibility Sniffer: blog page checking WCAG2AA http://ci.openymca.org/build289/blogWCAG2AAhtmlcs.txt

2018-04-24 11:45 UTC, merged

2018-04-24 11:46 UTC, podarok commented
Thanks, merged